openapi: 3.0.0
servers:
  - description: "SwaggerHub API Auto Mocking"
    url: https://virtserver.swaggerhub.com/VNGRealisatie/api/bevragingen_ingeschreven_personen/v1
  - description: "Referentie-implementatie"
    url: https://www.voorbeeldgemeente.nl/api/bevragingen_ingeschreven_personen/v1
info:
  title: Bevragingen ingeschreven personen
  description: "Koppelvlak voor het ontsluiten van gegevens van andere basisregistraties. In het kader van de bevraging ingeschreven persoon is er beoefte aan een endpoint waar gegevens van een nummeraanduiding opgehaald kunnen worden. Zolang er geen API voor de BAG is gerealiseerd wordt de endpoint voor de nummeraanduiding apart vormgegeven. Zie de [Functionele documentatie](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/functionele_specificaties.md) voor nadere toelichting."
  version: "1.0"
  contact:
    url: https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
paths:
  /nummeraanduidingen/{identificatiecodenummeraanduiding}:
    get:
      operationId: nummeraanduidingenIdentificatiecodenummeraanduiding
      description: "Het ophalen van een nummeraanduiding"
      parameters: 
        - in: query
          name: expand
          description: "Hier kan aangegeven worden welke gerelateerde resources meegeladen moeten worden. Resources en velden van resources die gewenst zijn kunnen in de expand parameter kommagescheiden worden opgegeven. Specifieke velden van resource kunnen worden opgegeven door het opgeven van de resource-naam gevolgd door de veldnaam, met daartussen een punt."
          required: false
          schema:
            type: string
            example: kinderen,adressen.postcode,adressen.huisnummer
        - in: query
          name: fields
          description: "Geeft de mogelijkheid de inhoud van de body van het antwoord naar behoefte aan te passen. Bevat een door komma's gescheiden lijst van veldennamen. Als niet-bestaande veldnamen worden meegegeven wordt een 400 Bad Request teruggegeven. Wanneer de parameter fields niet is opgenomen, worden alle gedefinieerde velden die een waarde hebben teruggegeven."
          required: false
          schema:
            type: string
            example: id,onderwerp,aanvrager,wijzig_datum
        - in: path
          name: identificatiecodenummeraanduiding
          description: "De unieke aanduiding van een NUMMERAANDUIDING. zie toelichting BAG Combinatie van de viercijferige 'gemeentecode' (volgens GBA tabel 33, Gemeententabel), de tweecijferige 'objecttypecode' en een voor het betreffende objecttype binnen een gemeente uniek tiencijferig 'objectvolgnummer'. De objecttypecode kent in de BAG de volgende waarde:20 nummeraanduiding."
          required: true
          schema:
            type: string
            maxLength: 16
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            api-version:
              $ref: '#/components/headers/api_version'
            warning:
              $ref: '#/components/headers/warning'
            X-Rate-Limit-Limit:
              $ref: '#/components/headers/X_Rate_Limit_Limit'
            X-Rate-Limit-Remaining:
              $ref: '#/components/headers/X_Rate_Limit_Remaining'
            X-Rate-Limit-Reset:
              $ref: '#/components/headers/X_Rate_Limit_Reset'  
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Nummeraanduiding'
        default:
          description: "Er is een onverwachte fout opgetreden."
          content:
            application/problem+json:
              schema:  
                $ref: '#/components/schemas/Foutbericht'
      tags: 
      - nummeraanduidingen
components:
  schemas:
    Nummeraanduiding:
      type: "object"
      description: "Een door het bevoegde gemeentelijke orgaan als zodanig toegekende\
        \ aanduiding van een VERBLIJFSOBJECT, een STANDPLAATS of een LIGPLAATS. Zie\
        \ de toelichting in de Catalogus BAG. In aanvulling hierop het volgende. Het\
        \ betreft alle gegevens en relaties van de NUMMERAANDUIDING zoals deze in\
        \ de BAG gedefinieerd zijn. NUMMERAANDUIDING is gemodelleerd als een specialisatie\
        \ van ADRESSEERBAAR OBJECT AANDUIDING. Daar bij overige (officieel vastgestelde)\
        \ adressen deels vergelijkbare gegevens en relaties van toepassing zijn, zijn\
        \ desbetreffende gegevens gemodelleerd bij ADRESSEERBAAR OBJECT AANDUIDING,\
        \ de verzameling van nummeraanduidingen en overige adresseerbaar object aanduidingen."
      properties:
        identificatiecodeNummeraanduiding:
          type: "string"
          title: "Identificatiecode nummeraanduiding"
          description: "De unieke aanduiding van een NUMMERAANDUIDING. zie toelichting\
            \ BAG Combinatie van de viercijferige 'gemeentecode' (volgens GBA tabel\
            \ 33, Gemeententabel), de tweecijferige 'objecttypecode' en een voor het\
            \ betreffende objecttype binnen een gemeente uniek tiencijferig 'objectvolgnummer'.\
            \ De objecttypecode kent in de BAG de volgende waarde:20 nummeraanduiding."
          maxLength: 16
        huisnummer:
          type: "integer"
          title: "Huisnummer"
          description: "Een door of namens het bevoegd gemeentelijk orgaan ten aanzien\
            \ van een adresseerbaar object toegekende nummering. Dit attribuutsoort\
            \ is in de BAG gespecificeerd bij het objecttype NUMMERAANDUIDING. Het\
            \ is bij de ADRESSEERBAAR OBJECT AANDUIDING opgenomen aangezien naast\
            \ de NUMMERAANDUIDING de OVERIG ADRESSEERBAAR OBJECT AANDUIDING wordt\
            \ onderscheiden. Aangezien de ADRESSEERBAAR OBJECT AANDUIDING een generalisatie\
            \ is van NUMMERAANDUIDING en OVERIG ADRESSEERBAAR OBJECT AANDUIDING overerven\
            \ beide laatstgenoemde objecttypen dit attribuutsoort. Zie verder de toelichting\
            \ in de BAG. Alle natuurlijke getallen tussen 1 en 99999."
        huisletter:
          type: "string"
          title: "Huisletter"
          description: "Een door of namens het bevoegd gemeentelijk orgaan ten aanzien\
            \ van een adresseerbaar object toegekende toevoeging aan een huisnummer\
            \ in de vorm van een alfanumeriek teken. Dit attribuutsoort is in de BAG\
            \ gespecificeerd bij het objecttype NUMMERAANDUIDING. Het is bij de ADRESSEERBAAR\
            \ OBJECT AANDUIDING opgenomen aangezien naast de NUMMERAANDUIDING de OVERIG\
            \ ADRESSEERBAAR OBJECT AANDUIDING wordt onderscheiden. Aangezien de ADRESSEERBAAR\
            \ OBJECT AANDUIDING een generalisatie is van NUMMERAANDUIDING en OVERIG\
            \ ADRESSEERBAAR OBJECT AANDUIDING overerven beide laatstgenoemde objecttypen\
            \ dit attribuutsoort. Zie verder de toelichting in de BAG. a - z , A ?\
            \ Z"
          maxLength: 1
        huisnummertoevoeging:
          type: "string"
          title: "Huisnummertoevoeging"
          description: "Een door of namens het bevoegd gemeentelijk orgaan ten aanzien\
            \ van een adresseerbaar object toegekende nadere toevoeging aan een huisnummer\
            \ of een combinatie van huisnummer en huisletter. Dit attribuutsoort is\
            \ in de BAG gespecificeerd bij het objecttype NUMMERAANDUIDING. Het is\
            \ bij de ADRESSEERBAAR OBJECT AANDUIDING opgenomen aangezien naast de\
            \ NUMMERAANDUIDING de OVERIG ADRESSEERBAAR OBJECT AANDUIDING wordt onderscheiden.\
            \ Aangezien de ADRESSEERBAAR OBJECT AANDUIDING een generalisatie is van\
            \ NUMMERAANDUIDING en OVERIG ADRESSEERBAAR OBJECT AANDUIDING overerven\
            \ beide laatstgenoemde objecttypen dit attribuutsoort. Zie verder de toelichting\
            \ in de BAG. a - z , A - Z , 0 ? 9"
          maxLength: 4
        postcode:
          type: "string"
          title: "Postcode"
          description: "De door PostNL vastgestelde code behorende bij een bepaalde\
            \ combinatie van een naam van een woonplaats, naam van een openbare ruimte\
            \ en een huisnummer Dit attribuutsoort is in de BAG gespecificeerd bij\
            \ het objecttype NUMMERAANDUIDING. Het is bij de ADRESSEERBAAR OBJECT\
            \ AANDUIDING opgenomen aangezien naast de NUMMERAANDUIDING de OVERIG ADRESSEERBAAR\
            \ OBJECT AANDUIDING wordt onderscheiden. Aangezien de ADRESSEERBAAR OBJECT\
            \ AANDUIDING een generalisatie is van NUMMERAANDUIDING en OVERIG ADRESSEERBAAR\
            \ OBJECT AANDUIDING overerven beide laatstgenoemde objecttypen dit attribuutsoort.\
            \ Zie verder de toelichting in de BAG."
          pattern: "^[1-9]{1}[0-9]{3}[A-Z]{2}$"
        _links:
          $ref: "#/components/schemas/Nummeraanduiding_links"
        _embedded:
          $ref: "#/components/schemas/Nummeraanduiding_embedded"
    Woonplaats:
      type: "object"
      description: "Een door het bevoegde gemeentelijke orgaan als zodanig aangewezen\
        \ en van een naam voorzien gedeelte van het grondgebied van de gemeente. In\
        \ incidentele gevallen komt het voor dat een woonplaats (in de zin van het\
        \ gebied dat in de praktijk aangeduid wordt met dezelfde woonplaatsnaam) doorsneden\
        \ wordt door een gemeentegrens. Volgens de definitie zou dit niet kunnen c.q.\
        \ is een woonplaats anders gedefinieerd en dus afgebakend: ?gedeelte van het\
        \ gemeentelijk grondgebied?. Vooralsnog wordt uitgegaan van de BAG-insteek\
        \ en wordt afgewacht hoe dit opgelost wordt in de landelijk te specificeren\
        \ woonplaatsentabel."
      properties:
        woonplaatsidentificatie:
          type: "string"
          title: "Woonplaatsidentificatie"
          description: "De unieke aanduiding van een WOONPLAATS, zoals opgenomen in\
            \ de landelijke woonplaatsentabel. Zie verder de toelichting in de BAG.\
            \ 0001 tot en met 9999"
          maxLength: 4
        woonplaatsnaam:
          type: "string"
          title: "Woonplaatsnaam"
          description: "De door het bevoegde gemeentelijke orgaan aan een WOONPLAATS\
            \ toegekende benaming. Zie verder de toelichting in de BAG. Tekens gecodeerd\
            \ volgens de UTF-8 standaard."
          maxLength: 80
        woonplaatsnaamNen:
          type: "string"
          title: "Woonplaatsnaam NEN"
          description: "De officiële plaatsnaam conform NEN Het attribuut bevat een\
            \ verkorte naam ten opzichte van de officiële woonplaatsnaam zoals geregistreerd\
            \ in de BAG. kapitaal geschreven en met leestekens (géén diacrieten).\
            \ Indien langer dan 24 posities verkort volgens NEN. (bron: https://secure2.dataonline.nl/mijnpostcode/sites/cendris.net.mijnpostcode/files/Postcode-informatie%20handleiding.pdf\
            \ )"
          maxLength: 24
        _links:
          $ref: "#/components/schemas/Woonplaats_links"
    OpenbareRuimte:
      type: "object"
      description: "Een door het bevoegde gemeentelijke orgaan als zodanig aangewezen\
        \ en van een naam voorziene buitenruimte die binnen één woonplaats is gelegen\
        \ Als openbare ruimte worden onder meer aangemerkt wegen, water, spoorbanen\
        \ en landschappelijke gebieden."
      properties:
        identificatiecodeOpenbareRuimte:
          type: "string"
          title: "Identificatiecode openbare ruimte"
          description: "De unieke aanduiding van een OPENBARE RUIMTE. Zie verder de\
            \ toelichting in de BAG. Combinatie van het (viercijferig) subdomein 'gemeentecode'\
            \ (volgens GBA tabel 33, Gemeententabel), het (tweecijferig) subdomein\
            \ 'objecttypecode' en een voor het betreffende objecttype binnen een gemeente\
            \ uniek (tiencijferig) subdomein 'objectvolgnummer'."
          maxLength: 16
        naamOpenbareRuimte:
          type: "string"
          title: "Naam openbare ruimte"
          description: "Een door het bevoegde gemeentelijke orgaan aan een OPENBARE\
            \ RUIMTE toegekende benaming Zie verder de toelichting in de BAG. Tekens\
            \ gecodeerd volgens de UTF-8 standaard"
          maxLength: 80
        straatnaam:
          type: "string"
          title: "Straatnaam"
          description: "De officiële straatnaam zoals door het bevoegd gemeentelijk\
            \ orgaan is vastgesteld, zo nodig ingekort conform de specificaties van\
            \ de NEN 5825. Voor straatnamen langer dan 24 posities gelden inkortingsregels.\
            \ Hiervoor wordt NEN 5825 (versie 2002) gevolgd. De hier gehanteerde schrijfwijze\
            \ kan afwijken van de POSTNL-schrijfwijze. alle alfanumrieke tekens"
          maxLength: 24
        _links:
          $ref: "#/components/schemas/OpenbareRuimte_links"
    Nummeraanduiding_links:
      type: "object"
      properties:
        self:
          $ref: "#/components/schemas/Link"
        woonplaatsen:
          title: "ligtIn"
          type: "object"
          description: ""
          properties:
            href:
              $ref: "#/components/schemas/Href"
        openbareruimtes:
          title: "ligtAan"
          type: "object"
          description: ""
          properties:
            href:
              $ref: "#/components/schemas/Href"
    Woonplaats_links:
      type: "object"
      properties:
        self:
          $ref: "#/components/schemas/Link"
    OpenbareRuimte_links:
      type: "object"
      properties:
        self:
          $ref: "#/components/schemas/Link"
    Nummeraanduiding_embedded:
      type: "object"
      properties:
        woonplaatsen:
          $ref: "#/components/schemas/Woonplaats"
        openbareruimtes:
          $ref: "#/components/schemas/OpenbareRuimte"
    Href:
      type: "string"
      format: "uri"
    Link:
      type: "object"
      properties:
        href:
          $ref: "#/components/schemas/Href"
    Foutbericht:
      type: "object"
      description: "Terugmelding bij een fout"
      properties:
        type:
          type: "string"
          format: "uri"
          description: "Link naar meer informatie over deze fout"
          example: "https://www.gemmaonline.nl/standaarden/api/ValidatieFout"
        title:
          type: "string"
          description: "Beschrijving van de fout"
          example: "Hier staat wat er is misgegaan..."
        status:
          type: "integer"
          description: "Http status code"
          example: 400
        detail:
          type: "string"
          description: "Details over de fout"
          example: "Meer details over de fout staan hier..."
        instance:
          type: "string"
          format: "uri"
          description: "Uri van de aanroep die de fout heeft veroorzaakt"
          example: "https://datapunt.voorbeeldgemeente.nl/service/api/v1/resourcenaam?parameter=waarde"
        invalid-params:
          type: "array"
          items:
            $ref: "#/components/schemas/ParamFoutDetails"
          description: "Foutmelding per fout in een parameter. Alle gevonden fouten\
            \ worden één keer teruggemeld."
    ParamFoutDetails:
      type: "object"
      description: "Details over fouten in opgegeven parameters"
      properties:
        type:
          type: "string"
          format: "uri"
        name:
          type: "string"
          description: "Naam van de parameter"
        reason:
          type: "string"
          description: "Beschrijving van de fout op de parameterwaarde"
  headers:
    api_version:
      schema:
        type: "integer"
        description: "Geeft een specifieke API-versie aan in de context van een specifieke\
          \ aanroep."
        example: "1.0.1"
    warning:
      schema:
        type: "string"
        description: "zie RFC 7234. In het geval een major versie wordt uitgefaseerd,\
          \ gebruiken we warn-code 299 ('Miscellaneous Persistent Warning') en het\
          \ API end-point (inclusief versienummer) als de warn-agent van de warning,\
          \ gevolgd door de warn-text met de human-readable waarschuwing"
        example: "299 https://service.../api/.../v1 'Deze versie van de API is verouderd\
          \ en zal uit dienst worden genomen op 2018-02-01. Raadpleeg voor meer informatie\
          \ hier de documentatie: https://omgevingswet.../api/.../v1'."
    X_Rate_Limit_Limit:
      schema:
        type: "integer"
    X_Rate_Limit_Remaining:
      schema:
        type: "integer"
    X_Rate_Limit_Reset:
      schema:
        type: "integer"
