= Welkom bij de {apiname}

---

== Zoek en raadpleeg persoonsinformatie

API voor het zoeken en raadplegen van informatie uit de basisregistratie
personen (BRP). De {apiname} heeft drie functies:

1. *Personen*: voor het zoeken en raadplegen van actuele personen,
   partners, ouders en kinderen uit de BRP, inclusief de registratie
   niet-ingezeten (RNI).
2. *Bewoning*: voor het raadplegen van de historische bewoning van een
   adres. Met de API kun je de samenstelling(en) van bewoners van een
   woning raadplegen binnen een periode of op een peildatum.
3. *Verblijfplaatshistorie*: voor het opvragen van de
   verblijfplaats(en) van een persoon in een periode of op een peildatum.

De {apiname} levert naast persoonsgegevens uit de BRP ook:

* link:./concepten/informatieproducten[informatieproducten]:
  - *link:./personen/documentatie/informatieproducten/adressering[Adressering]*:
    *aanschrijfwijze*, *aanhef*, een verwijzing naar een *persoon in de
    lopende tekst* van een brief, en *adresregels* die passen in een
    envelopvenster.
  - *link:./bewoning/documentatie[Bewoning]*: wie er samen
    in een woning woonde gedurende een periode, of op een peildatum.
  - *link:./personen/documentatie/informatieproducten/gezag[Gezag]*:
    gezagsrelaties van alle minderjarigen en gezagshouders, ook als er geen
    aantekening is in het gezagsregister.
  - *link:./personen/documentatie/informatieproducten/leeftijd[Leeftijd]*
    (in jaren).
  - *link:./personen/documentatie/informatieproducten/volledige-naam[Volledige
    naam]*: met adellijke titels en predicaten, zonder gebruik van de naam
    van de partner.
  - *link:./personen/documentatie/informatieproducten/voorletters[Voorletters]*.

== Getting Started

Als developer kun je direct aan de slag. Lees in de
link:./getting-started[Getting Started] hoe je zo snel mogelijk een
eerste succesvolle API call doet.

De {apiname} eerst uitproberen? Gebruik de
link:./how-tos/lokaal-testen[lokaal testen gids] om je eerste API call
te doen!

== Voorwaarden

Aansluiten mag alleen met:

1. een https://publicaties.rvig.nl/zoeken[BRP autorisatiebesluit]. Controleer of jouw organisatie of klant (als je een leverancier bent) een autorisatiebesluit heeft.
2. een aanvullend autorisatiebesluit voor informatieproducten. Voor gemeenten is dit niet nodig. Download hier het https://www.rvig.nl/media/898[autorisatieaanvraagformulier].
3. een ondertekend convenant voor deelname aan het https://www.digitaleoverheid.nl/nieuws/doe-mee-met-het-experiment-informatieproducten-uit-de-brp/[Experiment Dataminimalisatie].
4. een aansluiting op https://www.logius.nl/domeinen/infrastructuur/diginetwerk/aansluiten[DigiNetwerk].
5. een API Gateway.

== Documentatie

De documentatie is alsvolgt opgebouwd:

* How-Tos: praktische gidsen die jou helpen bij het implementeren van de
{apiname} in jouw applicatie.
* Concepten: uitleg van belangrijke onderwerpen die een rol spelen bij
het gebruik van de {apiname}.
* Referenties: de specificaties van de {apiname} functies Personen,
Verblijfplaatshistorie en Bewoning.

== Planning en Roadmap

In Q2 wordt het informatieproduct gezag verder verbeterd. Het percentage
kinderen met de uitspraak ``gezag niet te bepalen'' wordt verder
verlaagd. Dat doen we door gezag te bepalen voor een deel van de
kinderen die in het buitenland zijn geboren, of in het buitenland hebben
gewoond.

De vierde functie van de {apiname} is in ontwikkeling. De
{apiname} Notificaties is dit jaar gepland voor gebruik door
gemeenten.

== Contact

* Storing melden? +
Neem contact op met de *RvIG servicedesk*: op werkdagen telefonisch
bereikbaar tussen 08.30 en 17.00 uur via 088-9001000. Vanuit het
buitenland bel je naar: +31 707511000. Je kunt ook een e-mail sturen
naar info@rvig.nl.
* Bug Melden?
https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/issues/new?assignees=&labels=bug&template=bug_report.md&title=[Maak
een bug issue aan]
* Verbetersuggestie doen voor de {apiname} of de documentatie op
deze portal?
https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/issues/new?assignees=&labels=enhancement&template=enhancement.md&title=[Maak
een verbeter issue aan]
* Heb je een vraag? Neem contact op met:
** Product Owner: Cathy Dingemanse, {po-email}
** Developer en customer zero: Melvin Lee, {cz-email}
** Tester: Frank Samwel, {tester-email}

== Licentie

Copyright © RvIG 2024 Licensed under the
link:{main-branch-url}/LICENCE.md[EUPL]
