= Afleidingsregels Leeftijd

== Waarom leeftijd?
Als je dataminimalisatie toepast is het uitgangspunt dat je niet meer persoonsgegevens verwerkt dan je echt nodig hebt om je doel te bereiken. Heb je alleen leeftijd nodig? Vraag dan niet naar de geboortedatum.
Zo heb je bijvoorbeeld alleen de leeftijd nodig als er een bepaalde leeftijdsgrens is verbonden aan aspecten van jouw dienstverlening. Bijvoorbeeld:

* is iemand oud genoeg om een bedrijf te mogen starten of moeten ouders garant staan? (Kamer van Koophandel)
* is een kind 12 jaar of ouder? Dan moet het kind zelf toestemming geven om zijn/haar/het patiëntendossier in te zien (Bevoegdheidsverklaringsdienst).

== Wat krijg je als je de leeftijd vraagt?
Je krijgt de leeftijd in jaren op de dag van bevragen. Bijvoorbeeld: 34.

== Afleidingsregels leeftijd
Lees in de link:/personen/features/leeftijd[afleidingsregels voor leeftijd] hoe de leeftijd precies wordt afgeleid. Heel soms kan de leeftijd niet worden bepaald omdat de geboortedatum van de gevraagde persoon onbekend of gedeeltelijk onbekend is. Bijvoorbeeld omdat alleen een geboortejaar is geregistreerd. Bij een geboortedatum waarvan alleen de jaar en de maand bekend zijn wordt de leeftijd wel bepaald, tenzij de dag van bevragen in de geboortemaand ligt.
Bij minderjarigen en jonge volwassenen komt het eigenlijk niet voor dat de leeftijd niet kan worden bepaald.
