openapi: 3.1.0
info: 
  title: europees kiesrecht
  version: 1.0.0
components: 
  schemas: 
    GbaEuropeesKiesrecht:
      allOf: 
        - $ref: 'europees-kiesrecht-basis-v1.yaml#/components/schemas/EuropeesKiesrechtBasis'
        - type: object
          properties:
            einddatumUitsluiting:
              $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
