openapi: 3.1.0
info: 
  title: uitsluiting kiesrecht
  version: 1.0.0
components: 
  schemas:
    GbaUitsluitingKiesrecht:
      allOf: 
        - $ref: 'uitsluiting-kiesrecht-basis-v1.yaml#/components/schemas/UitsluitingKiesrechtBasis'
        - type: object
          properties:
            einddatum:
              $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
