openapi: 3.1.0
info: 
  title: uitsluiting kiesrecht (basis)
  version: 1.0.0
components: 
  schemas:
    UitsluitingKiesrechtBasis: 
      type: object
      properties:
        uitgeslotenVanKiesrecht:
          type: boolean
          example: true
