openapi: 3.1.0
info:
  title: adresregel 1
  version: 1.0.0
components:
  schemas:
    Adresregel1:
      type: string
      maxLength: 40
      description: |
        Het eerste deel van een adres is een combinatie van de straat en huisnummer.
      examples:
        - binnenlandsAdres:
          value: Kappeyne v d Cappellostr 26A-3
        - buitenlandsAdres:
          value: 1600 Pennsylvania Avenue NW
