apiVersion: v1
kind: Service
metadata:
  name: personenmock
  labels:
    app: brp-api-personen-mock
spec:
  selector:
    name: personenmock
  type: LoadBalancer
  ports:
    - name: "5010"
      port: 5010
      targetPort: http-mock
