apiVersion: apps/v1
kind: Deployment
metadata:
  name: brpproxy
  labels:
    app: haal-centraal-brp-bevragen-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: brpproxy
  template:
    metadata:
      labels:
        name: brpproxy
    spec:
      containers:
        - name: brpproxy
          image: iswish/haal-centraal-brp-bevragen-proxy:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Release
            - name: ASPNETCORE_URLS
              value: http://+:5000
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: brpproxy-routing-configuration
              mountPath: /app/configuration
            - name: brpproxy-settings
              mountPath: /app/appsettings.json
              subPath: appsettings.json
      volumes:
        - name: brpproxy-routing-configuration
          hostPath:
            path: {{ host-path }}/Haal-Centraal-BRP-bevragen/src/config/BrpProxy/configuration
        - name: brpproxy-settings
          hostPath:
            path: {{ host-path }}/Haal-Centraal-BRP-bevragen/src/config/BrpProxy/appsettings
