openapi: 3.1.0
info:
  title: in onderzoek type definitie
  version: 1.0.0
components:
  schemas:
    InOnderzoek:
      type: object
      required:
        - aanduidingGegevensInOnderzoek
        - datumIngangOnderzoek
      properties:
        aanduidingGegevensInOnderzoek:
          type: string
          pattern: ^[0-9]{6}$
          example: '100000'
        datumIngangOnderzoek:
          $ref: 'datum-v1.yaml#/components/schemas/GbaDatum'
