openapi: 3.1.0
info:
  title: indicatie curateleregister
  version: 1.0.0
components:
  schemas:
    IndicatieCurateleRegister:
      type: boolean
      description: |
        Geeft aan dat de persoon onder curatele is gesteld.
      example: true
