openapi: 3.1.0
info: 
  title: overlijden
  version: 1.0.0
components: 
  schemas:
    GbaOverlijden:
      allOf: 
        - $ref: 'overlijden-basis-v1.yaml#/components/schemas/OverlijdenBasis'
      type: object
      properties:
        datum:
          description: |
            datum waarop de persoon is overleden.
          $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
        inOnderzoek:
          $ref: '../in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
