openapi: 3.1.0
info:
  title: derde type definitie
  version: 2.0.0
paths: {}
components:
  schemas:
    Derde:
      type: object
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          BekendeDerde: '#/components/schemas/BekendeDerde'
          OnbekendeDerde: '#/components/schemas/OnbekendeDerde'

    BekendeDerde:
      allOf:
        - $ref: '#/components/schemas/Derde'
        - type: object
          properties:
            burgerservicenummer:
              $ref: '../brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
            naam:
              $ref: './naam-v1.yaml#/components/schemas/Naam'
            geslacht:
              $ref: '../brp/geslacht/geslachtsaanduiding-v1.yaml#/components/schemas/Geslachtsaanduiding'
          required:
            - naam

    OnbekendeDerde:
      allOf:
        - $ref: '#/components/schemas/Derde'
        - type: object
