openapi: 3.1.0
info:
  title: gezagouder type definitie
  version: 2.0.0
paths: {}
components:
  schemas:
    GezagOuder:
      type: object
      properties:
        burgerservicenummer:
          $ref: '../brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        naam:
          $ref: '#/components/schemas/Naam'
      required:
        - naam
    Naam:
      description: Benodigde properties om een volledige naam te construeren.
      type: object
      properties:
        voornamen:
          type: string
        voorvoegsel:
          type: string
        geslachtsnaam:
          type: string
        titel_predicaat:
          type: string
        geslacht:
          type: string
          enum: [ 'F', 'M' ]
