openapi: 3.1.0
info:
  title: minderjarige type definitie
  version: 2.0.0
paths: {}
components:
  schemas:
    Minderjarige:
      type: object
      properties:
        burgerservicenummer:
          $ref: '../brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        naam:
          $ref: './naam-v1.yaml#/components/schemas/Naam'
        geslacht:
          $ref: '../brp/geslacht/geslachtsaanduiding-v1.yaml#/components/schemas/Geslachtsaanduiding'
        geboorte:
          $ref: '../brp/geboorte/geboorte-basis-v1.yaml#/components/schemas/GeboorteBasis'
      required:
        - burgerservicenummer
        - naam
