openapi: 3.1.0
info:
  title: derde type definitie
  version: 2.0.0
paths: {}
components:
  schemas:
    Naam:
      description: Benodigde properties om een volledige naam te construeren. Het construeren wordt gedaan door een andere service.
      type: object
      properties:
        voornamen:
          $ref: '../brp/naam/voornamen-v1.yaml#/components/schemas/Voornamen'
        adellijkeTitelPredicaat:
          $ref: '../brp/naam/adellijke-titel-predicaat-v1.yaml#/components/schemas/AdellijkeTitelPredicaatType'
        voorvoegsel:
          $ref: '../brp/naam/voorvoegsel-v1.yaml#/components/schemas/Voorvoegsel'
        geslachtsnaam:
          $ref: '../brp/naam/geslachtsnaam-v1.yaml#/components/schemas/Geslachtsnaam'
