version: '3.7'

services:
  seq:
    container_name: seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - brp-api-network

  jaeger:
    container_name: jaeger
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 13133:13133
      - 16686:16686
      - 4317:55680
    networks:
      - brp-api-network

  brpproxy:
    container_name: brpproxy
    image: ghcr.io/brp-api/haal-centraal-brp-bevragen-proxy:latest
    build:
      context: .
      dockerfile: src/BrpProxy/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5000
      # - Routes__0__DownstreamScheme=https
      # - Routes__0__DownstreamHostAndPorts__0__Host=proefomgeving-gba.haalcentraal.nl
      # - Routes__0__DownstreamHostAndPorts__0__Port=443
    ports:
      - "5001:5000"
    networks:
      - brp-api-network
    # volumes:
    #   - ./src/config/BrpProxy/configuration:/app/configuration

  personen-mock:
    container_name: personen-mock
    image: ghcr.io/brp-api/personen-mock:latest
    build:
      context: .
      dockerfile: src/BrpService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010
    ports:
      - "5010:5010"
    networks:
      - brp-api-network

  gezagmock:
    container_name: gezagmock
    image: ghcr.io/brp-api/gezag-mock:latest
    build:
      context: .
      dockerfile: src/GezagMock/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5020
    ports:
      - "5020:5020"
    networks:
      - brp-api-network

networks:
  brp-api-network:
    name: brp-api-network