version: '3.7'

services:
  seq:
    container_name: seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80

  jaeger:
    container_name: jaeger
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 13133:13133
      - 16686:16686
      - 4317:55680

  brpproxy:
    container_name: brpproxy
    image: iswish/haal-centraal-brp-bevragen-proxy:latest
    build:
      context: .
      dockerfile: src/BrpProxy/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5001:5000"

  gbamock:
    container_name: gbamock
    image: iswish/haal-centraal-brp-bevragen-gba-mock:latest
    build:
      context: .
      dockerfile: src/BrpService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010
    ports:
      - "5010:5010"
