version: '3.7'

services:
  seq:
    container_name: seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
  jaeger:
    container_name: jaeger
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 13133:13133
      - 16686:16686
      - 4317:55680

  postgres:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - ./src/config/Database:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@haalcentraal.nl
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5433:80

  brpproxy:
    container_name: brpproxy
    image: ${DOCKER_REGISTRY-}brpproxy
    build:
      context: .
      dockerfile: src/BrpProxy/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      #- ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
      #- "5001:5001"
    volumes:
      #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./src/config/BrpProxy/configuration:/app/configuration
      - ./src/config/BrpProxy/mapping:/app/mapping

  brpservice:
    container_name: gbastub
    image: ${DOCKER_REGISTRY-}brpservice
    build:
      context: .
      dockerfile: src/BrpService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      #- ASPNETCORE_URLS=https://+:5011;http://+:5010
      - ASPNETCORE_URLS=http://+:5010
    ports:
      - "5010:5010"
      #- "5011:5011"
    volumes:
      #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./src/config/BrpService:/app/Data
  haalcentraal_api:
    image: haalcentraal.azurecr.io/gba-api:2.0.0
    environment:
      - Database__ConnectionString=database-connectionstring
      - HaalcentraalApi__MaxSearchResults=10
      - ASPNETCORE_URLS=http://+;
    ports:
      - "8000:80"
