version: '3.7'

services:

  personen-mock:
    container_name: personen-mock
    image: ghcr.io/brp-api/personen-mock:2.2.1
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010
    ports:
      - "5010:5010"
    # volumes:
    #   - ./src/config/BrpService:/app/Data
    networks:
      - brp-api-network

networks:
  brp-api-network:
    name: brp-api-network