version: '3.7'

services:
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one:latest
    ports:
      - 13133:13133
      - 16686:16686
      - 4317:55680
  brpproxy:
    image: ${DOCKER_REGISTRY-}brpproxy
    build:
      context: .
      dockerfile: src/BrpProxy/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      #- ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_URLS=http://+:5000
      # - ClientCertificate__Name=client.localhost-client.p12
      # - ClientCertificate__Password=changeit
    ports:
      - "5000:5000"
      #- "5001:5001"
    volumes:
      #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./src/config/BrpProxy/configuration:/app/configuration
      - ./src/config/BrpProxy/mapping:/app/mapping
      - ./src/config/BrpProxy/appsettings/appsettings.json:/app/appsettings.json
      - ./elastic:/app/elastic
      # - ./src/config/BrpProxy/certificates:/app/certificates

  brpservice:
    image: ${DOCKER_REGISTRY-}brpservice
    build:
      context: .
      dockerfile: src/BrpService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      #- ASPNETCORE_URLS=https://+:5011;http://+:5010
      - ASPNETCORE_URLS=http://+:5010
    ports:
      - "5010:5010"
      #- "5011:5011"
    volumes:
      #- ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      #- ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./src/config/BrpService:/app/Data
