openapi: 3.1.0
info: 
  title: verblijfplaats
  version: 1.0.0
components: 
  schemas:
    GbaVerblijfplaats:
      allOf:
        - $ref: 'verblijfplaats-beperkt-v1.yaml#/components/schemas/GbaVerblijfplaatsBeperkt'
        - type: object
          properties:
            adresseerbaarObjectIdentificatie:
              $ref: '../adres/adresseerbaar-object-identificatie-v1.yaml#/components/schemas/AdresseerbaarObjectIdentificatie'
            nummeraanduidingIdentificatie:
              $ref: '../adres/nummeraanduiding-identificatie-v1.yaml#/components/schemas/NummeraanduidingIdentificatie'
            datumAanvangAdresBuitenland:
              $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
            datumAanvangAdreshouding:
              $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
            datumIngangGeldigheid:
              $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
              deprecated: true
            functieAdres:
              $ref: '../waardetabel-v1.yaml#/components/schemas/Waardetabel'
            naamOpenbareRuimte:
              $ref: '../adres/straatnaam-officieel-v1.yaml#/components/schemas/OfficieleStraatnaam'
