openapi: 3.1.0
info:
  title: gezagouder type definitie
  version: 1.0.0
paths: {}
components:
  schemas:
    GezagOuder:
      type: object
      properties:
        burgerservicenummer:
          $ref: '../../brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        naam:
          $ref: '../naam/volledige-naam-v1.yaml#/components/schemas/NaamVolledigeNaam'
      required: 
        -  burgerservicenummer
