openapi: 3.1.0
info:
  title: gezagsrelatie type definitie
  version: 2.0.0
paths: {}
components:
  schemas:
    AbstractGezagsrelatie:
      type: object
      required:
        - type
        - minderjarige
      properties:
        type:
          type: string
        minderjarige:
          $ref: 'minderjarige-v1.yaml#/components/schemas/Minderjarige'
        inOnderzoek:
          type: boolean
          description: Geeft aan dat de gezagsrelatie in onderzoek is.
      discriminator:
        propertyName: type
        mapping:
          TweehoofdigOuderlijkGezag: '#/components/schemas/TweehoofdigOuderlijkGezag'
          EenhoofdigOuderlijkGezag: '#/components/schemas/EenhoofdigOuderlijkGezag'
          GezamenlijkGezag: '#/components/schemas/GezamenlijkGezag'
          Voogdij: '#/components/schemas/Voogdij'
          TijdelijkGeenGezag: '#/components/schemas/TijdelijkGeenGezag'
          GezagNietTeBepalen: '#/components/schemas/GezagNietTeBepalen'

    TweehoofdigOuderlijkGezag:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            ouders:
              type: array
              items:
                $ref: 'gezagouder-v1.yaml#/components/schemas/GezagOuder'
              minItems: 2
              maxItems: 2

    EenhoofdigOuderlijkGezag:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            ouder:
              $ref: 'gezagouder-v1.yaml#/components/schemas/GezagOuder'

    GezamenlijkGezag:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            ouder:
              $ref: 'gezagouder-v1.yaml#/components/schemas/GezagOuder'
            derde:
              $ref: 'derde-v1.yaml#/components/schemas/Derde'

    Voogdij:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            derden:
              type: array
              items:
                $ref: 'derde-v1.yaml#/components/schemas/BekendeDerde'
              minItems: 0
              maxItems: 2

    TijdelijkGeenGezag:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            toelichting:
              $ref: '../../gezag/toelichting-v1.yaml#/components/schemas/Toelichting'

    GezagNietTeBepalen:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            toelichting:
              $ref: '../../gezag/toelichting-v1.yaml#/components/schemas/Toelichting'
