openapi: 3.1.0
info:
  title: minderjarige type definitie
  version: 2.0.0
paths: {}
components:
  schemas:
    Minderjarige:
      type: object
      properties:
        burgerservicenummer:
          $ref: '../../brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        naam:
          $ref: '../naam/volledige-naam-v1.yaml#/components/schemas/NaamVolledigeNaam'
        leeftijd:
          $ref: '../geboorte/leeftijd-v1.yaml#/components/schemas/Leeftijd'
      required: 
        - burgerservicenummer
