openapi: 3.0.0
servers:
  - description: "SwaggerHub API Auto Mocking"
    url: https://virtserver.swaggerhub.com/VNGRealisatie/api/landelijke_tabellen/
  - description: "Referentie-implementatie"
    url: https://www.voorbeeldgemeente.nl/api/landelijke_tabellen/
info:
  title: Landelijke tabellen
  description: "Koppelvlak voor het ontsluiten van landelijke tabellen die nu als pdf op de website van BZK worden gepubliceerd."
  version: "1.0.0"
  contact:
    url: https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
paths:
  /tabellen/gemeenten:
    get:
      operationId: getGemeenten
      description: "Het ophalen van de gegevens van de landelijke gemeententabel (Tabel 33) Bij het zoeken op de omschrijving (gemeentenaam) mag er gebruik wrden gemaakt van [wildcards](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/wildcard.feature) ). Zoeken is **case-insensitive**."
      parameters: 
        - in: query
          name: page
          description: "Een pagina binnen de gepagineerde resultatenset."
          required: false
          schema:
            type: integer
            minimum: 1
        - in: query
          name: code
          description: "De code, behorende bij de gemeentenaam opgenomen in de Gemeentetabel van de GBA."
          required: false
          schema:
            type: string
            maxLength: 4
            example: 0737
        - in: query
          name: datumeinde
          description: "Einddatum van de geldigheid van de gegevens."
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: datumingang
          description: "Begindatum van de geldigheid van de gegevens"
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: nieuwecode
          description: "Code van de nieuwegevormde gemeente waarin deze gemeente is overgegaan."
          required: false
          schema:
            type: string
            maxLength: 4
        - in: query
          name: omschrijving
          description: ""
          required: false
          schema:
            type: string
            maxLength: 80
            example: Tytsjerksteradiel
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml/components/headers/warning"
            X-Pagination-Page:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml/components/headers/X_Pagination_Page"
            X-Pagination-Limit:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml/components/headers/X_Pagination_Limit"
            X-Rate-Limit-Limit:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml/components/headers/X_Rate_Limit_Limit"
            X-Rate-Limit-Remaining:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml/components/headers/X_Rate_Limit_Remaining"
            X-Rate-Limit-Reset:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml/components/headers/X_Rate_Limit_Reset"
          content:
            application/hal+json:
              schema:
                 $ref: '#/components/schemas/GemeenteHalCollectie'
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/403"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/406"
        '409':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/409"
        '410':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/410"
        '415':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/415"
        '429':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/429"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/500"
        '501':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/501"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/503"
        'default':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/default"
      tags: 
      - Tabellen
  /tabellen/gemeenten/{code}:
    get:
      operationId: getGemeente
      description: "Het ophalen van de gegevens van de landelijke gemeententabel (Tabel 33)"
      parameters:
        - in: path
          name: code
          description: "De code, behorende bij de gemeentenaam opgenomen in de Gemeentetabel van de GBA."
          required: true
          schema:
            type: string
            maxLength: 4
            minLength: 4
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml/components/headers/warning"
            X-Rate-Limit-Limit:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml/components/headers/X_Rate_Limit_Limit"
            X-Rate-Limit-Remaining:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml/components/headers/X_Rate_Limit_Remaining"
            X-Rate-Limit-Reset:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml/components/headers/X_Rate_Limit_Reset"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/GemeenteHal'
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/403"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/406"
        '409':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/409"
        '410':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/410"
        '415':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/415"
        '429':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/429"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/500"
        '501':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/501"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/503"
        'default':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/common.yaml#/components/responses/default"
      tags: 
      - Tabellen
components:
  schemas:
    Gemeente:
      type: "object"
      description: "Een opsomming van alle huidige en voormalige landen met hun codes,\
        \ namen en geldigheidstermijnen conform de landelijke tabel Gemeenten Tabel\
        \ 33"
      properties:
        code:
          type: "string"
          title: "code"
          description: "De code, behorende bij de gemeentenaam opgenomen in de Gemeentetabel\
            \ van de GBA."
          maxLength: 4
          example: "0737"
        datumEinde:
          type: "string"
          title: "datumEinde"
          description: "Einddatum van de geldigheid van de gegevens."
          format: "date"
        datumIngang:
          type: "string"
          title: "datumIngang"
          description: "Begindatum van de geldigheid van de gegevens"
          format: "date"
        nieuweCode:
          type: "string"
          title: "nieuweCode"
          description: "Code van de nieuwegevormde gemeente waarin deze gemeente is\
            \ overgegaan."
          maxLength: 4
        omschrijving:
          type: "string"
          title: "omschrijving"
          description: ""
          maxLength: 80
          example: "Tytsjerksteradiel"
    GemeenteHal:
      allOf:
        - $ref: "#/components/schemas/Gemeente"
        - type: "object"
          properties:
            _links:
              $ref: "#/components/schemas/Gemeente_links"
    GemeenteHalCollectie:
      type: "object"
      properties:
        _links:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/HalPaginationLinks"
        _embedded:
          type: object
          properties:
            gemeenten:
              type: array
              items:
                $ref: '#/components/schemas/GemeenteHal'
    Gemeente_links:
      type: "object"
      properties:
        self:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/HalLink"
        gemeenten:
          title: "overgegaanIn"
          type: "object"
          description: "De gemeente waarin deze gemeente is overgegaan bij een gemeentelijke herindeling. "
          properties:
            href:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/Href"
