openapi: 3.1.0
info:
  title: geslachtsnaam type definitie
  version: 1.0.0
components:
  schemas:
    Geslachtsnaam:
      type: string
      pattern: ^[a-zA-Z0-9À-ž \.\-\']{1,200}$
      description: |
        De achternaam van een persoon.
      example: Vries
