openapi: 3.1.0
info: 
  title: gemeente van inschrijving query parameter type definitie
  version: 1.0.0
components: 
  schemas:
    GemeenteVanInschrijving:
      description: |
        Een code die aangeeft in welke gemeente de persoon woont, of de laatste gemeente waar de persoon heeft gewoond, of de gemeente waar de persoon voor het eerst is ingeschreven.
      type: string
      pattern: ^[0-9]{4}$
