openapi: 3.1.0
info: 
  title: geslacht query parameter type definitie
  version: 1.0.0
components: 
  schemas:
    GeslachtFilter:
      description: |
        Geeft aan dat de persoon een man of een vrouw is, of dat het geslacht (nog) onbekend is.
      type: string
      pattern: ^([Mm]|[Vv]|[Oo])$
      example: "V"
