openapi: 3.1.0
info:
  title: nummeraanduiding identificatie query parameter type definitie
  version: 1.0.0
components:
  schemas:
    NummeraanduidingIdentificatieFilter:
      type: string
      pattern: ^(?!0{16})[0-9]{16}$
      description: |
        De unieke identificatie van een nummeraanduiding (en het bijbehorende adres) in de BAG.
      example: '0518200000366054'
