openapi: 3.1.0
info: 
  title: voornamen verplicht query parameter type definitie
  version: 1.0.0
components: 
  schemas:
    VoornamenVerplichtFilter:
      description: |
        De verzameling namen die, gescheiden door spaties, aan de geslachtsnaam voorafgaat. **Gebruik van de wildcard is toegestaan bij invoer van ten minste 3 letters.** **Zoeken met tekstvelden is case-insensitive.**
      type: string
      pattern: ^[a-zA-Z0-9À-ž \.\-\']{1,200}$|^[a-zA-Z0-9À-ž \.\-\']{3,199}\*{1}$
      example: "Dirk"
