= Afleidingsregels Gezag

== Wat is gezag?
Iedereen in Nederland die jonger is dan 18 jaar staat onder gezag. Dit betekent dat zij sommige beslissingen niet zelfstandig mogen nemen. Iemand die gezag heeft over een minderjarige is verantwoordelijk voor de verzorging en opvoeding van de minderjarige en beheert het geld en de spullen van de minderjarige.
De gezaghouder is ook de wettelijk vertegenwoordiger van de minderjarige. Minderjarigen mogen vaak niet zelf officiële handelingen doen. De wettelijk vertegenwoordiger doet dit dan voor de minderjarige, bijvoorbeeld door een handtekening te zetten. De wettelijk vertegenwoordiger is ook vaak wettelijk aansprakelijk voor wat de minderjarige doet.
Gezag gaat veel verder dan alleen een recht op omgang. De ouder met gezag mag namelijk belangrijke beslissingen nemen over het leven van het kind, zoals een schoolkeuze, medische beslissingen, een verhuizing, een vakantie naar het buitenland of het aanvragen van een reisdocument. Een ouder die alleen het gezag uitoefent, heeft bij het nemen van deze beslissingen geen toestemming nodig van de andere (juridische) ouder zonder gezag.

Iedereen die 18 jaar of ouder is en niet onder curatele staat of een geestelijke stoornis heeft kan gezag hebben over een minderjarige. Meestal hebben de ouders het gezag. Het gezag stopt automatisch als het kind 18 jaar wordt. Een minderjarige kan niet meer dan 2 ouders hebben. Over een minderjarige kan het gezag niet door meer dan 2 personen worden uitgeoefend.

=== Verschillende typen gezag
Er zijn verschillende soorten gezag:
* Ouderlijk gezag door één ouder (éénhoofdig ouderlijk gezag) of twee ouders (gezamenlijk ouderlijk gezag)
* Gezamenlijk gezag van een ouder en een niet-ouder
* Voogdij

=== Wat bedoelen we met ouders?
Met *ouders* bedoelen we de juridische ouders volgens de wet. De juridische ouder is de ouder die op de geboorteakte staat. Hieronder staat hoe iemand juridisch ouder kan worden:

De *moeder* van een kind is volgens de wet:
* de vrouw uit wie het kind geboren is
* de vrouw die het kind heeft geadopteerd
* de vrouw die met de moeder is getrouwd of een geregistreerd partnerschap heeft als het kind tijdens het huwelijk of geregistreerd partnerschap geboren wordt. Om zwanger te worden is gebruik gemaakt van een onbekende zaaddonor, zoals beschreven in de Wet donorgegevens kunstmatige bevruchting
* de vrouw die het kind heeft erkend
* de vrouw van wie het ouderschap gerechtelijk is vastgesteld

De *vader* van een kind is volgens de wet:
* de man die met de moeder is gehuwd of een geregistreerd partnerschap heeft, als het kind tijdens het huwelijk of geregistreerd partnerschap geboren wordt
* de man die het kind heeft erkend
* de man die het kind heeft geadopteerd
* de man van wie het ouderschap gerechtelijk is vastgesteld

Met *niet-ouder* bedoelen we:
* de partner van één van de ouders
* een derde met een nauwe persoonlijke relatie met tot de minderjarige (bijvoorbeeld een tante, oom of iemand anders)
* een voogd

=== Wat is voogdij?
Voogdij is het gezag van niet-ouders. Iedereen die 18 jaar of ouder is, niet onder curatele staat en geen geestelijke stoornis heeft, kan voogd worden. Ook een jeugdzorgorganisatie (bijvoorbeeld Bureau Jeugdzorg) kan als voogd worden benoemd.

Wanneer krijgt een minderjarige een voogd?
* wanneer de ouders zijn overleden
* wanneer de ouders geen gezag (meer) hebben

Een minderjarige kan automatisch of via de rechter een voogd krijgen:
* een gezaghouder met gezamenlijk gezag wordt automatisch voogd als de andere gezaghebbende ouder overlijdt of onbevoegd raakt tot de uitoefening van gezag. Bijvoorbeeld omdat die ouder onder curatele staat
* vaak benoemt de rechter een voogd in een gerechtelijke uitspraak. Ook ouders kunnen in hun testament of door een aantekening in het gezagsregister één of twee personen als voogd aanwijzen. De voogdij begint pas als de ouders overleden zijn, het kind nog geen 18 jaar is en de voogd bij de griffie van de rechtbank verklaard heeft dat de voogdij wordt aanvaard. Als de gevraagde persoon toch geen voogd wil zijn, bepaalt de rechter wie de voogd wordt

== Leeswijzer afleidingsregels

Gezag wordt bepaald door afleidingsregels in onderstaande volgorde toe te passen:

. Wanneer minderjarige de vaste verblijfplaats in het buitenland heeft, is het gezag niet te bepalen. Lees de afleidingsregels voor xref:personen:features/gezag/niet-ingezetene.adoc[gezag bepalen voor minderjarigen die in het buitenland verblijven]
. Er wordt vastgesteld dat geen gezag is. Lees de afleidingsregels voor xref:personen:features/gezag/geen-gezag.adoc[geen gezag functionaliteit]
. Er is een gerechtelijke uitspraak over gezag, die kan worden herzien door adoptie, een reparatiehuwelijk of ontkenning. Lees de afleidingsregels voor xref:personen:features/gezag/gerechtelijke-uitspraak.adoc[gerechtelijke uitspraak]
. Gezag wordt bepaald van een minderjarige:
.. met twee ouders met een relatie met elkaar. Lees de afleidingsregels voor een xref:personen:features/gezag/twee-ouders-met-relatie.adoc[minderjarige met twee ouders met relatie]
.. met twee ouders zonder een relatie met elkaar. Lees de afleidingsregels voor een xref:personen:features/gezag/twee-ouders-geen-relatie.adoc[minderjarige met twee ouders zonder relatie]
.. met één ouder. Lees de afleidingsregels voor een xref:personen:features/gezag/een-ouder.adoc[minderjarige met één ouder]
.. zonder ouders. Lees de afleidingsregels voor een xref:personen:features/gezag/geen-ouder.adoc[minderjarige zonder ouder]
. Minderjarige heeft de de gewone verblijfplaats in het buitenland gehad. Lees de afleidingsregels voor xref:personen:features/gezag/immigrant.adoc[minderjarige die in het buitenland heeft verbleven]
. Gezaghouder(s) zijn niet bevoegd of overleden. Lees de afleidingsregels voor xref:personen:features/gezag/bevoegdheid-tot-gezag.adoc[bevoegdheid tot gezag].
