openapi: 3.1.0
info:
  title: nummeraanduiding identificatie
  version: 1.0.0
components:
  schemas:
    NummeraanduidingIdentificatie:
      description: |
        Unieke identificatie van een nummeraanduiding (en het bijbehorende adres) in de BAG.
      type: string
      pattern: ^[0-9]{16}$
      example: "0518200000366054"
