openapi: 3.0.0
servers:
  - description: "SwaggerHub API Auto Mocking"
    url: https://virtserver.swaggerhub.com/VNGRealisatie/api/reisdocumenten
info:
  title: Reisdocumenten
  description: "API voor het ontsluiten van gegevens van reisdocumenten uit de GBA en RNI."
  version: "1.0.0"
  contact:
    url: https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
paths:
  /reisdocumenten/{reisdocumentnummer}:
    get:
      operationId: reisdocumentenReisdocumentnummer
      description: "Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer."
      parameters:
        - in: path
          name: reisdocumentnummer
          description: "Het nummer van het verstrekte Nederlandse reisdocument."
          required: true
          schema:
            type: string
            maxLength: 9
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/headers/warning"
            X-Rate-Limit-Limit:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/headers/X_Rate_Limit_Limit"
            X-Rate-Limit-Remaining:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/headers/X_Rate_Limit_Remaining"
            X-Rate-Limit-Reset:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/headers/X_Rate_Limit_Reset"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ReisdocumentHal'
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/403"
        '404':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/404"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/406"
        '409':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/409"
        '410':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/410"
        '415':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/415"
        '429':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/429"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/500"
        '501':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/501"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/503"
        'default':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/responses/default"
      tags:
      - reisdocumenten
components:
  schemas:
    Reisdocument:
      type: "object"
      description: "Een document dat vereist is voor reizen naar het buitenland \n\
        * **datumEindeGeldigheid** : De datum waarop een Nederlands reisdocument,\
        \ dat aan de ingeschrevene is verstrekt of waarin de ingeschrevene is bijgeschreven,\
        \ zijn geldigheid verliest. \n* **datumInhoudingOfVermissing**: De datum waarop\
        \ een Nederlands reisdocument is vermist, ingehouden, ingeleverd, dan wel\
        \ van rechtswege is vervallen. \n* **datumUitgifte** : De datum waarop het\
        \ Nederlands reisdocument is uitgegeven of de datum van bijschrijving van\
        \ de ingeschrevene in een Nederlands reisdocument. \n* **autoriteitAfgifte**\
        \ : Tabel Autoriteit van afgifte Nederlands reisdocument, die aangeeft welke\
        \ autoriteit het Nederlands reisdocument heeft verstrekt of de bijschrijving\
        \ heeft verricht. \n* **aanduidingInhoudingOfVermissing** : Een aanduiding\
        \ dat een Nederlands reisdocument is vermist, ingehouden, ingeleverd, dan\
        \ wel van rechtswege is vervallen. \n* **soortReisdocument** : Tabel Nederlands\
        \ reisdocument, die aangeeft welk Nederlandse reisdocument is verstrekt of\
        \ in welk reisdocument de ingeschrevene is bijgeschreven."
      properties:
        aanduidingInhoudingOfVermissing:
          $ref: "#/components/schemas/AanduidingInhoudingVermissingReisdocument_enum"
        reisdocumentnummer:
          type: "string"
          title: "Reisdocumentnummer"
          description: "Het nummer van het verstrekte Nederlandse reisdocument."
          maxLength: 9
          example: "546376728"
        autoriteitAfgifte:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/Waardetabel"
        datumEindeGeldigheid:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/Datum_onvolledig"
        datumInhoudingOfVermissing:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/Datum_onvolledig"
        datumUitgifte:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/Datum_onvolledig"
        soortReisdocument:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/Waardetabel"
        geheimhoudingPersoonsgegevens:
          type: "boolean"
          title: "Indicatie geheim"
          description: "Een aanduiding die aangeeft dat gegevens wel of niet verstrekt\
            \ mogen worden. Indien true: op verzoek van deze persoon is het verstrekken\
            \ van gegevens over deze persoon aan bepaalde derden niet toegestaan."
        inOnderzoek:
          $ref: "#/components/schemas/ReisdocumentInOnderzoek"
    ReisdocumentHal:
      allOf:
        - $ref: '#/components/schemas/Reisdocument'
        - properties:
            _links:
              $ref: "#/components/schemas/Reisdocument_links"
    Reisdocument_links:
      type: "object"
      properties:
        self:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/HalLink"
        ingeschrevenPersoon:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/HalLink"
    AanduidingInhoudingVermissingReisdocument_enum:
      type: "string"
      description: "De mogelijke waarden van de aanduiding van inhouding of vermissing\
        \ van een Nederlands reisdocument. Zie logisch ontwerp BRP bij de stamtabellen:\n\
        * `ingehouden_of_ingeleverd` - I\n* `vermist` - V\n* `rechtswege` - R\n* `niet_in_bezit_van`\
        \ - N"
      enum:
      - "ingehouden_of_ingeleverd"
      - "vermist"
      - "rechtswege"
      - "niet_in_bezit_van"
    ReisdocumentInOnderzoek:
      type: "object"
      description: "Een groep van booleans om aan te geven welke gegevens van het\
        \ reisdocument in onderzoek zijn. Als de hele categorie in onderzoek is worden\
        \ alle rubrieken binnen die categorie op _true_ gezet. Zie de [functionele\
        \ specificaties](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/in_onderzoek.feature)\
        \ ."
      properties:
        aanduidingInhoudingOfVermissing:
          type: "boolean"
          title: "aanduidingInhoudingOfVermissing"
          description: "Indicator die aangeeft of het corresponderende gegeven voor\
            \ deze persoon in onderzoek is."
        autoriteitAfgifte:
          type: "boolean"
          title: "autoriteitAfgifte"
          description: "Indicator die aangeeft of het corresponderende gegeven voor\
            \ deze persoon in onderzoek is."
        datumEindeGeldigheid:
          type: "boolean"
          title: "datumEindeGeldigheid"
          description: "Indicator die aangeeft of het corresponderende gegeven voor\
            \ deze persoon in onderzoek is."
        datumInhoudingOfVermissing:
          type: "boolean"
          title: "datumInhoudingOfVermissing"
          description: "Indicator die aangeeft of het corresponderende gegeven voor\
            \ deze persoon in onderzoek is."
        datumUitgifte:
          type: "boolean"
          title: "datumUitgifte"
          description: "Indicator die aangeeft of het corresponderende gegeven voor\
            \ deze persoon in onderzoek is."
        reisdocumentnummer:
          type: "boolean"
          title: "reisdocumentnummer"
          description: "Indicator die aangeeft of het corresponderende gegeven voor\
            \ deze persoon in onderzoek is."
        soortReisdocument:
          type: "boolean"
          title: "soortReisdocument"
          description: "Indicator die aangeeft of het corresponderende gegeven voor\
            \ deze persoon in onderzoek is."
        datumIngangOnderzoek:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/master/api-specificatie/common.yaml#/components/schemas/Datum_onvolledig"
