openapi: 3.1.0
info:
  title: naam persoon beperkt
  version: 2.0.0
  contact: {}
components:
  schemas:
    NaamPersoonBeperkt:
      description: |
        Gegevens over de naam van de persoon.
      allOf:
        - $ref: 'naam-basis-v1.yaml#/components/schemas/NaamBasis'
        - properties:
            inOnderzoek:
              $ref: '#/components/schemas/NaamPersoonInOnderzoekBeperkt'

    NaamPersoonInOnderzoekBeperkt:
      allOf:
        - $ref: 'naam-gerelateerde-v1.yaml#/components/schemas/NaamInOnderzoek'
        - type: object
          properties:
            volledigeNaam:
              type: boolean
