openapi: 3.1.0
info:
  title: naam basis
  version: 2.0.0
  contact: {}
components:
  schemas:
    NaamBasis:
      type: object
      properties:
        voornamen:
          $ref: '../../brp/naam/voornamen-v1.yaml#/components/schemas/Voornamen'
        adellijkeTitelPredicaat:
          $ref: '../../brp/naam/adellijke-titel-predicaat-v1.yaml#/components/schemas/AdellijkeTitelPredicaatType'
        voorvoegsel:
          $ref: '../../brp/naam/voorvoegsel-v1.yaml#/components/schemas/Voorvoegsel'
        geslachtsnaam:
          $ref: '../../brp/naam/geslachtsnaam-v1.yaml#/components/schemas/Geslachtsnaam'
        voorletters:
          $ref: 'voorletters-v1.yaml#/components/schemas/Voorletters'
        volledigeNaam:
          $ref: 'volledige-naam-v1.yaml#/components/schemas/VolledigeNaam'
