openapi: 3.1.0
info:
  title: voorletters
  version: 2.0.0
  contact: {}
components:
  schemas:
    Voorletters:
      type: string
      pattern: ^[a-zA-Z0-9À-ž \.]{1,40}$
      description: |
        De voorletters van de persoon, afgeleid van de voornamen.
      example: "P.J."
