openapi: 3.1.0
info:
  title: 400 Bad Request Response type definitie
  description: |
    Definitie voor Bad Request Response, voor het leveren van input validatie foutmeldingen 
  version: 1.0.0
  contact: {}
components:
  responses:
    '400':
      description: Bad Request
      content:
        application/problem+json:
          schema: 
            $ref: 'bad-request-fout-bericht-v1.yaml#/components/schemas/BadRequestFoutbericht'
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1
            title: Ten minste één parameter moet worden opgegeven.
            status: 400
            detail: The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: paramsRequired
            invalidParams:
              - type: https://www.vng.nl/realisatie/api/validaties/integer
                name: huisnummer
                code: integer
                reason: Waarde is geen geldig getal.
