openapi: 3.1.0
info:
  title: 401 Unauthorized Response type definitie
  description: |
    Definitie voor Unauthorized Response, voor het leveren van 'niet geauthenticeerd' foutmelding 
  version: 1.0.0
  contact: {}
components:
  responses:
    '401':
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: 'fout-bericht-v1.yaml#/components/schemas/Foutbericht'
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2
            title: Niet correct geauthenticeerd.
            status: 401
            detail: The request requires user authentication. The response MUST include a WWW-Authenticate header field (section 14.47) containing a challenge applicable to the requested resource.
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: authentication
