openapi: 3.1.0
info:
  title: 404 Not Found Response type definitie
  description: |
    Definitie voor Not Found Response, voor het leveren van 'resource bestaat niet' foutmelding 
  version: 1.0.0
  contact: {}
components:
  responses:
    '404':
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: 'fout-bericht-v1.yaml#/components/schemas/Foutbericht'
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5
            title: Opgevraagde resource bestaat niet.
            status: 404
            detail: The server has not found anything matching the Request-URI.
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: notFound
