openapi: 3.1.0
info:
  title: 415 Unsupported Media Type Response
  description: |
    Definitie voor Unsupported Media Type Response, voor het leveren van de 'niet ondersteund request body type' foutmelding 
  version: 1.0.0
  contact: {}
components:
  responses:
    '415':
      description: Unsupported Media Type
      content:
        application/problem+json:
          schema:
            $ref: 'fout-bericht-v1.yaml#/components/schemas/Foutbericht'
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.16
            title: Unsupported Media Type
            status: 415
            detail: The server is refusing the request because the entity of the request is in a format not supported by the requested resource for the requested method.
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: unsupported