openapi: 3.1.0
info:
  title: 500 Not Implemented Response type definitie
  description: |
    Definitie voor Not Implemented Response 
  version: 1.0.0
  contact: {}
components:
  responses:
    '501':
      description: Not Implemented
      content:
        application/problem+json:
          schema:
            $ref: 'fout-bericht-v1.yaml#/components/schemas/Foutbericht'
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5.2
            title: Not Implemented
            status: 501
            detail: The server does not support the functionality required to fulfill the request.
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: notImplemented
