/* 
 * Bevragingen ingeschreven personen
 *
 * API voor het ontsluiten van gegevens van ingeschreven personen en aanverwante gegevens uit de GBA en RNI. Met deze API worden de actuele gegevens van ingeschreven personen, hun kinderen, partners en ouders ontsloten. <br> Heeft een persoon bijvoorbeeld geen geldige nationaliteit, dan wordt nationaliteit niet geretourneerd. <br> Heeft een persoon een beëindigd partnerschap of huwelijk, dan wordt de partner niet geretourneerd. <br> <br> Zie de [Functionele documentatie](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/tree/master/features) voor nadere toelichting. <br> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Dit object bevat de basis Verblijfsplaats kenmerken die gedeeld worden door Bewoning en Verblijfplaats 
    /// </summary>
    [DataContract]
    public partial class BinnenlandsAdres :  IEquatable<BinnenlandsAdres>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BinnenlandsAdres" /> class.
        /// </summary>
        /// <param name="functieAdres">functieAdres.</param>
        /// <param name="huisletter">Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende toevoeging aan een huisnummer in de vorm van een alfanumeriek teken. a - z , A – Z.</param>
        /// <param name="huisnummer">Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende nummering. Alle natuurlijke getallen tussen 1 en 99999..</param>
        /// <param name="huisnummertoevoeging">Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende nadere toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter. a - z , A - Z , 0 – 9.</param>
        /// <param name="aanduidingBijHuisnummer">aanduidingBijHuisnummer.</param>
        /// <param name="identificatiecodeNummeraanduiding">De unieke aanduiding van een NUMMERAANDUIDING. Combinatie van de viercijferige &#39;gemeentecode&#39; de tweecijferige &#39;objecttypecode&#39; en een voor het betreffende objecttype binnen een gemeente uniek tiencijferig &#39;objectvolgnummer&#39;. De objecttypecode kent in de BAG de volgende waarde:20 nummeraanduiding. Combinatie van de viercijferige &#39;gemeentecode&#39; (volgens GBA tabel 33, Gemeententabel), de tweecijferige &#39;objecttypecode&#39; en een voor het betreffende objecttype binnen een gemeente uniek tiencijferig &#39;objectvolgnummer&#39;. De objecttypecode kent in de BAG de volgende waarde:20 nummeraanduiding..</param>
        /// <param name="naamOpenbareRuimte">Een door het bevoegde gemeentelijke orgaan aan een OPENBARE RUIMTE toegekende benaming Tekens gecodeerd volgens de UTF-8 standaard.</param>
        /// <param name="postcode">De door PostNL vastgestelde code behorende bij een bepaalde combinatie van een naam van een woonplaats, naam van een openbare ruimte en een huisnummer.</param>
        /// <param name="woonplaatsnaam">De door het bevoegde gemeentelijke orgaan aan een WOONPLAATS toegekende benaming. Tekens gecodeerd volgens de UTF-8 standaard..</param>
        public BinnenlandsAdres(SoortAdresEnum functieAdres = default(SoortAdresEnum), string huisletter = default(string), int huisnummer = default(int), string huisnummertoevoeging = default(string), AanduidingBijHuisnummerEnum aanduidingBijHuisnummer = default(AanduidingBijHuisnummerEnum), string identificatiecodeNummeraanduiding = default(string), string naamOpenbareRuimte = default(string), string postcode = default(string), string woonplaatsnaam = default(string))
        {
            this.FunctieAdres = functieAdres;
            this.Huisletter = huisletter;
            this.Huisnummer = huisnummer;
            this.Huisnummertoevoeging = huisnummertoevoeging;
            this.AanduidingBijHuisnummer = aanduidingBijHuisnummer;
            this.IdentificatiecodeNummeraanduiding = identificatiecodeNummeraanduiding;
            this.NaamOpenbareRuimte = naamOpenbareRuimte;
            this.Postcode = postcode;
            this.Woonplaatsnaam = woonplaatsnaam;
        }
        
        /// <summary>
        /// Gets or Sets FunctieAdres
        /// </summary>
        [DataMember(Name="functieAdres", EmitDefaultValue=false)]
        public SoortAdresEnum FunctieAdres { get; set; }

        /// <summary>
        /// Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende toevoeging aan een huisnummer in de vorm van een alfanumeriek teken. a - z , A – Z
        /// </summary>
        /// <value>Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende toevoeging aan een huisnummer in de vorm van een alfanumeriek teken. a - z , A – Z</value>
        [DataMember(Name="huisletter", EmitDefaultValue=false)]
        public string Huisletter { get; set; }

        /// <summary>
        /// Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende nummering. Alle natuurlijke getallen tussen 1 en 99999.
        /// </summary>
        /// <value>Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende nummering. Alle natuurlijke getallen tussen 1 en 99999.</value>
        [DataMember(Name="huisnummer", EmitDefaultValue=false)]
        public int Huisnummer { get; set; }

        /// <summary>
        /// Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende nadere toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter. a - z , A - Z , 0 – 9
        /// </summary>
        /// <value>Een door of namens het bevoegd gemeentelijk orgaan ten aanzien van een adresseerbaar object toegekende nadere toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter. a - z , A - Z , 0 – 9</value>
        [DataMember(Name="huisnummertoevoeging", EmitDefaultValue=false)]
        public string Huisnummertoevoeging { get; set; }

        /// <summary>
        /// Gets or Sets AanduidingBijHuisnummer
        /// </summary>
        [DataMember(Name="aanduidingBijHuisnummer", EmitDefaultValue=false)]
        public AanduidingBijHuisnummerEnum AanduidingBijHuisnummer { get; set; }

        /// <summary>
        /// De unieke aanduiding van een NUMMERAANDUIDING. Combinatie van de viercijferige &#39;gemeentecode&#39; de tweecijferige &#39;objecttypecode&#39; en een voor het betreffende objecttype binnen een gemeente uniek tiencijferig &#39;objectvolgnummer&#39;. De objecttypecode kent in de BAG de volgende waarde:20 nummeraanduiding. Combinatie van de viercijferige &#39;gemeentecode&#39; (volgens GBA tabel 33, Gemeententabel), de tweecijferige &#39;objecttypecode&#39; en een voor het betreffende objecttype binnen een gemeente uniek tiencijferig &#39;objectvolgnummer&#39;. De objecttypecode kent in de BAG de volgende waarde:20 nummeraanduiding.
        /// </summary>
        /// <value>De unieke aanduiding van een NUMMERAANDUIDING. Combinatie van de viercijferige &#39;gemeentecode&#39; de tweecijferige &#39;objecttypecode&#39; en een voor het betreffende objecttype binnen een gemeente uniek tiencijferig &#39;objectvolgnummer&#39;. De objecttypecode kent in de BAG de volgende waarde:20 nummeraanduiding. Combinatie van de viercijferige &#39;gemeentecode&#39; (volgens GBA tabel 33, Gemeententabel), de tweecijferige &#39;objecttypecode&#39; en een voor het betreffende objecttype binnen een gemeente uniek tiencijferig &#39;objectvolgnummer&#39;. De objecttypecode kent in de BAG de volgende waarde:20 nummeraanduiding.</value>
        [DataMember(Name="identificatiecodeNummeraanduiding", EmitDefaultValue=false)]
        public string IdentificatiecodeNummeraanduiding { get; set; }

        /// <summary>
        /// Een door het bevoegde gemeentelijke orgaan aan een OPENBARE RUIMTE toegekende benaming Tekens gecodeerd volgens de UTF-8 standaard
        /// </summary>
        /// <value>Een door het bevoegde gemeentelijke orgaan aan een OPENBARE RUIMTE toegekende benaming Tekens gecodeerd volgens de UTF-8 standaard</value>
        [DataMember(Name="naamOpenbareRuimte", EmitDefaultValue=false)]
        public string NaamOpenbareRuimte { get; set; }

        /// <summary>
        /// De door PostNL vastgestelde code behorende bij een bepaalde combinatie van een naam van een woonplaats, naam van een openbare ruimte en een huisnummer
        /// </summary>
        /// <value>De door PostNL vastgestelde code behorende bij een bepaalde combinatie van een naam van een woonplaats, naam van een openbare ruimte en een huisnummer</value>
        [DataMember(Name="postcode", EmitDefaultValue=false)]
        public string Postcode { get; set; }

        /// <summary>
        /// De door het bevoegde gemeentelijke orgaan aan een WOONPLAATS toegekende benaming. Tekens gecodeerd volgens de UTF-8 standaard.
        /// </summary>
        /// <value>De door het bevoegde gemeentelijke orgaan aan een WOONPLAATS toegekende benaming. Tekens gecodeerd volgens de UTF-8 standaard.</value>
        [DataMember(Name="woonplaatsnaam", EmitDefaultValue=false)]
        public string Woonplaatsnaam { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BinnenlandsAdres {\n");
            sb.Append("  FunctieAdres: ").Append(FunctieAdres).Append("\n");
            sb.Append("  Huisletter: ").Append(Huisletter).Append("\n");
            sb.Append("  Huisnummer: ").Append(Huisnummer).Append("\n");
            sb.Append("  Huisnummertoevoeging: ").Append(Huisnummertoevoeging).Append("\n");
            sb.Append("  AanduidingBijHuisnummer: ").Append(AanduidingBijHuisnummer).Append("\n");
            sb.Append("  IdentificatiecodeNummeraanduiding: ").Append(IdentificatiecodeNummeraanduiding).Append("\n");
            sb.Append("  NaamOpenbareRuimte: ").Append(NaamOpenbareRuimte).Append("\n");
            sb.Append("  Postcode: ").Append(Postcode).Append("\n");
            sb.Append("  Woonplaatsnaam: ").Append(Woonplaatsnaam).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BinnenlandsAdres);
        }

        /// <summary>
        /// Returns true if BinnenlandsAdres instances are equal
        /// </summary>
        /// <param name="input">Instance of BinnenlandsAdres to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BinnenlandsAdres input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FunctieAdres == input.FunctieAdres ||
                    (this.FunctieAdres != null &&
                    this.FunctieAdres.Equals(input.FunctieAdres))
                ) && 
                (
                    this.Huisletter == input.Huisletter ||
                    (this.Huisletter != null &&
                    this.Huisletter.Equals(input.Huisletter))
                ) && 
                (
                    this.Huisnummer == input.Huisnummer ||
                    this.Huisnummer.Equals(input.Huisnummer)
                ) && 
                (
                    this.Huisnummertoevoeging == input.Huisnummertoevoeging ||
                    (this.Huisnummertoevoeging != null &&
                    this.Huisnummertoevoeging.Equals(input.Huisnummertoevoeging))
                ) && 
                (
                    this.AanduidingBijHuisnummer == input.AanduidingBijHuisnummer ||
                    (this.AanduidingBijHuisnummer != null &&
                    this.AanduidingBijHuisnummer.Equals(input.AanduidingBijHuisnummer))
                ) && 
                (
                    this.IdentificatiecodeNummeraanduiding == input.IdentificatiecodeNummeraanduiding ||
                    (this.IdentificatiecodeNummeraanduiding != null &&
                    this.IdentificatiecodeNummeraanduiding.Equals(input.IdentificatiecodeNummeraanduiding))
                ) && 
                (
                    this.NaamOpenbareRuimte == input.NaamOpenbareRuimte ||
                    (this.NaamOpenbareRuimte != null &&
                    this.NaamOpenbareRuimte.Equals(input.NaamOpenbareRuimte))
                ) && 
                (
                    this.Postcode == input.Postcode ||
                    (this.Postcode != null &&
                    this.Postcode.Equals(input.Postcode))
                ) && 
                (
                    this.Woonplaatsnaam == input.Woonplaatsnaam ||
                    (this.Woonplaatsnaam != null &&
                    this.Woonplaatsnaam.Equals(input.Woonplaatsnaam))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FunctieAdres != null)
                    hashCode = hashCode * 59 + this.FunctieAdres.GetHashCode();
                if (this.Huisletter != null)
                    hashCode = hashCode * 59 + this.Huisletter.GetHashCode();
                hashCode = hashCode * 59 + this.Huisnummer.GetHashCode();
                if (this.Huisnummertoevoeging != null)
                    hashCode = hashCode * 59 + this.Huisnummertoevoeging.GetHashCode();
                if (this.AanduidingBijHuisnummer != null)
                    hashCode = hashCode * 59 + this.AanduidingBijHuisnummer.GetHashCode();
                if (this.IdentificatiecodeNummeraanduiding != null)
                    hashCode = hashCode * 59 + this.IdentificatiecodeNummeraanduiding.GetHashCode();
                if (this.NaamOpenbareRuimte != null)
                    hashCode = hashCode * 59 + this.NaamOpenbareRuimte.GetHashCode();
                if (this.Postcode != null)
                    hashCode = hashCode * 59 + this.Postcode.GetHashCode();
                if (this.Woonplaatsnaam != null)
                    hashCode = hashCode * 59 + this.Woonplaatsnaam.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Huisletter (string) maxLength
            if(this.Huisletter != null && this.Huisletter.Length > 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Huisletter, length must be less than 1.", new [] { "Huisletter" });
            }

            // Huisletter (string) pattern
            Regex regexHuisletter = new Regex(@"^[A-Z,a-z]$", RegexOptions.CultureInvariant);
            if (false == regexHuisletter.Match(this.Huisletter).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Huisletter, must match a pattern of " + regexHuisletter, new [] { "Huisletter" });
            }

            // Huisnummer (int) maximum
            if(this.Huisnummer > (int)99999)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Huisnummer, must be a value less than or equal to 99999.", new [] { "Huisnummer" });
            }

            // Huisnummertoevoeging (string) maxLength
            if(this.Huisnummertoevoeging != null && this.Huisnummertoevoeging.Length > 4)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Huisnummertoevoeging, length must be less than 4.", new [] { "Huisnummertoevoeging" });
            }

            // Huisnummertoevoeging (string) pattern
            Regex regexHuisnummertoevoeging = new Regex(@"^[a-zA-Z0-9]{1,4}$", RegexOptions.CultureInvariant);
            if (false == regexHuisnummertoevoeging.Match(this.Huisnummertoevoeging).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Huisnummertoevoeging, must match a pattern of " + regexHuisnummertoevoeging, new [] { "Huisnummertoevoeging" });
            }

            // IdentificatiecodeNummeraanduiding (string) maxLength
            if(this.IdentificatiecodeNummeraanduiding != null && this.IdentificatiecodeNummeraanduiding.Length > 16)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for IdentificatiecodeNummeraanduiding, length must be less than 16.", new [] { "IdentificatiecodeNummeraanduiding" });
            }

            // NaamOpenbareRuimte (string) maxLength
            if(this.NaamOpenbareRuimte != null && this.NaamOpenbareRuimte.Length > 80)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for NaamOpenbareRuimte, length must be less than 80.", new [] { "NaamOpenbareRuimte" });
            }

            // Postcode (string) pattern
            Regex regexPostcode = new Regex(@"^[1-9]{1}[0-9]{3}[A-Z]{2}$", RegexOptions.CultureInvariant);
            if (false == regexPostcode.Match(this.Postcode).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Postcode, must match a pattern of " + regexPostcode, new [] { "Postcode" });
            }

            // Woonplaatsnaam (string) maxLength
            if(this.Woonplaatsnaam != null && this.Woonplaatsnaam.Length > 80)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Woonplaatsnaam, length must be less than 80.", new [] { "Woonplaatsnaam" });
            }

            yield break;
        }
    }

}
