/* 
 * Bevragingen ingeschreven personen
 *
 * API voor het ontsluiten van gegevens van ingeschreven personen en aanverwante gegevens uit de GBA en RNI. Met deze API worden de actuele gegevens van ingeschreven personen, hun kinderen, partners en ouders ontsloten. <br> Heeft een persoon bijvoorbeeld geen geldige nationaliteit, dan wordt nationaliteit niet geretourneerd. <br> Heeft een persoon een beëindigd partnerschap of huwelijk, dan wordt de partner niet geretourneerd. <br> <br> Zie de [Functionele documentatie](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/tree/master/features) voor nadere toelichting. <br> 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// OuderHal
    /// </summary>
    [DataContract]
    public partial class OuderHal :  IEquatable<OuderHal>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OuderHal" /> class.
        /// </summary>
        /// <param name="burgerservicenummer">Het burgerservicenummer, bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer. Alle nummers waarvoor geldt dat, indien aangeduid als (s0 s1 s2 s3 s4 s5 s6 s7 s8), het resultaat van (9*s0) + (8*s1) + (7*s2) +...+ (2*s7) - (1*s8) deelbaar is door elf. Er moeten dus 9 cijfers aanwezig zijn..</param>
        /// <param name="geslachtsaanduiding">geslachtsaanduiding.</param>
        /// <param name="ouderAanduiding">ouderAanduiding.</param>
        /// <param name="datumIngangFamilierechtelijkeBetrekking">datumIngangFamilierechtelijkeBetrekking.</param>
        /// <param name="naam">naam.</param>
        /// <param name="inOnderzoek">inOnderzoek.</param>
        /// <param name="geboorte">geboorte.</param>
        /// <param name="geheimhoudingPersoonsgegevens">Een aanduiding die aangeeft dat gegevens wel of niet verstrekt mogen worden. Indien true: op verzoek van deze persoon is het verstrekken van gegevens over deze persoon aan bepaalde derden niet toegestaan..</param>
        /// <param name="links">links.</param>
        public OuderHal(string burgerservicenummer = default(string), GeslachtEnum geslachtsaanduiding = default(GeslachtEnum), OuderAanduidingEnum ouderAanduiding = default(OuderAanduidingEnum), DatumOnvolledig datumIngangFamilierechtelijkeBetrekking = default(DatumOnvolledig), Naam naam = default(Naam), OuderInOnderzoek inOnderzoek = default(OuderInOnderzoek), Geboorte geboorte = default(Geboorte), bool geheimhoudingPersoonsgegevens = default(bool), OuderLinks links = default(OuderLinks))
        {
            this.Burgerservicenummer = burgerservicenummer;
            this.Geslachtsaanduiding = geslachtsaanduiding;
            this.OuderAanduiding = ouderAanduiding;
            this.DatumIngangFamilierechtelijkeBetrekking = datumIngangFamilierechtelijkeBetrekking;
            this.Naam = naam;
            this.InOnderzoek = inOnderzoek;
            this.Geboorte = geboorte;
            this.GeheimhoudingPersoonsgegevens = geheimhoudingPersoonsgegevens;
            this.Links = links;
        }
        
        /// <summary>
        /// Het burgerservicenummer, bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer. Alle nummers waarvoor geldt dat, indien aangeduid als (s0 s1 s2 s3 s4 s5 s6 s7 s8), het resultaat van (9*s0) + (8*s1) + (7*s2) +...+ (2*s7) - (1*s8) deelbaar is door elf. Er moeten dus 9 cijfers aanwezig zijn.
        /// </summary>
        /// <value>Het burgerservicenummer, bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer. Alle nummers waarvoor geldt dat, indien aangeduid als (s0 s1 s2 s3 s4 s5 s6 s7 s8), het resultaat van (9*s0) + (8*s1) + (7*s2) +...+ (2*s7) - (1*s8) deelbaar is door elf. Er moeten dus 9 cijfers aanwezig zijn.</value>
        [DataMember(Name="burgerservicenummer", EmitDefaultValue=false)]
        public string Burgerservicenummer { get; set; }

        /// <summary>
        /// Gets or Sets Geslachtsaanduiding
        /// </summary>
        [DataMember(Name="geslachtsaanduiding", EmitDefaultValue=false)]
        public GeslachtEnum Geslachtsaanduiding { get; set; }

        /// <summary>
        /// Gets or Sets OuderAanduiding
        /// </summary>
        [DataMember(Name="ouderAanduiding", EmitDefaultValue=false)]
        public OuderAanduidingEnum OuderAanduiding { get; set; }

        /// <summary>
        /// Gets or Sets DatumIngangFamilierechtelijkeBetrekking
        /// </summary>
        [DataMember(Name="datumIngangFamilierechtelijkeBetrekking", EmitDefaultValue=false)]
        public DatumOnvolledig DatumIngangFamilierechtelijkeBetrekking { get; set; }

        /// <summary>
        /// Gets or Sets Naam
        /// </summary>
        [DataMember(Name="naam", EmitDefaultValue=false)]
        public Naam Naam { get; set; }

        /// <summary>
        /// Gets or Sets InOnderzoek
        /// </summary>
        [DataMember(Name="inOnderzoek", EmitDefaultValue=false)]
        public OuderInOnderzoek InOnderzoek { get; set; }

        /// <summary>
        /// Gets or Sets Geboorte
        /// </summary>
        [DataMember(Name="geboorte", EmitDefaultValue=false)]
        public Geboorte Geboorte { get; set; }

        /// <summary>
        /// Een aanduiding die aangeeft dat gegevens wel of niet verstrekt mogen worden. Indien true: op verzoek van deze persoon is het verstrekken van gegevens over deze persoon aan bepaalde derden niet toegestaan.
        /// </summary>
        /// <value>Een aanduiding die aangeeft dat gegevens wel of niet verstrekt mogen worden. Indien true: op verzoek van deze persoon is het verstrekken van gegevens over deze persoon aan bepaalde derden niet toegestaan.</value>
        [DataMember(Name="geheimhoudingPersoonsgegevens", EmitDefaultValue=false)]
        public bool GeheimhoudingPersoonsgegevens { get; set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name="_links", EmitDefaultValue=false)]
        public OuderLinks Links { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OuderHal {\n");
            sb.Append("  Burgerservicenummer: ").Append(Burgerservicenummer).Append("\n");
            sb.Append("  Geslachtsaanduiding: ").Append(Geslachtsaanduiding).Append("\n");
            sb.Append("  OuderAanduiding: ").Append(OuderAanduiding).Append("\n");
            sb.Append("  DatumIngangFamilierechtelijkeBetrekking: ").Append(DatumIngangFamilierechtelijkeBetrekking).Append("\n");
            sb.Append("  Naam: ").Append(Naam).Append("\n");
            sb.Append("  InOnderzoek: ").Append(InOnderzoek).Append("\n");
            sb.Append("  Geboorte: ").Append(Geboorte).Append("\n");
            sb.Append("  GeheimhoudingPersoonsgegevens: ").Append(GeheimhoudingPersoonsgegevens).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OuderHal);
        }

        /// <summary>
        /// Returns true if OuderHal instances are equal
        /// </summary>
        /// <param name="input">Instance of OuderHal to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OuderHal input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Burgerservicenummer == input.Burgerservicenummer ||
                    (this.Burgerservicenummer != null &&
                    this.Burgerservicenummer.Equals(input.Burgerservicenummer))
                ) && 
                (
                    this.Geslachtsaanduiding == input.Geslachtsaanduiding ||
                    (this.Geslachtsaanduiding != null &&
                    this.Geslachtsaanduiding.Equals(input.Geslachtsaanduiding))
                ) && 
                (
                    this.OuderAanduiding == input.OuderAanduiding ||
                    (this.OuderAanduiding != null &&
                    this.OuderAanduiding.Equals(input.OuderAanduiding))
                ) && 
                (
                    this.DatumIngangFamilierechtelijkeBetrekking == input.DatumIngangFamilierechtelijkeBetrekking ||
                    (this.DatumIngangFamilierechtelijkeBetrekking != null &&
                    this.DatumIngangFamilierechtelijkeBetrekking.Equals(input.DatumIngangFamilierechtelijkeBetrekking))
                ) && 
                (
                    this.Naam == input.Naam ||
                    (this.Naam != null &&
                    this.Naam.Equals(input.Naam))
                ) && 
                (
                    this.InOnderzoek == input.InOnderzoek ||
                    (this.InOnderzoek != null &&
                    this.InOnderzoek.Equals(input.InOnderzoek))
                ) && 
                (
                    this.Geboorte == input.Geboorte ||
                    (this.Geboorte != null &&
                    this.Geboorte.Equals(input.Geboorte))
                ) && 
                (
                    this.GeheimhoudingPersoonsgegevens == input.GeheimhoudingPersoonsgegevens ||
                    this.GeheimhoudingPersoonsgegevens.Equals(input.GeheimhoudingPersoonsgegevens)
                ) && 
                (
                    this.Links == input.Links ||
                    (this.Links != null &&
                    this.Links.Equals(input.Links))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Burgerservicenummer != null)
                    hashCode = hashCode * 59 + this.Burgerservicenummer.GetHashCode();
                if (this.Geslachtsaanduiding != null)
                    hashCode = hashCode * 59 + this.Geslachtsaanduiding.GetHashCode();
                if (this.OuderAanduiding != null)
                    hashCode = hashCode * 59 + this.OuderAanduiding.GetHashCode();
                if (this.DatumIngangFamilierechtelijkeBetrekking != null)
                    hashCode = hashCode * 59 + this.DatumIngangFamilierechtelijkeBetrekking.GetHashCode();
                if (this.Naam != null)
                    hashCode = hashCode * 59 + this.Naam.GetHashCode();
                if (this.InOnderzoek != null)
                    hashCode = hashCode * 59 + this.InOnderzoek.GetHashCode();
                if (this.Geboorte != null)
                    hashCode = hashCode * 59 + this.Geboorte.GetHashCode();
                hashCode = hashCode * 59 + this.GeheimhoudingPersoonsgegevens.GetHashCode();
                if (this.Links != null)
                    hashCode = hashCode * 59 + this.Links.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Burgerservicenummer (string) maxLength
            if(this.Burgerservicenummer != null && this.Burgerservicenummer.Length > 9)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Burgerservicenummer, length must be less than 9.", new [] { "Burgerservicenummer" });
            }

            // Burgerservicenummer (string) minLength
            if(this.Burgerservicenummer != null && this.Burgerservicenummer.Length < 9)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Burgerservicenummer, length must be greater than 9.", new [] { "Burgerservicenummer" });
            }

            // Burgerservicenummer (string) pattern
            Regex regexBurgerservicenummer = new Regex(@"^[0-9]*$", RegexOptions.CultureInvariant);
            if (false == regexBurgerservicenummer.Match(this.Burgerservicenummer).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Burgerservicenummer, must match a pattern of " + regexBurgerservicenummer, new [] { "Burgerservicenummer" });
            }

            yield break;
        }
    }

}
