/* 
 * Bevragen Ingeschreven Personen
 *
 * API voor het bevragen van ingeschreven personen uit de basisregistratie personen (BRP), inclusief de registratie niet-ingezeten (RNI). Met deze API kun je personen zoeken en actuele gegevens over personen, kinderen, partners en ouders raadplegen.  Gegevens die er niet zijn of niet actueel zijn krijg je niet terug. Heeft een persoon bijvoorbeeld geen geldige nationaliteit, en alleen een beëindigd partnerschap, dan krijg je geen gegevens over nationaliteit en partner.  Zie de [Functionele documentatie](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/tree/v1.0.0/features) voor nadere toelichting. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Aanduiding van het soort adres * &#x60;woonadres&#x60; - W - adres waar de persoon woont * &#x60;briefadres&#x60; - B - het adres van een andere persoon of van een instelling (de zogenoemde briefadresgever). Met dit adres van de briefadresgever is de persoon zonder woonadres toch bereikbaar voor de overheid. 
    /// </summary>
    /// <value>Aanduiding van het soort adres * &#x60;woonadres&#x60; - W - adres waar de persoon woont * &#x60;briefadres&#x60; - B - het adres van een andere persoon of van een instelling (de zogenoemde briefadresgever). Met dit adres van de briefadresgever is de persoon zonder woonadres toch bereikbaar voor de overheid. </value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum SoortAdresEnum
    {
        /// <summary>
        /// Enum Woonadres for value: woonadres
        /// </summary>
        [EnumMember(Value = "woonadres")]
        Woonadres = 1,

        /// <summary>
        /// Enum Briefadres for value: briefadres
        /// </summary>
        [EnumMember(Value = "briefadres")]
        Briefadres = 2

    }

}
