openapi: 3.1.0
info:
  title: geboorte basis type definitie
  version: 1.0.0
components:
  schemas:
    GeboorteBasis:
      type: object
      properties:
        datum:
          $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
          description: |
            Datum waarop de persoon is geboren.
