openapi: 3.1.0
info: 
  title: aangaan huwelijk/partnerschap schema definitie
  version: 1.0.0
components: 
  schemas:
    GbaAangaanHuwelijkPartnerschap:
      allOf: 
        - $ref: 'aangaan-huwelijk-partnerschap-basis-v1.yaml#/components/schemas/AangaanHuwelijkPartnerschapBasis'
        - type: object
          properties:
            datum:
              description: |
                De datum waarop het huwelijk is voltrokken of het partnerschap is aangegaan.
              $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
