openapi: 3.1.0
info: 
  title: ontbinding huwelijk/partnerschap schema definitie
  version: 1.0.0
components: 
  schemas:
    GbaOntbindingHuwelijkPartnerschap:
      type: object
      properties:
        datum:
          $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
