openapi: 3.1.0
info: 
  title: partner
  version: 1.0.0
components: 
  schemas:
    PartnerBasis:
      type: object
      properties: 
        burgerservicenummer:
          $ref: '../identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        geslacht:
          description: |
            wordt gevuld met waarden voor 'Geslacht' in 'tabelwaarden.csv'.
          $ref: '../waardetabel-v1.yaml#/components/schemas/Waardetabel'
        soortVerbintenis:
          $ref: '../waardetabel-v1.yaml#/components/schemas/Waardetabel'
