openapi: 3.1.0
info:
  title: indicatie geheim type definitie
  version: 1.0.0
components:
  schemas:
    IndicatieGeheim:
      description: |
        Gegevens over het mogen verstrekken van persoonsgegevens aan derden / maatschappelijke instellingen.
      type: integer
      minimum: 0
      maximum: 7
