openapi: 3.1.0
info: 
  title: ouder
  version: 1.0.0
components: 
  schemas:
    GbaOuder:
      allOf: 
        - $ref: 'ouder-basis-v1.yaml#/components/schemas/OuderBasis'
        - type: object
          properties:
            datumIngangFamilierechtelijkeBetrekking:
              description: |
                De datum waarop de familierechtelijke betrekking is ontstaan.
              $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
            naam:
              $ref: '../naam/naam-basis-v1.yaml#/components/schemas/NaamBasis'
            geboorte:
              $ref: '../geboorte/geboorte-v1.yaml#/components/schemas/GbaGeboorte'
            inOnderzoek:
              $ref: '../in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
