openapi: 3.1.0
info: 
  title: nationaliteit type definitie
  version: 1.0.0
components: 
  schemas:
    GbaNationaliteit:
      type: object
      properties:
        aanduidingBijzonderNederlanderschap:
          type: string
          pattern: ^(B|V)$
        datumIngangGeldigheid:
          $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
        nationaliteit:
          $ref: '../waardetabel-v1.yaml#/components/schemas/Waardetabel'
        redenOpname:
          $ref: '../waardetabel-v1.yaml#/components/schemas/Waardetabel'
        inOnderzoek:
            $ref: '../in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
