openapi: 3.1.0
info:
  title: gezagouder type definitie
  version: 2.0.0
paths: {}
components:
  schemas:
    GezagOuder:
      type: object
      properties:
        burgerservicenummer:
          $ref: '../identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        naam:
          $ref: '../naam/naam-basis-v1.yaml#/components/schemas/NaamBasis'
        geslacht:
          $ref: '../geslacht/geslachtsaanduiding-v1.yaml#/components/schemas/Geslachtsaanduiding'
      required: 
        -  burgerservicenummer
