openapi: 3.1.0
info:
  title: regel 3
  version: 1.0.0
components:
  schemas:
    Regel3:
      type: string
      maxLength: 35
      description: |
        Het derde deel van een buitenlands adres is optioneel. Het gaat om een of meer geografische gebieden van het adres in het buitenland.
      example: Selangor
