openapi: 3.1.0
info:
  title: regel 2
  version: 1.0.0
components:
  schemas:
    Regel2:
      type: string
      maxLength: 50
      description: |
        Het tweede deel van een buitenlands adres. Vaak is dit een combinatie van woonplaats eventueel in combinatie met de postcode.
