openapi: 3.1.0
info: 
  title: immigratie schema definitie
  version: 1.0.0
components: 
  schemas:
    GbaImmigratie:
      allOf: 
        - $ref: 'immigratie-basis-v1.yaml#/components/schemas/ImmigratieBasis'
        - type: object
          properties:
            datumVestigingInNederland:
              $ref: '../datum-v1.yaml#/components/schemas/GbaDatum'
