version: '3.7'

services:
  haalcentraal_api:
    image: haalcentraal.azurecr.io/gba-api:2.2.0-2024042201
    environment:
      - Database__Host=postgres
      - Database__Username=root
      - Database__Password=root
      - Database__Database=rvig_haalcentraal_testdata
      - HaalcentraalApi__MaxSearchResults=10
      - ASPNETCORE_URLS=http://+;
      - AuthenticationTypes=Basic
      # - AuthenticationTypes=jwtbearer
      - Serilog__MinimumLevel__Default=Information
      # - WebApi__Url=http://gezagmock:5020
    ports:
      - "8000:80"
    networks:
      - brp-api-network

networks:
  brp-api-network:
    name: brp-api-network
