openapi: 3.1.0
info:
  title: Locatie
  version: 1.0.0
  contact: {}
components:
  schemas:
    VerblijfadresLocatie:
      type: object
      properties:
        locatiebeschrijving:
          $ref: '../../brp/locatie/locatiebeschrijving-v1.yaml#/components/schemas/Locatiebeschrijving'
        inOnderzoek:
          $ref: "#/components/schemas/VerblijfadresLocatieInOnderzoek"

    VerblijfadresLocatieInOnderzoek:
      allOf:
        - $ref: '../in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            locatiebeschrijving:
              type: boolean

    Locatie:
      allOf:
        - $ref : 'verblijfplaats-polymorf-v1.yaml#/components/schemas/AbstractVerblijfplaats'
        - type: object
          properties:
            datumVan:
              $ref: '../datum/datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
            functieAdres:
              $ref: '../../brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
            verblijfadres:
              $ref: "#/components/schemas/VerblijfadresLocatie"
            indicatieVastgesteldVerblijftNietOpAdres:
              $ref: 'indicatie-vastgesteld-verblijft-niet-op-adres-v1.yaml#/components/schemas/IndicatieVastgesteldVerblijftNietOpAdres'
            inOnderzoek:
              $ref: '#/components/schemas/LocatieInOnderzoek'

    LocatieInOnderzoek:
      allOf:
        - $ref: '../in-onderzoek-v1.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            type:
              type: boolean
            datumVan:
              type: boolean
            functieAdres:
              type: boolean
            datumIngangGeldigheid:
              type: boolean
              deprecated: true
