openapi: 3.0.3
info:
  title: Adressering definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Adressering:
      type: "object"
      description: ""
      properties:
        aanhef:
          $ref: "naam.yaml#/components/schemas/Aanhef"
        aanschrijfwijze:
          $ref: "naam.yaml#/components/schemas/Aanschrijfwijze"
        gebruikInLopendeTekst:
          $ref: "naam.yaml#/components/schemas/GebruikInLopendeTekst"
        adresseringregel1:
          $ref: "verblijfplaats.yaml#/components/schemas/Adresregel1"
        adresseringregel2:
          $ref: "verblijfplaats.yaml#/components/schemas/Adresregel2"
        adresseringregel3:
          $ref: "verblijfplaats.yaml#/components/schemas/Adresregel3"
        land:
          $ref: "common.yaml#/components/schemas/Waardetabel"
