openapi: 3.0.3
info:
  title: Header, foutresponse en waardetabel definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  headers:
    api_version:
      schema:
        type: string
        pattern: ^[1-9][0-9]{0,2}.[0-9]{1,3}.[0-9]{1,3}$
        description: Geeft een specifieke API-versie aan in de context van een specifieke aanroep.
        example: 1.0.0
    warning:
      schema:
        type: string
        maxLength: 500
        description: 'zie RFC 7234. In het geval een major versie wordt uitgefaseerd, gebruiken we warn-code 299 ("Miscellaneous Persistent Warning") en het API end-point (inclusief versienummer) als de warn-agent van de warning, gevolgd door de warn-text met de human-readable waarschuwing'
        example: '299 https://service.../api/.../v1 "Deze versie van de API is verouderd en zal uit dienst worden genomen op 2018-02-01. Raadpleeg voor meer informatie hier de documentatie: https://omgevingswet.../api/.../v1".'
    X_Rate_Limit_Limit:
      schema:
        type: integer
    X_Rate_Limit_Remaining:
      schema:
        type: integer
    X_Rate_Limit_Reset:
      schema:
        type: integer
  responses:
    '204':
      description: No content
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
    '400':
      description: Bad Request
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/BadRequestFoutbericht"
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.1
            title: Ten minste één parameter moet worden opgegeven.
            status: 400
            detail: The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: paramsRequired
            invalidParams:
              - type: https://www.vng.nl/realisatie/api/validaties/integer
                name: verblijfplaats__huisnummer
                code: integer
                reason: Waarde is geen geldige integer.
    '401':
      description: Unauthorized
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Foutbericht"
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.2
            title: Niet correct geauthenticeerd.
            status: 401
            detail: The request requires user authentication. The response MUST include a WWW-Authenticate header field (section 14.47) containing a challenge applicable to the requested resource.
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: authentication
    '403':
      description: Forbidden
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Foutbericht"
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.4
            title: U bent niet geautoriseerd voor deze operatie.
            status: 403
            detail: The server understood the request, but is refusing to fulfill it.
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: autorisation
    '404':
      description: Not Found
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Foutbericht"
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5
            title: Opgevraagde resource bestaat niet.
            status: 404
            detail: The server has not found anything matching the Request-URI.
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: notFound
    '406':
      description: Not Acceptable
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Foutbericht"
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.7
            title: Gevraagde contenttype wordt niet ondersteund.
            status: 406
            detail: The resource identified by the request is only capable of generating response entities which have content characteristics not acceptable according to thr accept headers sent in the request
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: notAcceptable
    '409':
      description: Conflict
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Foutbericht"
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10
            title: Conflict
            status: 409
            detail: The request could not be completed due to a conflict with the current state of the resource
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: conflict
    '410':
      description: Gone
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Foutbericht"
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.11
            title: Gone
            status: 410
            detail: The request could not be completed due to a conflict with the current state of the resource
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: gone
    '412':
      description: Precondition failed
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Foutbericht"
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.13
            title: Precondition Failed
            status: 412
            detail: The precondition given in one or more of the request-header fields evaluated to false when it was tested on the server.
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: preconditionFailed
    '415':
      description: Unsupported Media Type
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Foutbericht"
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.16
            title: Unsupported Media Type
            status: 415
            detail: The server is refusing the request because the entity of the request is in a format not supported by the requested resource for the requested method.
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: unsupported
    '422':
      description: Unprocessable entity
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Foutbericht"
          example:
            type: https://tools.ietf.org/html/rfc4918#section-11.2
            title: Aanvraag kan niet verwerkt worden
            status: 422
            detail: The server understands the content type of the request entity and the syntax of the request entity is correct but was unable to process the contained instructions.
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: unprocessableEntity
    '429':
      description: Too Many Requests
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Foutbericht"
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
            title: Too many request
            status: 429
            detail: The user has sent too many requests in a given amount of time (rate limiting).
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: tooManyRequests
    '500':
      description: Internal Server Error
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Foutbericht"
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5.1
            title: Interne server fout.
            status: 500
            detail: The server encountered an unexpected condition which prevented it from fulfilling the request.
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: serverError
    '501':
      description: Not Implemented
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Foutbericht"
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5.2
            title: Not Implemented
            status: 501
            detail: The server does not support the functionality required to fulfill the request.
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: notImplemented
    '503':
      description: Service Unavailable
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Foutbericht"
          example:
            type: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.5.4
            title: Bronservice BRP is tijdelijk niet beschikbaar.
            status: 503
            detail: The service is currently unable to handle the request due to a temporary overloading or maintenance of the server.
            instance: https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde
            code: notAvailable
    'default':
      description: Er is een onverwachte fout opgetreden
      headers:
        api-version:
          $ref: "#/components/headers/api_version"
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/Foutbericht"
  schemas:
    Foutbericht:
      type: object
      description: Terugmelding bij een fout. JSON representatie in lijn met [RFC7807](https://tools.ietf.org/html/rfc7807).
      properties:
        type:
          type: string
          format: uri
          description: Link naar meer informatie over deze fout
        title:
          type: string
          pattern: ^[a-zA-Z0-9À-ž \.\-]{1,80}$
          description: Beschrijving van de fout
        status:
          type: integer
          minimum: 100
          maximum: 600
          description: Http status code
        detail:
          type: string
          pattern: ^[a-zA-Z0-9À-ž \.\-\(\)\,]{1,200}$
          description: Details over de fout
        instance:
          type: string
          format: uri
          description: Uri van de aanroep die de fout heeft veroorzaakt
        code:
          type: string
          pattern: ^[a-zA-Z0-9]{1,25}$
          description: Systeemcode die het type fout aangeeft
          minLength: 1
    InvalidParams:
      type: object
      description: Details over fouten in opgegeven parameters
      properties:
        type:
          type: string
          format: uri
          example: "https://www.vng.nl/realisatie/api/{major-versie}/validaties/integer"
        name:
          type: string
          pattern: ^[a-zA-Z0-9\.,_]{1,30}$
          description: Naam van de parameter
          example: "verblijfplaats__huisnummer"
        code:
          type: string
          pattern: ^[a-zA-Z0-9\.,_]{1,25}$
          description: Systeemcode die het type fout aangeeft
          minLength: 1
          example: "integer"
        reason:
          type: string
          pattern: ^[a-zA-Z0-9\.,_ ]{1,80}$
          description: Beschrijving van de fout op de parameterwaarde
          example: "Waarde is geen geldige integer."
    BadRequestFoutbericht:
      allOf:
      - $ref: "#/components/schemas/Foutbericht"
      - type: "object"
        properties:
          invalidParams:
            description: Foutmelding per fout in een parameter. Alle gevonden fouten worden één keer teruggemeld.
            type: array
            items:
              $ref: "#/components/schemas/InvalidParams"
    Waardetabel:
      type: "object"
      properties:
        code:
          type: "string"
          pattern: ^[a-zA-Z0-9 \.]+$
          example: "6030"
        omschrijving:
          type: "string"
          pattern: ^[a-zA-Z0-9À-ž \'\,\(\)\.\-]{1,200}$
          example: "Nederland"
