openapi: 3.0.3
info:
  title: Datum definities
  description: |
    Definities voor de volgende datum types:
    - datum conform LO GBA
    - onbekend datum
    - 'volledig' datum conform ISO-8601
    - datum waarvan de dag onbekend is
    - datum waarvan de maand en dag onbekend is 
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    AbstractDatum:
      type: object
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          GbaDatum: '#/components/schemas/GbaDatum'
          Datum: '#/components/schemas/VolledigDatum'
          OnbekendDatum: '#/components/schemas/OnbekendDatum'
          JaarDatum: '#/components/schemas/JaarDatum'
          JaarMaandDatum: '#/components/schemas/JaarMaandDatum'
    GbaDatumBasis:
      type: object
      properties:
        datum:
          type: string
          pattern: ^[0-9]{8}$
    GbaDatum:
      description: Datum conform LO GBA
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - $ref: '#/components/schemas/GbaDatumBasis'
      required:
        - datum
      example:
        value:
          type: GbaDatum
          datum: "20180700"
    VolledigDatum:
      description: Datum conform iso8601
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - type: object
          properties:
            datum:
              type: string
              format: date
      required:
        - datum
      example:
        value:
          type: Datum
          datum: "2018-07-01"
    OnbekendDatum:
      description: representatie voor een volledig onbekend datum
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - type: object
          properties:
            onbekend:
              type: boolean
              default: true
      required:
        - onbekend
      example:
        value:
          type: OnbekendDatum
          onbekend: true
    JaarDatum:
      description: representatie voor een datum waarvan maand en dag onbekend zijn
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - type: object
          properties:
            jaar:
              $ref: '#/components/schemas/Jaar'
      required:
        - jaar
      example:
        value:
          type: JaarDatum
          jaar: 2018
    JaarMaandDatum:
      description: representatie voor een datum waarvan de dag onbekend is
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - type: object
          properties:
            jaar:
              $ref: '#/components/schemas/Jaar'
            maand:
              $ref: '#/components/schemas/Maand'
      required:
        - jaar
        - maand
      example:
        value:
          type: JaarMaandDatum
          jaar: 2018
          maand: 7
    Jaar:
      type: integer
      format: int32
      minimum: 1
      maximum: 9999
    Maand:
      type: integer
      format: int32
      minimum: 1
      maximum: 12
