openapi: 3.0.3
info:
  title: Datum definities
  description: |
    Definities voor de volgende datum types:
    - datum conform LO GBA
    - onbekend datum
    - 'volledig' datum conform ISO-8601
    - datum waarvan de dag onbekend is
    - datum waarvan de maand en dag onbekend is 
  version: 2.0.0
  contact: {}
paths:
  /examples/datums:
    get:
      responses:
        '200':
          description: |
            Als voorbeeld een lijst met LO GBA datum soorten

            - volledig
            - onvolledig: dag onbekend
            - onvolledig: maand en dag onbekend
            - onvolledig: volledig onbekend

            en hun Haal Centraal tegenhanger
          content:
            application/json:
              schema:
                type: object
                properties:
                  datums:
                    type: array
                    items:
                      $ref: '#/components/schemas/AbstractDatum'
                example:
                  [
                    { "type": "GbaDatum", "waarde": "20180701" },
                    { "type": "GbaDatum", "waarde": "20161200" },
                    { "type": "GbaDatum", "waarde": "20100000" },
                    { "type": "GbaDatum", "waarde": "00000000" },
                    { "type": "Datum", "waarde": "2018-07-01" },
                    { "type": "JaarMaandDatum", "jaar": "2016", "maand": "12" },
                    { "type": "JaarDatum", "jaar": "2010" },
                    { "type": "OnbekendDatum", "onbekend": true }
                  ]
components:
  schemas:
    AbstractDatum:
      type: object
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          GbaDatum: '#/components/schemas/GbaDatum'
          Datum: '#/components/schemas/Datum'
          OnbekendDatum: '#/components/schemas/OnbekendDatum'
          JaarDatum: '#/components/schemas/JaarDatum'
          JaarMaandDatum: '#/components/schemas/JaarMaandDatum'
    GbaDatum:
      description: Datum conform LO GBA
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - type: object
          properties:
            waarde:
              type: string
              pattern: "^[0-9]{8}$"
              minLength: 8
              maxLength: 8
      required:
        - waarde
      example: 20210801
    Datum:
      description: Datum conform iso8601
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - type: object
          properties:
            waarde:
              type: string
              format: date
              minLength: 10
              maxLength: 10
      required:
        - waarde
      example: 2021-08-01
    OnbekendDatum:
      description: representatie voor een onbekend datum
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - type: object
          properties:
            onbekend:
              type: boolean
              default: true
      required:
        - onbekend
    JaarDatum:
      description: representatie voor een datum waarvan maand en dag onbekend zijn
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - type: object
          properties:
            jaar:
              $ref: '#/components/schemas/Jaar'
      required:
        - jaar
    JaarMaandDatum:
      description: representatie voor een datum waarvan de dag onbekend is
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - type: object
          properties:
            jaar:
              $ref: '#/components/schemas/Jaar'
            maand:
              $ref: '#/components/schemas/Maand'
      required:
        - jaar
        - maand
    Jaar:
      type: integer
      format: int32
      minimum: 0
      maximum: 9999
    Maand:
      type: integer
      format: int32
      minimum: 1
      maximum: 12
    DatumOnvolledig:
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - type: "object"
          description: "Gegevens over de datums die mogelijk niet volledig zijn."
          properties:
            dag:
              type: "integer"
              description: "Als de dag van de datum bekend is wordt dit element gevuld, ook als de volledige datum bekend is."
              minimum: 1
              maximum: 31
              example: 3
            datum:
              type: "string"
              description: "Als de volledige datum bekend is wordt de datum gevuld die in de date definitie past."
              format: "date"
              example: "1989-05-03"
            jaar:
              type: "integer"
              description: "Als het jaar van de datum bekend is wordt dit element gevuld, ook als de volledige datum bekend is."
              maximum: 9999
              example: 1989
            maand:
              type: "integer"
              description: "Als de maand van een datum bekend is wordt dit element gevuld, ook als de volledige datum bekend is."
              minimum: 1
              maximum: 12
              example: 5
