openapi: 3.0.3
info:
  title: Datum definities
  version: 2.0.0
  contact: {}
paths:
  /examples/datums:
    get:
      responses:
        '200':
          description: |
            Als voorbeeld een lijst met LO GBA datum soorten

            - volledig
            - onvolledig: dag onbekend
            - onvolledig: maand en dag onbekend
            - onvolledig: volledig onbekend

            en hun Haal Centraal tegenhanger
          content:
            application/json:
              schema:
                type: object
                properties:
                  datums:
                    type: array
                    items:
                      $ref: '#/components/schemas/AbstractDatum'
                example:
                  [
                    { "type": "logbadatum", "waarde": "20180701" },
                    { "type": "logbadatum", "waarde": "20161200" },
                    { "type": "logbadatum", "waarde": "20100000" },
                    { "type": "logbadatum", "waarde": "00000000" },
                    { "type": "datum", "waarde": "2018-07-01" },
                    { "type": "jaarmaanddatum", "jaar": "2016", "maand": "12" },
                    { "type": "jaardatum", "jaar": "2010" },
                    { "type": "onbekenddatum", "onbekend": true }
                  ]
components:
  schemas:
    AbstractDatum:
      type: object
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          GbaDatum: '#/components/schemas/GbaDatum'
          Datum: '#/components/schemas/Datum'
          OnbekendDatum: '#/components/schemas/OnbekendDatum'
          JaarDatum: '#/components/schemas/JaarDatum'
          JaarMaandDatum: '#/components/schemas/JaarMaandDatum'
    GbaDatum:
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - type: object
          properties:
            waarde:
              type: integer
    Datum:
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - type: object
          properties:
            waarde:
              type: string
              format: date
    OnbekendDatum:
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - type: object
          properties:
            onbekend:
              type: boolean
              default: true
    JaarDatum:
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - type: object
          properties:
            jaar:
              type: integer
    JaarMaandDatum:
      allOf:
        - $ref: '#/components/schemas/AbstractDatum'
        - type: object
          properties:
            jaar:
              type: integer
            maand:
              type: integer
