openapi: 3.1.0
servers:
  - description: |
      Proef omgeving
    url: https://proefomgeving-gba.haalcentraal.nl/haalcentraal/api/brp
info:
  title: BRP API Personen
  description: |
    API voor het bevragen van personen uit de basisregistratie personen (BRP), inclusief de registratie niet-ingezeten (RNI). Met deze API kun je personen zoeken en actuele gegevens over personen, kinderen, partners en ouders raadplegen.

    Gegevens die er niet zijn of niet actueel zijn krijg je niet terug. Had een persoon bijvoorbeeld een verblijfstitel die nu niet meer geldig is, dan wordt die verblijfstitel niet opgenomen. In partners wordt alleen de actuele of de laatst ontbonden partner geleverd.
  version: 2.2.0
  contact:
    url: https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
tags:
  - name: Personen
paths:
  /personen:
    $ref: 'zoek-gba-personen.yaml#/paths/~1personen'
