openapi: 3.0.3
info:
  title: Geheimhouding definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    AbstractGeheimhoudingPersoonsgegevens:
      description: |
        Gegevens mogen niet worden verstrekt aan derden / maatschappelijke instellingen.
      type: object
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          GbaGeheimhouding: '#/components/schemas/GbaGeheimhoudingPersoonsgegevens'
          Geheimhouding: '#/components/schemas/GeheimhoudingPersoonsgegevens'
    GbaGeheimhoudingPersoonsgegevens:
      allOf:
        - $ref: '#/components/schemas/AbstractGeheimhoudingPersoonsgegevens'
        - type: object
          properties:
            waarde:
              type: integer
    GeheimhoudingPersoonsgegevens:
      allOf:
        - $ref: '#/components/schemas/AbstractGeheimhoudingPersoonsgegevens'
        - type: object
          properties:
            geheimhouding:
              type: boolean
