openapi: 3.0.3
info:
  title: Gezag definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GbaGezagPersoonBeperkt:
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/GbaPersoonBeperkt'
        - type: object
          properties:
            gezag:
              $ref: "#/components/schemas/Gezag"
    GezagPersoonBeperkt:
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/PersoonBeperkt'
        - type: object
          properties:
            gezag:
              $ref: "#/components/schemas/Gezag"
    Gezag:
      type: array
      items: 
        $ref: 'brp-api/gezag/gezagsrelatie-v1.yaml#/components/schemas/AbstractGezagsrelatie'
      minItems: 0
