openapi: 3.0.3
info:
  title: Gezagsverhouding definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Gezagsverhouding:
      type: "object"
      description: |
                    Gegevens over het gezag over de persoon.
      properties:
        indicatieCurateleRegister:
          type: boolean
          description: |
                        Geeft aan dat de persoon onder curatele is gesteld.
          example: true
        indicatieGezagMinderjarige:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
        inOnderzoek:
          $ref: "#/components/schemas/AbstractGezagsverhoudingInOnderzoek"
    AbstractGezagsverhoudingInOnderzoek:
      type: object
      description: |
        Geeft aan welke gegevens van de gezagsverhouding in onderzoek zijn. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/in_onderzoek.feature)
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          GbaInOnderzoek: '#/components/schemas/GbaGezagsverhoudingInOnderzoek'
          InOnderzoek: '#/components/schemas/GezagsverhoudingInOnderzoek'
    GezagsverhoudingInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsverhoudingInOnderzoek'
        - type: object
          properties:
            indicatieCurateleRegister:
              type: boolean
            indicatieGezagMinderjarige:
              type: boolean
            datumIngangOnderzoek:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
    GbaGezagsverhoudingInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsverhoudingInOnderzoek'
        - type: object
          properties:
            aanduidingGegevensInOnderzoek:
              type: string
              maxLength: 50
            datumIngangOnderzoek:
              $ref: 'datum.yaml#/components/schemas/GbaDatum'
