openapi: 3.0.3
info:
  title: Gezag definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GbaGezagPersoonBeperkt:
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/GbaPersoonBeperkt'
        - type: object
          properties:
            gezag:
              $ref: "#/components/schemas/Gezag"
    GezagPersoonBeperkt:
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/PersoonBeperkt'
        - type: object
          properties:
            gezag:
              $ref: "#/components/schemas/Gezag"
    Gezag:
      type: array
      items: 
        $ref: '#/components/schemas/AbstractGezagsrelatie'
      minItems: 0
    Meerderjarige:
      type: object
      properties:
        burgerservicenummer:
          $ref: 'persoon.yaml#/components/schemas/Burgerservicenummer'
    Minderjarige:
      type: object
      properties:
        burgerservicenummer:
          $ref: 'persoon.yaml#/components/schemas/Burgerservicenummer'
      required: 
        - burgerservicenummer
    GezagOuder:
      type: object
      properties:
        burgerservicenummer:
          $ref: 'persoon.yaml#/components/schemas/Burgerservicenummer'
      required: 
        -  burgerservicenummer
    AbstractGezagsrelatie:
      type: object
      required:
        - type
        - minderjarige
      properties:
        type:
          type: string
        minderjarige:
          $ref: '#/components/schemas/Minderjarige'
      discriminator:
        propertyName: type
        mapping:
          TweehoofdigOuderlijkGezag: '#/components/schemas/TweehoofdigOuderlijkGezag'
          EenhoofdigOuderlijkGezag: '#/components/schemas/EenhoofdigOuderlijkGezag'
          GezamenlijkGezag: '#/components/schemas/GezamenlijkGezag'
          Voogdij: '#/components/schemas/Voogdij'
          TijdelijkGeenGezag: '#/components/schemas/TijdelijkGeenGezag'
          GezagNietTeBepalen: '#/components/schemas/GezagNietTeBepalen'
      example:
        type: 'TweehoofdigOuderlijkGezag'
        ouders:
          - burgerservicenummer: '999998870'
          - burgerservicenummer: '999998882'
        minderjarige:
          burgerservicenummer: '999998894'
    TweehoofdigOuderlijkGezag:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            ouders:
              type: array
              items:
                $ref: '#/components/schemas/GezagOuder'
              minItems: 2
              maxItems: 2
    EenhoofdigOuderlijkGezag:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            ouder:
              $ref: '#/components/schemas/GezagOuder'
    GezamenlijkGezag:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            ouder:
              $ref: '#/components/schemas/GezagOuder'
            derde:
              $ref: '#/components/schemas/Meerderjarige'
    Voogdij:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            derden:
              type: array
              items:
                $ref: '#/components/schemas/Meerderjarige'
              minItems: 0
              maxItems: 2
    TijdelijkGeenGezag:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            toelichting:
              $ref: '#/components/schemas/Toelichting'
    GezagNietTeBepalen:
      allOf:
        - $ref: '#/components/schemas/AbstractGezagsrelatie'
        - type: object
          properties:
            toelichting:
              $ref: '#/components/schemas/Toelichting'
    Toelichting:
      type: string
      pattern: ^[a-zA-Z0-9À-ž \/\;\:\.\-\?\(\)]{1,400}$
