openapi: 3.0.3
info:
  title: Gezagsverhouding definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GezagsverhoudingBasis:
      type: object
      description: |
        Gegevens over het gezag over de persoon.
        * **indicatieGezagMinderjarige** - wordt gevuld op basis van de waarden die voorkomen in de tabel 'Gezag_Minderjarige' uit de Haal-Centraal-BRP-tabellen-bevragen API.
      properties:
        indicatieCurateleRegister:
          type: boolean
          description: |
            Geeft aan dat de persoon onder curatele is gesteld.
          example: true
        indicatieGezagMinderjarige:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
    GbaGezagsverhouding:
      allOf:
        - $ref: '#/components/schemas/GezagsverhoudingBasis'
        - type: object
          properties:
            inOnderzoek:
              $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
    Gezagsverhouding:
      allOf:
        - $ref: '#/components/schemas/GezagsverhoudingBasis'
        - type: object
          properties:
            inOnderzoek:
              $ref: '#/components/schemas/GezagsverhoudingInOnderzoek'
    GezagsverhoudingInOnderzoek:
      description: |
        Geeft aan welke gegevens van de gezagsverhouding in onderzoek zijn.
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            indicatieCurateleRegister:
              type: boolean
            indicatieGezagMinderjarige:
              type: boolean
