openapi: 3.0.3
info:
  title: Immigratie definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    IndicatieVestigingVanuitBuitenland:
      type: boolean
      description: |
        Geeft aan dat de persoon zich vanuit het buitenland heeft ingeschreven.
    VanuitVerblijfplaatsOnbekend:
      type: boolean
      description: |
        Geeft aan dat de persoon is teruggekeerd uit een situatie van onbekende verblijfplaats
    Immigratie:
      type: object
      description: |
        Gegevens over het het immigratie van een persoon.
          * **landVanWaarIngeschreven** : het land waar de persoon woonde voor (her)vestiging in Nederland.
      properties:
        datumVestigingInNederland:
          $ref: 'brp-api/datum/datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
        landVanwaarIngeschreven:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        vanuitVerblijfplaatsOnbekend:
          $ref: '#/components/schemas/VanuitVerblijfplaatsOnbekend'
        indicatieVestigingVanuitBuitenland:
          $ref: '#/components/schemas/IndicatieVestigingVanuitBuitenland'
        inOnderzoek:
          $ref: '#/components/schemas/ImmigratieInOnderzoek'
    ImmigratieInOnderzoek:
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            datumVestigingInNederland:
              type: boolean
            landVanwaarIngeschreven:
              type: boolean
            vanuitVerblijfplaatsOnbekend:
              type: boolean
            indicatieVestigingVanuitBuitenland:
              type: boolean
