openapi: 3.0.3
info:
  title: Kiesrecht definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GbaKiesrecht:
      type: object
      properties:
        europeesKiesrecht:
          type: boolean
          description: |
            Geeft aan of persoon een oproep moet ontvangen voor verkiezingen voor het Europees parlement.
          example: true
        uitgeslotenVanKiesrecht:
          type: boolean
          example: true
        einddatumUitsluitingEuropeesKiesrecht:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
        einddatumUitsluitingKiesrecht:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
    UitsluitingKiesrecht:
      type: object
      properties:
        uitgeslotenVanKiesrecht:
          type: boolean
          example: true
        einddatumUitsluitingKiesrecht:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
    EuropeesKiesrecht:
      type: object
      description: |
        * **europeesKiesrecht** - DGeeft aan of persoon een oproep moet ontvangen voor verkiezingen voor het Europees parlement. Wordt gevuld op basis van de waarden die voorkomen in de tabel 'Europees_Kiesrecht' uit de Haal-Centraal-BRP-tabellen-bevragen API.
      properties:
        europeesKiesrecht:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        einddatumUitsluitingEuropeesKiesrecht:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
