openapi: 3.0.3
info:
  title: Kiesrecht definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    UitsluitingKiesrecht:
      type: object
      properties:
        uitgeslotenVanKiesrecht:
          type: boolean
          example: true
        einddatum:
          $ref: 'brp-api/datum/datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
    EuropeesKiesrecht:
      type: object
      description: |
        * **aanduiding** - Geeft aan of persoon een oproep moet ontvangen voor verkiezingen voor het Europees parlement.
      properties:
        aanduiding:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        einddatumUitsluiting:
          $ref: 'brp-api/datum/datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
