openapi: 3.0.3
info:
  title: Kiesrecht definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GbaUitsluitingKiesrecht:
      type: object
      properties:
        uitgeslotenVanKiesrecht:
          type: boolean
          example: true
        einddatum:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
    GbaEuropeesKiesrecht:
      type: object
      description: |
        * **aanduiding** - Geeft aan of persoon een oproep moet ontvangen voor verkiezingen voor het Europees parlement. Wordt gevuld op basis van de waarden die voorkomen in de tabel 'Europees_Kiesrecht' uit de Haal-Centraal-BRP-tabellen-bevragen API.
      properties:
        aanduiding:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        einddatumUitsluiting:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
    UitsluitingKiesrecht:
      type: object
      properties:
        uitgeslotenVanKiesrecht:
          type: boolean
          example: true
        einddatum:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
    EuropeesKiesrecht:
      type: object
      description: |
        * **aanduiding** - Geeft aan of persoon een oproep moet ontvangen voor verkiezingen voor het Europees parlement. Wordt gevuld op basis van de waarden die voorkomen in de tabel 'Europees_Kiesrecht' uit de Haal-Centraal-BRP-tabellen-bevragen API.
      properties:
        aanduiding:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        einddatumUitsluiting:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
