openapi: 3.0.3
info:
  title: Ouder definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Kiesrecht:
      type: "object"
      properties:
        europeesKiesrecht:
          type: boolean
          description: |
                        Geeft aan of persoon een oproep moet ontvangen voor verkiezingen voor het Europees parlement.
          example: true
        uitgeslotenVanKiesrecht:
          type: boolean
          example: true
        einddatumUitsluitingEuropeesKiesrecht:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/DatumOnvolledig"
        einddatumUitsluitingKiesrecht:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/DatumOnvolledig"
