openapi: 3.0.3
info:
  title: Kind definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Kind:
      type: object
      properties:
        burgerservicenummer:
          $ref: 'brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        inOnderzoek:
          $ref: '#/components/schemas/KindInOnderzoek'
        naam:
          $ref: 'naam.yaml#/components/schemas/NaamGerelateerde'
        geboorte:
          $ref: 'geboorte.yaml#/components/schemas/Geboorte'
    KindInOnderzoek:
      description: |
        Geeft aan of de gegevens over het kind van de persoon in onderzoek zijn.
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            burgerservicenummer:
              type: boolean
