openapi: 3.0.3
info:
  title: Kind definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    AbstractKind:
      type: object
      description: |
        Gegevens over een kind van de persoon.
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          Kind: '#/components/schemas/Kind'
          OnbekendKind: '#/components/schemas/OnbekendKind'
    Kind:
      allOf:
        - $ref: '#/components/schemas/AbstractKind'
        - type: object
          properties:
            identificatie:
              $ref: 'persoon.yaml#/components/schemas/PersoonIdentificatie'
            burgerservicenummer:
              $ref: 'persoon.yaml#/components/schemas/Burgerservicenummer'
            leeftijd:
              type: integer
              description: |
                Leeftijd op het moment van bevragen
              example: 12
            inOnderzoek:
              $ref: '#/components/schemas/AbstractKindInOnderzoek'
            naam:
              $ref: 'naam.yaml#/components/schemas/NaamGerelateerde'
            geboorte:
              $ref: 'geboorte.yaml#/components/schemas/Geboorte'
    OnbekendKind:
      allOf:
        - $ref: '#/components/schemas/AbstractKind'
        - type: object
          properties:
            indicatieOnbekend:
              type: boolean
              default: false
    AbstractKindInOnderzoek:
      type: object
      description: |
        Geeft aan of de gegevens over het kind van de persoon in onderzoek zijn. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/in_onderzoek.feature)
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          GbaInOnderzoek: '#/components/schemas/GbaKindInOnderzoek'
          InOnderzoek: '#/components/schemas/KindInOnderzoek'
    KindInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/AbstractKindInOnderzoek'
        - type: object
          properties:
            burgerservicenummer:
              type: boolean
            datumIngangOnderzoek:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
    GbaKindInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/AbstractKindInOnderzoek'
        - $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
