openapi: 3.0.3
info:
  title: Land definities
  version: 2.0.0
paths: {}
components:
  schemas:
    AbstractLand:
      type: object
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          Land: '#/components/schemas/Land'
          OnbekendLand: '#/components/schemas/OnbekendLand'
    Land:
      allOf:
      - $ref: '#/components/schemas/AbstractLand'
      - $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
    OnbekendLand:
      allOf:
      - $ref: '#/components/schemas/AbstractLand'
      - type: object
        properties:
          onbekend:
            type: boolean
            default: true
