openapi: 3.0.3
info:
  title: Naam definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    AbstractNaamBasis:
      type: object
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          GbaNaam: '#/components/schemas/GbaNaamBasis'
          Naam: '#/components/schemas/NaamBasis'
    GbaNaamBasis:
      type: object
      properties:
        voornamen:
          type: string
          maxLength: 200
          description: |
            De verzameling namen voor de geslachtsnaam, gescheiden door spaties.
        voorvoegsel:
          type: string
          maxLength: 10
          example: "de"
        geslachtsnaam:
          type: string
          maxLength: 200
          description: |
            De achternaam van een persoon.
          example: "Vries"
        adellijkeTitelPredikaat:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel"
    NaamBasis:
      allOf:
        - $ref: '#/components/schemas/GbaNaamBasis'
        - type: object
          properties:
            voorletters:
              type: string
              description: |
                De voorletters van de persoon, afgeleid van de voornamen.
              example: "P.J."
    Naam:
      allOf:
        - $ref: "#/components/schemas/NaamBasis"
        - properties:
            inOnderzoek:
              $ref: "#/components/schemas/AbstractNaamInOnderzoek"
    AbstractNaamInOnderzoek:
      type: object
      description: |
        Geeft aan welke gegevens over de naam in onderzoek zijn. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/in_onderzoek.feature)
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          GbaInOnderzoek: '#/components/schemas/GbaNaamInOnderzoek'
          InOnderzoek: '#/components/schemas/NaamInOnderzoek'
    NaamInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/AbstractNaamInOnderzoek'
        - type: object
          properties:
            geslachtsnaam:
              type: boolean
            voornamen:
              type: boolean
            voorvoegsel:
              type: boolean
            adellijkeTitelPredikaat:
              type: boolean
            datumIngangOnderzoek:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
    GbaNaamInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/AbstractNaamInOnderzoek'
        - type: object
          properties:
            aanduidingGegevensInOnderzoek:
              type: string
              maxLength: 50
            datumIngangOnderzoek:
              $ref: 'datum.yaml#/components/schemas/GbaDatum'
    NaamPersoon:
      allOf:
        - $ref: "#/components/schemas/NaamBasis"
        - properties:
            aanhef:
              type: "string"
              description: |
                            Kun je gebruiken als aanhef in een brief gericht aan persoon.
              example: "Hoogwelgeboren heer"
            aanschrijfwijze:
              type: "string"
              description: |
                            Samengestelde naam die je kunt gebruiken in de communicatie met de persoon.
              example: "H.W. baron van den Aedel"
            regelVoorafgaandAanAanschrijfwijze:
              type: "string"
              description: |
                            Deze regel moet als aparte regel boven de aanschrijfwijze worden geplaatst. Komt alleen voor bij personen met een adellijke titel of predicaat.
              example: "De hoogwelgeboren heer"
            gebruikInLopendeTekst:
              type: "string"
              description: |
                            Naam van persoon die je kunt gebruiken als je in lopende tekst (bijvoorbeeld in een brief) aan persoon refereert.
              example: "baron Van den Aedel"
            aanduidingNaamgebruik:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
            inOnderzoek:
              $ref: "#/components/schemas/AbstractNaamPersoonInOnderzoek"
    AbstractNaamPersoonInOnderzoek:
      type: object
      description: |
        Geeft aan welke gegevens over de naam in onderzoek zijn. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/in_onderzoek.feature)
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          GbaInOnderzoek: '#/components/schemas/GbaNaamPersoonInOnderzoek'
          InOnderzoek: '#/components/schemas/NaamPersoonInOnderzoek'
    NaamPersoonInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/AbstractNaamPersoonInOnderzoek'
        - properties:
            geslachtsnaam:
              type: boolean
            voornamen:
              type: boolean
            voorvoegsel:
              type: boolean
            adellijkeTitelPredikaat:
              type: boolean
            aanduidingNaamgebruik:
              type: boolean
            datumIngangOnderzoek:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
    GbaNaamPersoonInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/AbstractNaamInOnderzoek'
        - type: object
          properties:
            aanduidingGegevensInOnderzoek:
              type: string
              maxLength: 50
            datumIngangOnderzoek:
              $ref: 'datum.yaml#/components/schemas/GbaDatum'
