openapi: 3.0.3
info:
  title: Naam definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Aanhef:
      type: string
      description: |
        Kun je gebruiken als aanhef in een brief gericht aan persoon.
      example: "Hoogwelgeboren heer"
    Aanschrijfwijze:
      type: object
      description: |
        Samengestelde naam en aanspreekvorm die je kunt gebruiken in de communicatie met de persoon.
      properties:
        naam:
          type: string
          example: "H.W. baron van den Aedel"
        aanspreekvorm:
          description: |
            Deze regel moet als aparte regel boven de samengestelde naam worden geplaatst. Komt alleen voor bij personen met een adellijke titel of predicaat.
          type: string
          example: "De hoogwelgeboren heer"
    GebruikInLopendeTekst:
      type: string
      description: |
        Naam van persoon die je kunt gebruiken als je in lopende tekst (bijvoorbeeld in een brief) aan persoon refereert.
      example: "baron Van den Aedel"
    Geslachtsnaam:
      type: string
      maxLength: 200
      description: |
        De achternaam van een persoon.
      example: "Vries"
    VolledigeNaam:
      type: string
      description: |
        Combinatie van predikaat, voornamen, adellijke titel, voorvoegsels en geslachtsnaam, zonder toevoeging van een eventuele partnernaam.
      example: "Pieter Jan de Vries"
    Voorletters: 
      type: string
      description: |
        De voorletters van de persoon, afgeleid van de voornamen.
      example: "P.J."
    Voornamen:
      type: string
      maxLength: 200
      description: |
        De verzameling namen voor de geslachtsnaam, gescheiden door spaties.
    Voorvoegsel:
      type: string
      maxLength: 10
      example: "de"
    AdellijkeTitelPredikaatType:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
        - properties:
            soort:
              type: string
          example:
            value:
              code: "JV"
              omschrijving: "jonkvrouw"
              soort: "predikaat"
    GbaNaamBasis:
      type: object
      properties:
        voornamen:
          $ref: '#/components/schemas/Voornamen'
        voorvoegsel:
          $ref: '#/components/schemas/Voorvoegsel'
        geslachtsnaam:
          $ref: '#/components/schemas/Geslachtsnaam'
        adellijkeTitelPredikaat:
          $ref: '#/components/schemas/AdellijkeTitelPredikaatType'
    GbaNaamGerelateerde:
      allOf:
        - $ref: '#/components/schemas/GbaNaamBasis'
        - type: object
          properties:
            inOnderzoek:
              $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
    GbaNaamPersoon:
      allOf:
        - $ref: '#/components/schemas/GbaNaamBasis'
        - properties:
            aanduidingNaamgebruik:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
            inOnderzoek:
              $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
    NaamBasis:
      type: object
      properties:
        geslachtsnaam:
          $ref: '#/components/schemas/Geslachtsnaam'
        volledigeNaam:
          $ref: '#/components/schemas/VolledigeNaam'
        voorletters:
          $ref: '#/components/schemas/Voorletters'
        voornamen:
          $ref: '#/components/schemas/Voornamen'
        voorvoegsel:
          $ref: '#/components/schemas/Voorvoegsel'
        adellijkeTitelPredikaat:
          $ref: '#/components/schemas/AdellijkeTitelPredikaatType'
    NaamGerelateerde:
      type: object
      properties:
        voornamen:
          $ref: '#/components/schemas/Voornamen'
        voorvoegsel:
          $ref: '#/components/schemas/Voorvoegsel'
        geslachtsnaam:
          $ref: '#/components/schemas/Geslachtsnaam'
        adellijkeTitelPredikaat:
          $ref: '#/components/schemas/AdellijkeTitelPredikaatType'
        voorletters:
          $ref: '#/components/schemas/Voorletters'
        inOnderzoek:
          $ref: '#/components/schemas/NaamInOnderzoek'
    NaamInOnderzoek:
      description: |
        Geeft aan welke gegevens over de naam in onderzoek zijn. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/in_onderzoek.feature)
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            geslachtsnaam:
              type: boolean
            voornamen:
              type: boolean
            voorvoegsel:
              type: boolean
            adellijkeTitelPredikaat:
              type: boolean
    NaamPersoon:
      allOf:
        - $ref: '#/components/schemas/NaamBasis'
        - properties:
            aanhef:
              $ref: '#/components/schemas/Aanhef'
            aanschrijfwijze:
              $ref: '#/components/schemas/Aanschrijfwijze'
            gebruikInLopendeTekst:
              $ref: '#/components/schemas/GebruikInLopendeTekst'
            aanduidingNaamgebruik:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
            inOnderzoek:
              $ref: '#/components/schemas/NaamPersoonInOnderzoek'
    NaamPersoonInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/NaamInOnderzoek'
        - type: object
          properties:
            aanduidingNaamgebruik:
              type: boolean
