openapi: 3.0.3
info:
  title: Naam definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Voorletters:
      type: string
      pattern: ^[a-zA-Z0-9À-ž \.]{1,40}$
      description: |
        De voorletters van de persoon, afgeleid van de voornamen.
      example: "P.J."
    NaamBasis:
      type: object
      properties:
        voornamen:
          $ref: 'brp/naam/voornamen-v1.yaml#/components/schemas/Voornamen'
        adellijkeTitelPredicaat:
          $ref: 'brp/naam/adellijke-titel-predicaat-v1.yaml#/components/schemas/AdellijkeTitelPredicaatType'
        voorvoegsel:
          $ref: 'brp/naam/voorvoegsel-v1.yaml#/components/schemas/Voorvoegsel'
        geslachtsnaam:
          $ref: 'brp/naam/geslachtsnaam-v1.yaml#/components/schemas/Geslachtsnaam'
        voorletters:
          $ref: '#/components/schemas/Voorletters'
        volledigeNaam:
          $ref: 'brp-api/naam/volledige-naam-v1.yaml#/components/schemas/VolledigeNaam'
    NaamGerelateerde:
      type: object
      properties:
        voornamen:
          $ref: 'brp/naam/voornamen-v1.yaml#/components/schemas/Voornamen'
        adellijkeTitelPredicaat:
          $ref: 'brp/naam/adellijke-titel-predicaat-v1.yaml#/components/schemas/AdellijkeTitelPredicaatType'
        voorvoegsel:
          $ref: 'brp/naam/voorvoegsel-v1.yaml#/components/schemas/Voorvoegsel'
        geslachtsnaam:
          $ref: 'brp/naam/geslachtsnaam-v1.yaml#/components/schemas/Geslachtsnaam'
        voorletters:
          $ref: '#/components/schemas/Voorletters'
        inOnderzoek:
          $ref: '#/components/schemas/NaamInOnderzoek'
    NaamInOnderzoek:
      description: |
        Geeft aan welke gegevens over de naam in onderzoek zijn.
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            voornamen:
              type: boolean
            adellijkeTitelPredicaat:
              type: boolean
            voorvoegsel:
              type: boolean
            geslachtsnaam:
              type: boolean
            voorletters:
              type: boolean
    NaamPersoon:
      description: |
        Gegevens over de naam van de persoon.
        * **aanduidingNaamgebruik** - wordt gevuld met waarden voor 'Naamgebruik' in 'tabelwaarden.csv'.
      allOf:
        - $ref: '#/components/schemas/NaamBasis'
        - properties:
            aanduidingNaamgebruik:
              $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
            inOnderzoek:
              $ref: '#/components/schemas/NaamPersoonInOnderzoek'
    NaamPersoonBeperkt:
      description: |
        Gegevens over de naam van de persoon.
      allOf:
        - $ref: '#/components/schemas/NaamBasis'
        - properties:
            inOnderzoek:
              $ref: '#/components/schemas/NaamPersoonInOnderzoekBeperkt'
    NaamPersoonInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/NaamInOnderzoek'
        - type: object
          properties:
            aanduidingNaamgebruik:
              type: boolean
            volledigeNaam:
              type: boolean
    NaamPersoonInOnderzoekBeperkt:
      allOf:
        - $ref: '#/components/schemas/NaamInOnderzoek'
        - type: object
          properties:
            volledigeNaam:
              type: boolean
