openapi: 3.0.3
info:
  title: Naam definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Aanhef:
      type: string
      description: |
        Kun je gebruiken als aanhef in een brief gericht aan persoon.
      example: "Hoogwelgeboren heer"
    Aanschrijfwijze:
      type: string
      description: |
        Samengestelde naam die je kunt gebruiken in de communicatie met de persoon.
      example: "H.W. baron van den Aedel"
    GebruikInLopendeTekst:
      type: string
      description: |
        Naam van persoon die je kunt gebruiken als je in lopende tekst (bijvoorbeeld in een brief) aan persoon refereert.
      example: "baron Van den Aedel"
    Geslachtsnaam:
      type: string
      maxLength: 200
      description: |
        De achternaam van een persoon.
      example: "Vries"
    RegelVoorafgaandAanAanschrijfwijze:
      type: string
      description: |
        Deze regel moet als aparte regel boven de aanschrijfwijze worden geplaatst. Komt alleen voor bij personen met een adellijke titel of predicaat.
      example: "De hoogwelgeboren heer"
    Voorletters:
      type: string
      description: |
        De voorletters van de persoon, afgeleid van de voornamen.
      example: "P.J."
    Voornamen:
      type: string
      maxLength: 200
      description: |
        De verzameling namen voor de geslachtsnaam, gescheiden door spaties.
    Voorvoegsel:
      type: string
      maxLength: 10
      example: "de"
    AbstractNaamBasis:
      type: object
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          GbaNaam: '#/components/schemas/GbaNaamBasis'
          Naam: '#/components/schemas/NaamBasis'
    AbstractNaam:
      type: object
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          GbaNaam: '#/components/schemas/GbaNaam'
          Naam: '#/components/schemas/Naam'
    GbaNaamBasis:
      type: object
      properties:
        voornamen:
          $ref: '#/components/schemas/Voornamen'
        voorvoegsel:
          $ref: '#/components/schemas/Voorvoegsel'
        geslachtsnaam:
          $ref: '#/components/schemas/Geslachtsnaam'
        adellijkeTitelPredikaat:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
    NaamBasis:
      allOf:
        - $ref: '#/components/schemas/GbaNaamBasis'
        - type: object
          properties:
            voorletters:
              $ref: '#/components/schemas/Voorletters'
    Naam:
      allOf:
        - $ref: '#/components/schemas/AbstractNaam'
        - properties:
            voornamen:
              $ref: '#/components/schemas/Voornamen'
            voorvoegsel:
              $ref: '#/components/schemas/Voorvoegsel'
            geslachtsnaam:
              $ref: '#/components/schemas/Geslachtsnaam'
            adellijkeTitelPredikaat:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
            voorletters:
              $ref: '#/components/schemas/Voorletters'
            inOnderzoek:
              $ref: '#/components/schemas/NaamInOnderzoek'
    GbaNaam:
      allOf:
        - $ref: '#/components/schemas/AbstractNaam'
        - properties:
            voornamen:
              $ref: '#/components/schemas/Voornamen'
            voorvoegsel:
              $ref: '#/components/schemas/Voorvoegsel'
            geslachtsnaam:
              $ref: '#/components/schemas/Geslachtsnaam'
            adellijkeTitelPredikaat:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
            inOnderzoek:
              $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
    NaamInOnderzoek:
      description: |
        Geeft aan welke gegevens over de naam in onderzoek zijn. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/in_onderzoek.feature)
      type: object
      properties:
        geslachtsnaam:
          type: boolean
        voornamen:
          type: boolean
        voorvoegsel:
          type: boolean
        adellijkeTitelPredikaat:
          type: boolean
        datumIngangOnderzoek:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
    NaamPersoon:
      allOf:
        - $ref: '#/components/schemas/NaamBasis'
        - properties:
            aanhef:
              $ref: '#/components/schemas/Aanhef'
            aanschrijfwijze:
              $ref: '#/components/schemas/Aanschrijfwijze'
            regelVoorafgaandAanAanschrijfwijze:
              $ref: '#/components/schemas/RegelVoorafgaandAanAanschrijfwijze'
            gebruikInLopendeTekst:
              $ref: '#/components/schemas/GebruikInLopendeTekst'
            aanduidingNaamgebruik:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
            inOnderzoek:
              $ref: '#/components/schemas/AbstractNaamPersoonInOnderzoek'
    AbstractNaamPersoonInOnderzoek:
      type: object
      description: |
        Geeft aan welke gegevens over de naam in onderzoek zijn. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/in_onderzoek.feature)
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          GbaInOnderzoek: '#/components/schemas/GbaNaamPersoonInOnderzoek'
          InOnderzoek: '#/components/schemas/NaamPersoonInOnderzoek'
    NaamPersoonInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/AbstractNaamPersoonInOnderzoek'
        - properties:
            geslachtsnaam:
              type: boolean
            voornamen:
              type: boolean
            voorvoegsel:
              type: boolean
            adellijkeTitelPredikaat:
              type: boolean
            aanduidingNaamgebruik:
              type: boolean
            datumIngangOnderzoek:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
    GbaNaamPersoonInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/AbstractNaamPersoonInOnderzoek'
        - $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
