openapi: 3.0.3
info:
  title: Ouder definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Naam:
      allOf:
        - $ref: "#/components/schemas/NaamBasis"
        - properties:
            inOnderzoek:
              $ref: "#/components/schemas/NaamInOnderzoek"
    NaamBasis:
      type: "object"
      properties:
        geslachtsnaam:
          type: "string"
          description: |
                        De achternaam van een persoon.
          example: "Vries"
        voorletters:
          type: "string"
          description: |
                        De voorletters van de persoon, afgeleid van de voornamen.
          example: "P.J."
        voornamen:
          type: "string"
          description: |
                        De verzameling namen voor de geslachtsnaam, gescheiden door spaties.
          example: "Pieter Jan"
        voorvoegsel:
          type: "string"
          example: "de"
        adellijkeTitelPredikaat:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel"
    NaamInOnderzoek:
      type: "object"
      description: |
                    Geeft aan welke gegevens over de naam in onderzoek zijn. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/in_onderzoek.feature)
      properties:
        geslachtsnaam:
          type: boolean
        voornamen:
          type: boolean
        voorvoegsel:
          type: boolean
        adellijkeTitelPredikaat:
          type: boolean
        datumIngangOnderzoek:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/DatumOnvolledig"
    NaamPersoon:
      allOf:
        - $ref: "#/components/schemas/NaamBasis"
        - properties:
            aanhef:
              type: "string"
              description: |
                            Kun je gebruiken als aanhef in een brief gericht aan persoon.
              example: "Hoogwelgeboren heer"
            aanschrijfwijze:
              type: "string"
              description: |
                            Samengestelde naam die je kunt gebruiken in de communicatie met de persoon.
              example: "H.W. baron van den Aedel"
            regelVoorafgaandAanAanschrijfwijze:
              type: "string"
              description: |
                            Deze regel moet als aparte regel boven de aanschrijfwijze worden geplaatst. Komt alleen voor bij personen met een adellijke titel of predicaat.
              example: "De hoogwelgeboren heer"
            gebruikInLopendeTekst:
              type: "string"
              description: |
                            Naam van persoon die je kunt gebruiken als je in lopende tekst (bijvoorbeeld in een brief) aan persoon refereert.
              example: "baron Van den Aedel"
            aanduidingNaamgebruik:
              $ref: "enum.yaml#/components/schemas/Naamgebruik_enum"
            inOnderzoek:
              $ref: "#/components/schemas/NaamPersoonInOnderzoek"
    NaamPersoonInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/NaamInOnderzoek'
        - properties:
            aanduidingNaamgebruik:
              type: boolean
