openapi: 3.0.3
info:
  title: Nationaliteit definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    AbstractNationaliteit:
      type: object
      required:
        - type
      properties:
        type:
          type: string
        redenOpname:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
      discriminator:
        propertyName: type
        mapping:
          GbaNationaliteit: '#/components/schemas/GbaNationaliteit'
          Nationaliteit: '#/components/schemas/Nationaliteit'
          BehandeldAlsNederlander: '#/components/schemas/BehandeldAlsNederlander'
          VastgesteldNietNederlander: '#/components/schemas/VastgesteldNietNederlander'
    Nationaliteit:
      description: |
        * **redenOpname** : De reden op grond waarvan de persoon de nationaliteit gekregen heeft.
      allOf:
        - $ref: '#/components/schemas/AbstractNationaliteit'
        - type: object
          properties:
            datumIngangGeldigheid:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
            nationaliteit:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
            inOnderzoek:
              $ref: '#/components/schemas/NationaliteitInOnderzoek'
    BehandeldAlsNederlander:
      allOf:
        - $ref: '#/components/schemas/AbstractNationaliteit'
        - type: object
          properties:
            datumIngangGeldigheid:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
    VastgesteldNietNederlander:
      allOf:
        - $ref: '#/components/schemas/AbstractNationaliteit'
        - type: object
          properties:
            datumIngangGeldigheid:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
    GbaNationaliteit:
      description: |
        Bij de LO GBA versie kunnen datums, bijv datumIngangGeldigheid de LoGbaDatum refereren
        Het hoeft niet van AbstractDatum af te leiden omdat het nooit een andere type kan zijn
      allOf:
        - $ref: '#/components/schemas/AbstractNationaliteit'
        - type: object
          properties:
            datumIngangGeldigheid:
              $ref: 'datum.yaml#/components/schemas/GbaDatum'
            nationaliteit:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
            aanduidingBijzonderNederlandschap:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
            inOnderzoek:
                $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
    NationaliteitInOnderzoek:
      type: object
      description: |
        Geeft aan welke gegevens over de nationaliteit in onderzoek zijn. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/in_onderzoek.feature)
      properties:
        aanduidingBijzonderNederlanderschap:
          type: boolean
        nationaliteit:
          type: boolean
        redenOpname:
          type: boolean
        datumIngangOnderzoek:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
