openapi: 3.0.3
info:
  title: Ouder definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Nationaliteit:
      type: "object"
      description: |
                    * **redenOpname** : De reden op grond waarvan de persoon de nationaliteit gekregen heeft.
      properties:
        aanduidingBijzonderNederlanderschap:
          $ref: "enum.yaml#/components/schemas/AanduidingBijzonderNederlanderschap_enum"
        datumIngangGeldigheid:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/DatumOnvolledig"
        nationaliteit:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel"
        redenOpname:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel"
        inOnderzoek:
          $ref: "#/components/schemas/NationaliteitInOnderzoek"
    NationaliteitInOnderzoek:
      type: "object"
      description: |
                    Geeft aan welke gegevens over de nationaliteit in onderzoek zijn. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/in_onderzoek.feature)
      properties:
        aanduidingBijzonderNederlanderschap:
          type: boolean
        nationaliteit:
          type: boolean
        redenOpname:
          type: boolean
        datumIngangOnderzoek:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/DatumOnvolledig"
