openapi: 3.0.3
info:
  title: Nationaliteit definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    AbstractNationaliteit:
      type: object
      description: |
        * **redenOpname** - De reden op grond waarvan de persoon de nationaliteit gekregen heeft. Wordt gevuld met waarden uit de landelijke tabel 'Reden opnemen/beëindigen nationaliteit'.
      required:
        - type
      properties:
        type:
          type: string
        redenOpname:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
      discriminator:
        propertyName: type
        mapping:
          Nationaliteit: '#/components/schemas/NationaliteitBekend'
          BehandeldAlsNederlander: '#/components/schemas/BehandeldAlsNederlander'
          VastgesteldNietNederlander: '#/components/schemas/VastgesteldNietNederlander'
          Staatloos: '#/components/schemas/Staatloos'
          NationaliteitOnbekend: '#/components/schemas/NationaliteitOnbekend'
    NationaliteitBekend:
      description: |
        * **nationaliteit** - wordt gevuld met waarden uit de landelijke tabel 'Nationaliteiten'.
      allOf:
        - $ref: '#/components/schemas/AbstractNationaliteit'
        - type: object
          properties:
            datumIngangGeldigheid:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
            nationaliteit:
              $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
            inOnderzoek:
              $ref: '#/components/schemas/NationaliteitBekendInOnderzoek'
    BehandeldAlsNederlander:
      allOf:
        - $ref: '#/components/schemas/AbstractNationaliteit'
        - type: object
          properties:
            datumIngangGeldigheid:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
            inOnderzoek:
              $ref: '#/components/schemas/BijzonderNederlanderschapInOnderzoek'
    VastgesteldNietNederlander:
      allOf:
        - $ref: '#/components/schemas/AbstractNationaliteit'
        - type: object
          properties:
            datumIngangGeldigheid:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
            inOnderzoek:
              $ref: '#/components/schemas/BijzonderNederlanderschapInOnderzoek'
    Staatloos:
      description: |
        * **redenOpname** : De reden op grond waarvan de persoon de nationaliteit gekregen heeft.
      allOf:
        - $ref: '#/components/schemas/AbstractNationaliteit'
        - type: object
          properties:
            datumIngangGeldigheid:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
            inOnderzoek:
              $ref: '#/components/schemas/StaatloosInOnderzoek'
    NationaliteitOnbekend:
      allOf:
        - $ref: '#/components/schemas/AbstractNationaliteit'
        - type: object
          properties:
            datumIngangGeldigheid:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
            inOnderzoek:
              $ref: '#/components/schemas/NationaliteitOnbekendInOnderzoek'
    GbaNationaliteit:
      type: object
      properties:
        aanduidingBijzonderNederlanderschap:
          type: string
          pattern: ^(B|V)$
        datumIngangGeldigheid:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
        nationaliteit:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        redenOpname:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        inOnderzoek:
            $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
    BijzonderNederlanderschapInOnderzoek:
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            type:
              type: boolean
            redenOpname:
              type: boolean
    NationaliteitBekendInOnderzoek:
      description: |
        Geeft aan welke gegevens over de nationaliteit in onderzoek zijn.
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            type:
              type: boolean
            nationaliteit:
              type: boolean
            redenOpname:
              type: boolean
    StaatloosInOnderzoek:
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            type:
              type: boolean
            redenOpname:
              type: boolean
    NationaliteitOnbekendInOnderzoek:
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            type:
              type: boolean
            redenOpname:
              type: boolean
