openapi: 3.0.3
info:
  title: Ouder definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    OpschortingBijhoudingBasis:
      type: "object"
      properties:
        reden:
          $ref: "enum.yaml#/components/schemas/RedenOpschortingBijhouding_enum"
    OpschortingBijhouding:
      allOf:
        - $ref: '#/components/schemas/OpschortingBijhoudingBasis'
        - type: "object"
          description: |
                        * **datum**: de datum waarop de bijhouding van de persoonsgegevens is gestaakt.
          properties:
            datum:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/DatumOnvolledig"
