openapi: 3.0.3
info:
  title: OpschortingBijhouding definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    OpschortingBijhoudingBasis:
      type: object
      description: |
        * **reden** - wordt gevuld op basis van de waarden die voorkomen in de tabel 'redenopschortingbijhouding' uit de Haal-Centraal-BRP-tabellen-bevragen API.
      properties:
        reden:
          allOf:
          - $ref: 'common.yaml#/components/schemas/Waardetabel'
          - description: Voor de enumeratie van de geslachtsaanduiding wordt de tabel met identificatie "redenopschortingbijhouding" opgehaald m.b.v. "BRP tabellen bevragen"-API.
    GbaOpschortingBijhouding:
      allOf:
        - $ref: '#/components/schemas/OpschortingBijhoudingBasis'
        - type: object
          description: |
            * **datum**: de datum waarop de bijhouding van de persoonsgegevens is gestaakt.
          properties:
            datum:
              $ref: 'datum.yaml#/components/schemas/GbaDatum'
    OpschortingBijhouding:
      allOf:
        - $ref: '#/components/schemas/OpschortingBijhoudingBasis'
        - type: object
          description: |
            * **datum**: de datum waarop de bijhouding van de persoonsgegevens is gestaakt.
          properties:
            datum:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
