openapi: 3.0.3
info:
  title: OpschortingBijhouding definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    OpschortingBijhoudingBasis:
      type: object
      properties:
        reden:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
    OpschortingBijhouding:
      allOf:
        - $ref: '#/components/schemas/OpschortingBijhoudingBasis'
        - type: object
          description: |
            * **datum**: de datum waarop de bijhouding van de persoonsgegevens is gestaakt.
          properties:
            datum:
              $ref: 'brp-api/datum/datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
