openapi: 3.0.3
info:
  title: Ouder definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    OuderAanduiding:
      type: string
      pattern: ^[1|2]$
      example: "1"
    Ouder:
      description: |
        Gegevens over de ouder van de persoon.
        * **datumIngangFamilierechtelijkeBetrekking** - De datum waarop de familierechtelijke betrekking is ontstaan.
        * **geslacht** - wordt gevuld met waarden voor 'Geslacht' in 'tabelwaarden.csv'.
      type: object
      properties:
        burgerservicenummer:
          $ref: 'brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        geslacht:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        ouderAanduiding:
          $ref: '#/components/schemas/OuderAanduiding'
        datumIngangFamilierechtelijkeBetrekking:
          $ref: 'brp-api/datum/datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
        naam:
          $ref: 'naam.yaml#/components/schemas/NaamGerelateerde'
        inOnderzoek:
          $ref: '#/components/schemas/OuderInOnderzoek'
        geboorte:
          $ref: 'geboorte.yaml#/components/schemas/Geboorte'
    OuderInOnderzoek:
      description: |
        Geeft aan welke gegevens van de de ouder in onderzoek zijn.
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            burgerservicenummer:
              type: boolean
            datumIngangFamilierechtelijkeBetrekking:
              type: boolean
            geslacht:
              type: boolean
