openapi: 3.0.3
info:
  title: Ouder definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Ouder:
      type: object
      description: |
        Gegevens over de ouder van de persoon.
        * **datumIngangFamilierechtelijkeBetrekking** - De datum waarop de familierechtelijke betrekking is ontstaan.
      properties:
        identificatie:
          $ref: 'ingeschrevenpersoon.yaml#/components/schemas/PersoonIdentificatie'
        burgerservicenummer:
          $ref: 'ingeschrevenpersoon.yaml#/components/schemas/Burgerservicenummer'
        geslachtsaanduiding:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
        ouderAanduiding:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel'
        datumIngangFamilierechtelijkeBetrekking:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
        naam:
          $ref: 'naam.yaml#/components/schemas/Naam'
        inOnderzoek:
          $ref: '#/components/schemas/AbstractOuderInOnderzoek'
        geboorte:
          $ref: 'geboorte.yaml#/components/schemas/Geboorte'
    AbstractOuderInOnderzoek:
      type: object
      description: |
        Geeft aan welke gegevens van de de ouder in onderzoek zijn. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/in_onderzoek.feature)
      required:
        - type
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          GbaInOnderzoek: '#/components/schemas/GbaOuderInOnderzoek'
          InOnderzoek: '#/components/schemas/OuderInOnderzoek'
    OuderInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/AbstractOuderInOnderzoek'
        - type: object
          properties:
            burgerservicenummer:
              type: boolean
            datumIngangFamilierechtelijkeBetrekking:
              type: boolean
            geslachtsaanduiding:
              type: boolean
            datumIngangOnderzoek:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
    GbaOuderInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/AbstractOuderInOnderzoek'
        - $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
