openapi: 3.0.3
info:
  title: Ouder definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    OuderAanduiding:
      type: string
      pattern: ^[1|2]$
      example: "1"
    GbaOuder:
      type: object
      description: |
        Gegevens over de ouder van de persoon.
        * **datumIngangFamilierechtelijkeBetrekking** - De datum waarop de familierechtelijke betrekking is ontstaan.
      properties:
        burgerservicenummer:
          $ref: 'persoon.yaml#/components/schemas/Burgerservicenummer'
        geslacht:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        ouderAanduiding:
          $ref: '#/components/schemas/OuderAanduiding'
        datumIngangFamilierechtelijkeBetrekking:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
        naam:
          $ref: 'naam.yaml#/components/schemas/GbaNaamBasis'
        inOnderzoek:
          $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
        geboorte:
          $ref: 'geboorte.yaml#/components/schemas/GbaGeboorte'
    Ouder:
      description: |
        Gegevens over de ouder van de persoon.
        * **datumIngangFamilierechtelijkeBetrekking** - De datum waarop de familierechtelijke betrekking is ontstaan.
        * **geslacht** - wordt gevuld op basis van de waarden die voorkomen in de tabel 'geslacht' uit de Haal-Centraal-BRP-tabellen-bevragen API.
      type: object
      properties:
        burgerservicenummer:
          $ref: 'persoon.yaml#/components/schemas/Burgerservicenummer'
        geslacht:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        ouderAanduiding:
          $ref: '#/components/schemas/OuderAanduiding'
        datumIngangFamilierechtelijkeBetrekking:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
        naam:
          $ref: 'naam.yaml#/components/schemas/NaamGerelateerde'
        inOnderzoek:
          $ref: '#/components/schemas/OuderInOnderzoek'
        geboorte:
          $ref: 'geboorte.yaml#/components/schemas/Geboorte'
    OuderInOnderzoek:
      description: |
        Geeft aan welke gegevens van de de ouder in onderzoek zijn.
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            burgerservicenummer:
              type: boolean
            datumIngangFamilierechtelijkeBetrekking:
              type: boolean
            geslacht:
              type: boolean
