openapi: 3.0.3
info:
  title: Ouder definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Ouder:
      type: "object"
      description: |
                    Gegevens over de ouder van de persoon.
                    * **datumIngangFamilierechtelijkeBetrekking** - De datum waarop de familierechtelijke betrekking is ontstaan.
      properties:
        burgerservicenummer:
          type: "string"
          example: "555555021"
        geslachtsaanduiding:
          $ref: "enum.yaml#/components/schemas/Geslacht_enum"
        ouderAanduiding:
          $ref: "enum.yaml#/components/schemas/OuderAanduiding_enum"
        datumIngangFamilierechtelijkeBetrekking:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
        naam:
          $ref: "naam.yaml#/components/schemas/Naam"
        inOnderzoek:
          $ref: "#/components/schemas/AbstractOuderInOnderzoek"
        geboorte:
          $ref: "geboorte.yaml#/components/schemas/Geboorte"
    AbstractOuderInOnderzoek:
      type: object
      description: |
        Geeft aan welke gegevens van de de ouder in onderzoek zijn. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/in_onderzoek.feature)
      properties:
        type:
          type: string
      discriminator:
        propertyName: type
        mapping:
          GbaInOnderzoek: '#/components/schemas/GbaOuderInOnderzoek'
          InOnderzoek: '#/components/schemas/OuderInOnderzoek'
    OuderInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/AbstractOuderInOnderzoek'
        - type: object
          properties:
            burgerservicenummer:
              type: boolean
            datumIngangFamilierechtelijkeBetrekking:
              type: boolean
            geslachtsaanduiding:
              type: boolean
            datumIngangOnderzoek:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
    GbaOuderInOnderzoek:
      allOf:
        - $ref: '#/components/schemas/AbstractOuderInOnderzoek'
        - type: object
          properties:
            aanduidingGegevensInOnderzoek:
              type: string
              maxLength: 50
            datumIngangOnderzoek:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
