openapi: 3.0.3
info:
  title: Overlijden definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Overlijden:
      description: |
        Gegevens over het overlijden.
        * **datum** - datum waarop de persoon is overleden.
        * **land** - land waar de persoon is overleden. Wordt gevuld met waarden uit de landelijke tabel 'Landen'.
        * **plaats** - gemeente waar de persoon is overleden. Wordt gevuld met waarden uit de landelijke tabel "Gemeenten".
      type: object
      properties:
        datum:
          $ref: 'brp-api/datum/datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
        land:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        plaats:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        inOnderzoek:
          $ref: '#/components/schemas/OverlijdenInOnderzoek'
    OverlijdenInOnderzoek:
      description: |
        Geeft aan welke gegevens over het overlijden van de persoon in onderzoek zijn.
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            datum:
              type: boolean
            land:
              type: boolean
            plaats:
              type: boolean
