openapi: 3.0.3
info:
  title: Overlijden definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    GbaOverlijden:
        type: object
        properties:
          datum:
            $ref: 'datum.yaml#/components/schemas/GbaDatum'
          land:
            $ref: 'common.yaml#/components/schemas/Waardetabel'
          plaats:
            $ref: 'common.yaml#/components/schemas/Waardetabel'
          inOnderzoek:
            $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
    Overlijden:
      description: |
        Gegevens over het overlijden.
        * **datum** - datum waarop de persoon is overleden.
        * **land** - land waar de persoon is overleden. Wordt gevuld met waarden uit de tabel 'Landen' uit de Haal-Centraal-BRP-tabellen-bevragen API.
        * **plaats** - gemeente waar de persoon is overleden. Wordt gevuld met waarden uit de tabel "Gemeenten" voor een gemeente in Nederland of de omschrijving van een buitenlandse plaats.
        type: object
        properties:
          datum:
            $ref: 'datum.yaml#/components/schemas/AbstractDatum'
          land:
            $ref: 'common.yaml#/components/schemas/Waardetabel'
          plaats:
            $ref: 'common.yaml#/components/schemas/Waardetabel'
          inOnderzoek:
            $ref: '#/components/schemas/OverlijdenInOnderzoek'
    OverlijdenInOnderzoek:
      description: |
        Geeft aan welke gegevens over het overlijden van de persoon in onderzoek zijn.
        Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/in_onderzoek.feature)
      allOf:
        - $ref: 'persoon.yaml#/components/schemas/InOnderzoek'
        - type: object
          properties:
            datum:
              type: boolean
            land:
              type: boolean
            plaats:
              type: boolean
