openapi: 3.1.0
info:
  title: Persoon definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    PersoonBeperkt:
      type: object
      properties:
        burgerservicenummer:
          $ref: 'brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        geboorte:
          $ref: 'brp-api/geboorte/geboorte-beperkt-v1.yaml#/components/schemas/GeboorteBeperkt'
        geheimhoudingPersoonsgegevens:
          $ref: 'brp-api/geheim/geheimhouding-persoonsgegevens-v1.yaml#/components/schemas/GeheimhoudingPersoonsgegevens'
        geslacht:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        inOnderzoek:
          $ref: '#/components/schemas/PersoonInOnderzoekBeperkt'
        leeftijd:
          $ref: 'brp-api/geboorte/leeftijd-v1.yaml#/components/schemas/Leeftijd'
        naam:
          $ref: 'brp-api/naam/naam-persoon-beperkt-v1.yaml#/components/schemas/NaamPersoonBeperkt'
        opschortingBijhouding:
          $ref: 'brp-api/opschorting-bijhouding/opschorting-bijhouding-v1.yaml#/components/schemas/OpschortingBijhouding'
        adressering:
          $ref: 'brp-api/adressering/adressering-beperkt-v1.yaml#/components/schemas/AdresseringBeperkt'
        rni:
          type: array
          items:
            $ref: 'brp/rni/rni-deelnemer-v1.yaml#/components/schemas/RniDeelnemer'
        verificatie:
          $ref: 'brp-api/verificatie/verificatie-v1.yaml#/components/schemas/Verificatie'
    Persoon:
      type: object
      properties:
        aNummer:
          $ref: 'brp/identificatienummers/anummer-v1.yaml#/components/schemas/ANummer'
        burgerservicenummer:
          $ref: 'brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        datumEersteInschrijvingGBA:
          $ref: 'brp-api/datum/datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
        geheimhoudingPersoonsgegevens:
          $ref: 'brp-api/geheim/geheimhouding-persoonsgegevens-v1.yaml#/components/schemas/GeheimhoudingPersoonsgegevens'
        geslacht:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        inOnderzoek:
          $ref: '#/components/schemas/PersoonInOnderzoek'
        uitsluitingKiesrecht:
          $ref: 'brp-api/kiesrecht/uitsluiting-kiesrecht-v1.yaml#/components/schemas/UitsluitingKiesrecht'
        europeesKiesrecht:
          $ref: 'brp-api/kiesrecht/europees-kiesrecht-v1.yaml#/components/schemas/EuropeesKiesrecht'
        leeftijd:
          $ref: 'brp-api/geboorte/leeftijd-v1.yaml#/components/schemas/Leeftijd'
        naam:
          $ref: 'brp-api/naam/naam-persoon-v1.yaml#/components/schemas/NaamPersoon'
        nationaliteiten:
          type: array
          items:
            $ref: 'brp-api/nationaliteit/nationaliteit-polymorf-v1.yaml#/components/schemas/AbstractNationaliteit'
        geboorte:
          $ref: 'brp-api/geboorte/geboorte-v1.yaml#/components/schemas/Geboorte'
        opschortingBijhouding:
          $ref: 'brp-api/opschorting-bijhouding/opschorting-bijhouding-v1.yaml#/components/schemas/OpschortingBijhouding'
        overlijden:
          $ref: 'brp-api/overlijden/overlijden-v1.yaml#/components/schemas/Overlijden'
        verblijfplaats:
          $ref: 'brp-api/verblijfplaats/verblijfplaats-polymorf-v1.yaml#/components/schemas/AbstractVerblijfplaats'
        immigratie:
          $ref: 'brp-api/immigratie/immigratie-v1.yaml#/components/schemas/Immigratie'
        gemeenteVanInschrijving:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
        datumInschrijvingInGemeente:
          $ref: 'brp-api/datum/datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
        adressering:
          $ref: 'brp-api/adressering/adressering-v1.yaml#/components/schemas/Adressering'
        indicatieCurateleRegister:
          $ref: 'brp/indicatie-curatele-register-v1.yaml#/components/schemas/IndicatieCurateleRegister'
        indicatieGezagMinderjarige:
          $ref: 'brp/waardetabel-v1.yaml#/components/schemas/Waardetabel'
          deprecated: true
        gezag:
          $ref: 'brp-api/gezag/gezagsrelatie-v2.yaml#/components/schemas/Gezag'
        verblijfstitel:
          $ref: 'brp-api/verblijfstitel/verblijfstitel-v1.yaml#/components/schemas/Verblijfstitel'
        kinderen:
          type: array
          items:
            $ref: 'brp-api/kind/kind-v1.yaml#/components/schemas/Kind'
        ouders:
          type: array
          items:
            $ref: 'brp-api/ouder/ouder-v1.yaml#/components/schemas/Ouder'
        partners:
          type: array
          items:
            $ref: 'brp-api/partner/partner-v1.yaml#/components/schemas/Partner'
        rni:
          type: array
          items:
            $ref: 'brp/rni/rni-deelnemer-v1.yaml#/components/schemas/RniDeelnemer'
        verificatie:
          $ref: 'brp-api/verificatie/verificatie-v1.yaml#/components/schemas/Verificatie'
    PersoonInOnderzoek:
      description: |
        Geeft aan welke gegevens van de persoon in onderzoek zijn.
        * **datumIngangOnderzoekPersoon - Deze datum heeft betrekking op burgerservicenummer, geslacht en leeftijd
        * **datumIngangOnderzoekGemeente - Deze datum heeft betrekking op gemeenteVanInschrijving en datumInschrijvingInGemeente
        * **datumIngangOnderzoekGezag - Deze datumingang heeft betrekking op indicatieCurateleRegister en indicatieGezagMinderjarige
      type: object
      properties:
        datumIngangOnderzoekPersoon:
          $ref: 'brp-api/datum/datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
        datumIngangOnderzoekGemeente:
          $ref: 'brp-api/datum/datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
        datumIngangOnderzoekGezag:
          $ref: 'brp-api/datum/datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
        burgerservicenummer:
          type: boolean
        geslacht:
          type: boolean
        leeftijd:
          type: boolean
        gemeenteVanInschrijving:
          type: boolean
        datumInschrijvingInGemeente:
          type: boolean
        indicatieCurateleRegister:
          type: boolean
        indicatieGezagMinderjarige:
          type: boolean
          deprecated: true
    PersoonInOnderzoekBeperkt:
      description: |
        Geeft aan welke gegevens van de persoon in onderzoek zijn.
        * **datumIngangOnderzoekPersoon - Deze datum heeft betrekking op burgerservicenummer, geslacht en leeftijd
      type: object
      properties:
        datumIngangOnderzoekPersoon:
          $ref: 'brp-api/datum/datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
        burgerservicenummer:
          type: boolean
        geslacht:
          type: boolean
        leeftijd:
          type: boolean
    InOnderzoek:
      type: object
      properties:
        datumIngangOnderzoek:
          $ref: 'brp-api/datum/datum-polymorf-v1.yaml#/components/schemas/AbstractDatum'
