openapi: 3.0.3
info:
  title: Persoon definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    ANummer:
      description: |
        Het A-nummer van de persoon
      type: string
      pattern: ^[0-9]{10}$
    Burgerservicenummer:
      type: string
      pattern: ^[0-9]{9}$
      example: "555555021"
    GbaGeheimhoudingPersoonsgegevens:
      type: integer
    GeheimhoudingPersoonsgegevens:
      description: |
        Gegevens mogen niet worden verstrekt aan derden / maatschappelijke instellingen.
      type: boolean
    GemeenteVanInschrijving:
      description: |
        Een code die aangeeft in welke gemeente de persoon woont, of de laatste gemeente waar de persoon heeft gewoond, of de gemeente waar de persoon voor het eerst is ingeschreven.
      type: string
      pattern: ^[0-9]{4}$
      example: "0518"
    IndicatieCurateleRegister:
      type: boolean
      description: |
        Geeft aan dat de persoon onder curatele is gesteld.
      example: true
    Leeftijd:
      type: integer
      description: |
        Leeftijd in jaren op het moment van bevragen.
      example: 34
      minimum: 0
      maximum: 150
    OmschrijvingVerdrag:
      type: string
      description: |
        Omschrijving van het verdrag op basis waarvan een zusterorganisatie in het buitenland de gegevens bij de RNI-deelnemer heeft aangeleverd.
      pattern: ^[a-zA-Z0-9À-ž \.\-\']{1,50}$
    Categorie:
      type: string
      description: Naam van categorie waarop de RNI-deelnemer gegevens heeft aangeleverd
      pattern: ^[a-zA-Z0-9À-ž \.\-\'\/]{1,40}$
      example: Verblijfplaats
    OmschrijvingVerificatie:
      type: string
      description: |
        Omschrijving van de verificatie van de rni-gegevens
      pattern: ^[a-zA-Z0-9À-ž \.\-\']{1,50}$
    GbaVerificatie:
      type: object
      properties:
        datum:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
        omschrijving:
          $ref: '#/components/schemas/OmschrijvingVerificatie'
    Verificatie:
      type: object
      properties:
        datum:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
        omschrijving:
          $ref: '#/components/schemas/OmschrijvingVerificatie'
    RniDeelnemer:
      type: object
      description: Gegevens over de RNI-deelnemer die de gegevens in de betrokken categorie heeft aangeleverd.
      properties:
        deelnemer:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        omschrijvingVerdrag:
          $ref: '#/components/schemas/OmschrijvingVerdrag'
        categorie:
          $ref: '#/components/schemas/Categorie'
    GbaPersoonBeperkt:
      type: object
      properties:
        burgerservicenummer:
          $ref: '#/components/schemas/Burgerservicenummer'
        geboorte:
          $ref: 'geboorte.yaml#/components/schemas/GbaGeboorteBeperkt'
        geheimhoudingPersoonsgegevens:
          $ref: '#/components/schemas/GbaGeheimhoudingPersoonsgegevens'
        geslacht:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        persoonInOnderzoek:
          $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
        naam:
          $ref: 'naam.yaml#/components/schemas/GbaNaamBasis'
        opschortingBijhouding:
          $ref: 'opschortingbijhouding.yaml#/components/schemas/GbaOpschortingBijhouding'
        gemeenteVanInschrijving:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        verblijfplaats:
          $ref: 'verblijfplaats.yaml#/components/schemas/GbaVerblijfplaatsBeperkt'
        rni:
          type: array
          items:
            $ref: '#/components/schemas/RniDeelnemer'
        verificatie:
          $ref: '#/components/schemas/GbaVerificatie'
    PersoonBeperkt:
      type: object
      description: |
        * **geslacht** - wordt gevuld met waarden voor 'Geslacht' in 'tabelwaarden.csv'.
      properties:
        burgerservicenummer:
          $ref: '#/components/schemas/Burgerservicenummer'
        geboorte:
          $ref: 'geboorte.yaml#/components/schemas/GeboorteBeperkt'
        geheimhoudingPersoonsgegevens:
          $ref: '#/components/schemas/GeheimhoudingPersoonsgegevens'
        geslacht:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        inOnderzoek:
          $ref: '#/components/schemas/PersoonInOnderzoekBeperkt'
        leeftijd:
          $ref: '#/components/schemas/Leeftijd'
        naam:
          $ref: 'naam.yaml#/components/schemas/NaamPersoonBeperkt'
        opschortingBijhouding:
          $ref: 'opschortingbijhouding.yaml#/components/schemas/OpschortingBijhouding'
        adressering:
          $ref: 'adressering.yaml#/components/schemas/AdresseringBeperkt'
        rni:
          type: array
          items:
            $ref: '#/components/schemas/RniDeelnemer'
        verificatie:
          $ref: '#/components/schemas/Verificatie'
    GbaPersoon:
      type: object
      properties:
        aNummer:
          $ref: '#/components/schemas/ANummer'
        burgerservicenummer:
          $ref: '#/components/schemas/Burgerservicenummer'
        datumEersteInschrijvingGBA:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
        geheimhoudingPersoonsgegevens:
          $ref: '#/components/schemas/GbaGeheimhoudingPersoonsgegevens'
        geslacht:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        persoonInOnderzoek:
          $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
        gezagInOnderzoek:
          $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
        uitsluitingKiesrecht:
          $ref: 'kiesrecht.yaml#/components/schemas/GbaUitsluitingKiesrecht'
        europeesKiesrecht:
          $ref: 'kiesrecht.yaml#/components/schemas/GbaEuropeesKiesrecht'
        naam:
          $ref: 'naam.yaml#/components/schemas/GbaNaamPersoon'
        nationaliteiten:
          type: array
          items:
            $ref: 'nationaliteit.yaml#/components/schemas/GbaNationaliteit'
        geboorte:
          $ref: 'geboorte.yaml#/components/schemas/GbaGeboorte'
        opschortingBijhouding:
          $ref: 'opschortingbijhouding.yaml#/components/schemas/GbaOpschortingBijhouding'
        overlijden:
          $ref: 'overlijden.yaml#/components/schemas/GbaOverlijden'
        verblijfplaats:
          $ref: 'verblijfplaats.yaml#/components/schemas/GbaVerblijfplaats'
        immigratie:
          $ref: 'immigratie.yaml#/components/schemas/GbaImmigratie'
        gemeenteVanInschrijving:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        datumInschrijvingInGemeente:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
        indicatieCurateleRegister:
          $ref: '#/components/schemas/IndicatieCurateleRegister'
        indicatieGezagMinderjarige:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
          deprecated: true
        gezag:
          $ref: 'gezag.yaml#/components/schemas/Gezag'
        verblijfstitel:
          $ref: 'verblijfstitel.yaml#/components/schemas/GbaVerblijfstitel'
        kinderen:
          type: array
          items:
            $ref: 'kind.yaml#/components/schemas/GbaKind'
        ouders:
          type: array
          items:
            $ref: 'ouder.yaml#/components/schemas/GbaOuder'
        partners:
          type: array
          items:
            $ref: 'partner.yaml#/components/schemas/GbaPartner'
        rni:
          type: array
          items:
            $ref: '#/components/schemas/RniDeelnemer'
        verificatie:
          $ref: '#/components/schemas/GbaVerificatie'
    Persoon:
      type: object
      description: |
        * **geslacht** - wordt gevuld met waarden voor 'Geslacht' in 'tabelwaarden.csv'.
      properties:
        aNummer:
          $ref: '#/components/schemas/ANummer'
        burgerservicenummer:
          $ref: '#/components/schemas/Burgerservicenummer'
        datumEersteInschrijvingGBA:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
        geheimhoudingPersoonsgegevens:
          $ref: '#/components/schemas/GeheimhoudingPersoonsgegevens'
        geslacht:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        inOnderzoek:
          $ref: '#/components/schemas/PersoonInOnderzoek'
        uitsluitingKiesrecht:
          $ref: 'kiesrecht.yaml#/components/schemas/UitsluitingKiesrecht'
        europeesKiesrecht:
          $ref: 'kiesrecht.yaml#/components/schemas/EuropeesKiesrecht'
        leeftijd:
          $ref: '#/components/schemas/Leeftijd'
        naam:
          $ref: 'naam.yaml#/components/schemas/NaamPersoon'
        nationaliteiten:
          type: array
          items:
            $ref: 'nationaliteit.yaml#/components/schemas/AbstractNationaliteit'
        geboorte:
          $ref: 'geboorte.yaml#/components/schemas/Geboorte'
        opschortingBijhouding:
          $ref: 'opschortingbijhouding.yaml#/components/schemas/OpschortingBijhouding'
        overlijden:
          $ref: 'overlijden.yaml#/components/schemas/Overlijden'
        verblijfplaats:
          $ref: 'verblijfplaats.yaml#/components/schemas/AbstractVerblijfplaats'
        immigratie:
          $ref: 'immigratie.yaml#/components/schemas/Immigratie'
        gemeenteVanInschrijving:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        datumInschrijvingInGemeente:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
        adressering:
          $ref: 'adressering.yaml#/components/schemas/Adressering'
        indicatieCurateleRegister:
          $ref: '#/components/schemas/IndicatieCurateleRegister'
        indicatieGezagMinderjarige:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
          deprecated: true
        gezag:
          $ref: 'gezag.yaml#/components/schemas/Gezag'
        verblijfstitel:
          $ref: 'verblijfstitel.yaml#/components/schemas/Verblijfstitel'
        kinderen:
          type: array
          items:
            $ref: 'kind.yaml#/components/schemas/Kind'
        ouders:
          type: array
          items:
            $ref: 'ouder.yaml#/components/schemas/Ouder'
        partners:
          type: array
          items:
            $ref: 'partner.yaml#/components/schemas/Partner'
        rni:
          type: array
          items:
            $ref: '#/components/schemas/RniDeelnemer'
        verificatie:
          $ref: '#/components/schemas/Verificatie'
    PersoonInOnderzoek:
      description: |
        Geeft aan welke gegevens van de persoon in onderzoek zijn.
        * **datumIngangOnderzoekPersoon - Deze datum heeft betrekking op burgerservicenummer, geslacht en leeftijd
        * **datumIngangOnderzoekGemeente - Deze datum heeft betrekking op gemeenteVanInschrijving en datumInschrijvingInGemeente
        * **datumIngangOnderzoekGezag - Deze datumingang heeft betrekking op indicatieCurateleRegister en indicatieGezagMinderjarige
      type: object
      properties:
        datumIngangOnderzoekPersoon:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
        datumIngangOnderzoekGemeente:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
        datumIngangOnderzoekGezag:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
        burgerservicenummer:
          type: boolean
        geslacht:
          type: boolean
        leeftijd:
          type: boolean
        gemeenteVanInschrijving:
          type: boolean
        datumInschrijvingInGemeente:
          type: boolean
        indicatieCurateleRegister:
          type: boolean
        indicatieGezagMinderjarige:
          type: boolean
    PersoonInOnderzoekBeperkt:
      description: |
        Geeft aan welke gegevens van de persoon in onderzoek zijn.
        * **datumIngangOnderzoekPersoon - Deze datum heeft betrekking op burgerservicenummer, geslacht en leeftijd
      type: object
      properties:
        datumIngangOnderzoekPersoon:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
        burgerservicenummer:
          type: boolean
        geslacht:
          type: boolean
        leeftijd:
          type: boolean
    InOnderzoek:
      type: object
      properties:
        datumIngangOnderzoek:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
