openapi: 3.0.3
info:
  title: Zoek Personen endpoint definitie
  version: 2.0.0
  contact: {}
paths:
  /personen:
    post:
      operationId: GetPersonen
      summary: Zoek personen
      description: |
        Zoek personen met één van de onderstaande verplichte combinaties van parameters en vul ze evt. aan met optionele parameters.

        1.  Raadpleeg met burgerservicenummer
        2.  Zoek met geslachtsnaam en geboortedatum
        3.  Zoek met geslachtsnaam, voornamen en gemeente van inschrijving
        4.  Zoek met postcode en huisnummer
        5.  Zoek met straat, huisnummer en gemeente van inschrijving
        6.  Zoek met nummeraanduiding identificatie

        Default krijg je personen terug die nog in leven zijn, tenzij je de inclusiefoverledenpersonen=true opgeeft.
        
        Gebruik de fields parameter om alleen die gegevens op te vragen die je nodig hebt en waarvoor je geautoriseerd bent.
      requestBody:
        content:
          'application/json; charset=utf-8':
            schema:
              $ref: 'zoek-personen.yaml#/components/schemas/PersonenQuery'
      responses:
        '200':
          description: |
                        Zoekactie geslaagd
          headers:
            warning:
              $ref: 'common.yaml#/components/headers/warning'
            X-Rate-Limit-Limit:
              $ref: 'common.yaml#/components/headers/X_Rate_Limit_Limit'
            X-Rate-Limit-Remaining:
              $ref: 'common.yaml#/components/headers/X_Rate_Limit_Remaining'
            X-Rate-Limit-Reset:
              $ref: 'common.yaml#/components/headers/X_Rate_Limit_Reset'
          content:
            'application/json; charset=utf-8':
              schema:
                $ref: '#/components/schemas/PersonenQueryResponse'
        '400':
          $ref: 'common.yaml#/components/responses/400'
        '401':
          $ref: 'common.yaml#/components/responses/401'
        '403':
          $ref: 'common.yaml#/components/responses/403'
        '406':
          $ref: 'common.yaml#/components/responses/406'
        '415':
          $ref: 'common.yaml#/components/responses/415'
        '429':
          $ref: 'common.yaml#/components/responses/429'
        '500':
          $ref: 'common.yaml#/components/responses/500'
        '503':
          $ref: 'common.yaml#/components/responses/503'
        'default':
          $ref: 'common.yaml#/components/responses/default'
      tags:
        - Personen
components:
  schemas:
    PersonenQueryResponse:
      type: object
      required:
        - type
      discriminator:
        propertyName: type
        mapping:
          ZoekMetGeslachtsnaamEnGeboortedatum: '#/components/schemas/ZoekMetGeslachtsnaamEnGeboortedatumResponse'
          ZoekMetNaamEnGemeenteVanInschrijving: '#/components/schemas/ZoekMetNaamEnGemeenteVanInschrijvingResponse'
          RaadpleegMetBurgerservicenummer: '#/components/schemas/RaadpleegMetBurgerservicenummerResponse'
          ZoekMetPostcodeEnHuisnummer: '#/components/schemas/ZoekMetPostcodeEnHuisnummerResponse'
          ZoekMetStraatHuisnummerEnGemeenteVanInschrijving: '#/components/schemas/ZoekMetStraatHuisnummerEnGemeenteVanInschrijvingResponse'
          ZoekMetNummeraanduidingIdentificatie: '#/components/schemas/ZoekMetNummeraanduidingIdentificatieResponse'
          ZoekMetAdresseerbaarObjectIdentificatie: '#/components/schemas/ZoekMetAdresseerbaarObjectIdentificatieResponse'
      properties:
        type:
          type: string
    RaadpleegMetBurgerservicenummerResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon.yaml#/components/schemas/GbaPersoon'
    ZoekMetGeslachtsnaamEnGeboortedatumResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon.yaml#/components/schemas/GbaPersoonBeperkt'
    ZoekMetNaamEnGemeenteVanInschrijvingResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon.yaml#/components/schemas/GbaPersoonBeperkt'
    ZoekMetPostcodeEnHuisnummerResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon.yaml#/components/schemas/GbaPersoonBeperkt'
    ZoekMetStraatHuisnummerEnGemeenteVanInschrijvingResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon.yaml#/components/schemas/GbaPersoonBeperkt'
    ZoekMetNummeraanduidingIdentificatieResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon.yaml#/components/schemas/GbaPersoonBeperkt'
    ZoekMetAdresseerbaarObjectIdentificatieResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'gezag.yaml#/components/schemas/GbaGezagPersoonBeperkt'
