openapi: 3.0.3
info:
  title: Zoek Personen endpoint definitie
  version: 2.0.0
  contact: {}
paths:
  /ingeschrevenpersonen:
    get:
      operationId: GetIngeschrevenPersonen
      summary: Vindt personen
      description: |
        Zoek personen met één van de onderstaande verplichte combinaties van parameters en vul ze evt. aan met parameters uit de andere combinaties.


        Default krijg je personen terug die nog in leven zijn, tenzij je de inclusiefoverledenpersonen=true opgeeft.


        Gebruik de fields parameter als je alleen specifieke velden in het antwoord wil zien, [zie functionele specificaties fields-parameter](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/fields_extensie.feature)


        1.  Persoon
            -  geboorte__datum
            -  naam__geslachtsnaam (minimaal 2 karakters, [wildcard toegestaan](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/wildcard.feature)


        2.  Persoon
            -  verblijfplaats__gemeenteVanInschrijving
            -  naam__geslachtsnaam (minimaal 2 karakters, [wildcard toegestaan](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/wildcard.feature)


        3.  Persoon
            -  burgerservicenummer


        4.  Postcode
            -  verblijfplaats__postcode
            -  verblijfplaats__huisnummer


        5.  Straat
            -  verblijfplaats__straat (minimaal 2 karakters, [wildcard toegestaan](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/wildcard.feature) )
            -  verblijfplaats__gemeenteVanInschrijving
            -  verblijfplaats__huisnummer


        6.  Adres
            -  verblijfplaats__nummeraanduidingIdentificatie

      parameters:
        - name: expand
          deprecated: true
          in: query
          required: false
          description: "Hiermee kun je opgeven welke gerelateerde resources meegeleverd moeten worden, en hun inhoud naar behoefte aanpassen. Hele resources of enkele properties geef je in de expand parameter kommagescheiden op. Properties die je wil ontvangen geef je op met de resource-naam gevolgd door de property naam, met daartussen een punt. In de definitie van het antwoord kun je bij _embedded zien welke gerelateerde resources meegeleverd kunnen worden. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/expand.feature)."
          schema:
            type: string
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/parameters/fields"
        - in: query
          name: burgerservicenummer
          required: false
          description: |
                        Uniek persoonsnummer.
          explode: false
          example: ["999993653","999991723","999995078"]
          schema:
            type: array
            items:
              type: string
              pattern: "^[0-9]*$"
              maxLength: 9
              minLength: 9
        - in: query
          name: geboorte__datum
          description: |
                        Je kunt alleen zoeken met een volledig geboortedatum. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/parametervalidatie.feature)
          required: false
          schema:
            type: string
            format: date
            example: "1964-09-24"
        - in: query
          name: geboorte__plaats
          description: |
                        Gemeentenaam of een buitenlandse plaats of een plaatsbepaling, die aangeeft waar de persoon is geboren. **Zoeken met tekstvelden is [case-Insensitive](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/case_insensitive.feature).**
          required: false
          schema:
            type: string
            maxLength: 40
            example: "Utrecht"
        - in: query
          name: geslachtsaanduiding
          description: |
                        Geeft aan dat de persoon een man of een vrouw is, of dat het geslacht (nog) onbekend is.
          required: false
          schema:
            type: string
            example: "V"
        - in: query
          name: inclusiefOverledenPersonen
          description: |
                        Als je ook overleden personen in het antwoord wilt, geef dan de parameter inclusiefOverledenPersonen op met waarde True.  Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/overleden_personen.feature)
          required: false
          schema:
            type: boolean
            example: true
        - in: query
          name: naam__geslachtsnaam
          description: |
                        De (geslachts)naam waarvan de eventueel aanwezige voorvoegsels zijn afgesplitst. **Gebruik van de wildcard is toegestaan. Zie [feature-beschrijving](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/wildcard.feature)** **Zoeken met tekstvelden is [case-Insensitive](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/case_insensitive.feature).**
          required: false
          schema:
            type: string
            maxLength: 200
            example: "Vries"
        - in: query
          name: naam__voorvoegsel
          description: |
                        Deel van de geslachtsnaam dat vooraf gaat aan de rest van de geslachtsnaam. Het zoeken op het voorvoegsel is [case-Insensitive](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/case_insensitive.feature).**
          required: false
          schema:
            type: string
            maxLength: 10
            example: "de"
        - in: query
          name: naam__voornamen
          description: |
                        De verzameling namen die, gescheiden door spaties, aan de geslachtsnaam voorafgaat. ** Bij deze query-parameter is het gebruik van een [wildcard](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/wildcard.feature) toegestaan in combinatie met minimaal 2 karakters.** **Zoeken met tekstvelden is [case-Insensitive](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/case_insensitive.feature).**
          required: false
          schema:
            type: string
            maxLength: 200
            example: "Dirk"
        - in: query
          name: verblijfplaats__gemeenteVanInschrijving
          description: |
                        Een code die aangeeft in welke gemeente de persoon woont, of de laatste gemeente waar de persoon heeft gewoond, of de gemeente waar de persoon voor het eerst is ingeschreven.
          required: false
          schema:
            type: string
            maxLength: 4
            example: "0518"
        - in: query
          name: verblijfplaats__huisletter
          description: |
                        Een toevoeging aan een huisnummer in de vorm van een letter die door de gemeente aan een adresseerbaar object is gegeven.
          required: false
          schema:
            type: string
            maxLength: 1
            example: "a"
        - in: query
          name: verblijfplaats__huisnummer
          description: |
                        Een nummer dat door de gemeente aan een adresseerbaar object is gegeven.
          required: false
          schema:
            type: integer
            maximum: 99999
            example: 14
        - in: query
          name: verblijfplaats__huisnummertoevoeging
          description: |
                        Een toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter die door de gemeente aan een adresseerbaar object is gegeven.
          required: false
          schema:
            type: string
            maxLength: 4
            example: "bis"
        - in: query
          name: verblijfplaats__nummeraanduidingIdentificatie
          description: |
                        Unieke identificatie van een nummeraanduiding (en het bijbehorende adres) in de BAG.
          required: false
          schema:
            type: string
            maxLength: 16
            example: "0518200000366054"
        - in: query
          name: verblijfplaats__straat
          description: |
                        Een naam die door de gemeente aan een openbare ruimte is gegeven. **Gebruik van de wildcard is toegestaan. Zie [feature-beschrijving](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.2.0/features/wildcard.feature)** **Zoeken met tekstvelden is [case-Insensitive](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.1.0/features/case_insensitive.feature).
          required: false
          schema:
            type: string
            maxLength: 80
            example: "Tulpstraat"
        - in: query
          name: verblijfplaats__postcode
          description: |
                        De door PostNL vastgestelde code die bij een bepaalde combinatie van een straatnaam en een huisnummer hoort.
          required: false
          schema:
            type: string
            pattern: ^[1-9]{1}[0-9]{3}[A-Z]{2}$
            example: "2341SX"
      responses:
        '200':
          description: |
                        Zoekactie geslaagd
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/headers/warning"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/IngeschrevenPersoonHalCollectie'
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/403"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/406"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/500"
        '501':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/501"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/503"
        'default':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/default"
      tags:
        - Ingeschreven Personen
components:
  schemas:
    IngeschrevenPersoonHalCollectie:
      type: object
      properties:
        _links:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/HalCollectionLinks"
        _embedded:
          $ref: "#/components/schemas/IngeschrevenPersoonHalCollectieEmbedded"
    IngeschrevenPersoonHalCollectieEmbedded:
      type: object
      properties:
        ingeschrevenpersonen:
          type: array
          items:
            $ref: '#/components/schemas/IngeschrevenPersoonBeperktHal'
    IngeschrevenPersoonBeperktHal:
      allOf:
        - $ref: 'ingeschrevenpersoon.yaml#/components/schemas/IngeschrevenPersoonBeperkt'
        - properties:
            _links:
              $ref: "#/components/schemas/IngeschrevenPersoonBeperktLinks"
    IngeschrevenPersoonBeperktLinks:
        type: "object"
        properties:
          self:
            $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/HalLink"
