openapi: 3.0.3
info:
  title: Zoek Personen endpoint definitie
  version: 2.0.0
  contact: {}
paths:
  /personen:
    post:
      operationId: GetPersonen
      summary: Vindt personen
      description: |
        Zoek personen met één van de onderstaande verplichte combinaties van parameters en vul ze evt. aan met optionele parameters.


        Default krijg je personen terug die nog in leven zijn, tenzij je de inclusiefoverledenpersonen=true opgeeft.


        Gebruik de fields parameter als je alleen specifieke velden in het antwoord wil zien, [zie functionele specificaties fields-parameter](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.3.0/features/fields_extensie.feature)


        1.  Zoek met geslachtsnaam en geboortedatum
            - geboortedatum
            - geslachtsnaam (minimaal 2 karakters, [wildcard toegestaan](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.3.0/features/wildcard.feature))


        2.  Zoek met geslachtsnaam en gemeente van inschrijving
            - gemeenteVanInschrijving
            - geslachtsnaam (minimaal 2 karakters, [wildcard toegestaan](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.3.0/features/wildcard.feature))


        3.  Raadpleeg met burgerservicenummer
            - burgerservicenummer


        4.  Zoek met postcode en huisnummer
            - postcode
            - huisnummer


        5.  Zoek met straat, huisnummer en gemeente van inschrijving
            - straat (minimaal 2 karakters, [wildcard toegestaan](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.3.0/features/wildcard.feature))
            - gemeenteVanInschrijving
            - huisnummer


        6.  Zoek met nummeraanduiding identificatie
            - nummeraanduidingIdentificatie

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonenQuery'
      responses:
        '200':
          description: |
                        Zoekactie geslaagd
          headers:
            api-version:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.3.0/api-specificatie/common.yaml#/components/headers/api_version'
            warning:
              $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.3.0/api-specificatie/common.yaml#/components/headers/warning'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonenQueryResponse'
        '400':
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.3.0/api-specificatie/common.yaml#/components/responses/400'
        '401':
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.3.0/api-specificatie/common.yaml#/components/responses/401'
        '403':
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.3.0/api-specificatie/common.yaml#/components/responses/403'
        '406':
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.3.0/api-specificatie/common.yaml#/components/responses/406'
        '500':
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.3.0/api-specificatie/common.yaml#/components/responses/500'
        '501':
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.3.0/api-specificatie/common.yaml#/components/responses/501'
        '503':
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.3.0/api-specificatie/common.yaml#/components/responses/503'
        'default':
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.3.0/api-specificatie/common.yaml#/components/responses/default'
      tags:
        - Personen
components:
  schemas:
    InclusiefOverledenPersonen:
      description: |
        Als je ook overleden personen in het antwoord wilt, geef dan de parameter inclusiefOverledenPersonen op met waarde True.  Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.3.0/features/overleden_personen.feature)
      type: boolean
      example: true
    PersonenQuery:
      type: object
      required:
        - type
        - fields
      discriminator:
        propertyName: type
        mapping:
          ZoekMetGeslachtsnaamEnGeboortedatum: '#/components/schemas/ZoekMetGeslachtsnaamEnGeboortedatum'
          ZoekMetGeslachtsnaamEnGemeenteVanInschrijving: '#/components/schemas/ZoekMetGeslachtsnaamEnGemeenteVanInschrijving'
          RaadpleegMetBurgerservicenummer: '#/components/schemas/RaadpleegMetBurgerservicenummer'
          ZoekMetPostcodeEnHuisnummer: '#/components/schemas/ZoekMetPostcodeEnHuisnummer'
          ZoekMetStraatHuisnummerEnGemeenteVanInschrijving: '#/components/schemas/ZoekMetStraatHuisnummerEnGemeenteVanInschrijving'
          ZoekMetNummeraanduidingIdentificatie: '#/components/schemas/ZoekMetNummeraanduidingIdentificatie'
      properties:
        type:
          type: string
        fields:
          $ref: 'filter.yaml#/components/schemas/Fields'
        gemeenteVanInschrijving:
          $ref: 'verblijfplaats.yaml#/components/schemas/GemeenteVanInschrijving'
    RaadpleegMetBurgerservicenummer:
      required:
        - burgerservicenummer
      allOf:
        - $ref: '#/components/schemas/PersonenQuery'
        - type: object
          properties:
            burgerservicenummer:
              type: array
              items:
                $ref: 'persoon.yaml#/components/schemas/Burgerservicenummer'
              minItems: 1
              maxItems: 20
    ZoekMetGeslachtsnaamEnGeboortedatum:
      required:
        - geslachtsnaam
        - geboortedatum
      allOf:
        - $ref: '#/components/schemas/PersonenQuery'
        - type: object
          properties:
            inclusiefOverledenPersonen:
              $ref: '#/components/schemas/InclusiefOverledenPersonen'
            geboortedatum:
              description: |
                Je kunt alleen zoeken met een volledig geboortedatum. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.3.0/features/parametervalidatie.feature)
              type: string
              format: date
              example: "1964-09-24"
            geboorteplaats:
              description: |
                Gemeentenaam of een buitenlandse plaats of een plaatsbepaling, die aangeeft waar de persoon is geboren. **Zoeken met tekstvelden is [case-Insensitive](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.3.0/features/case_insensitive.feature).**
              type: string
              pattern: ^(\?+|\*)?[a-zA-Z0-9À-ÿ '\-\']{1,40}(\?+|\*)?$
              maxLength: 40
              example: "Utrecht"
            geslachtsnaam:
              description: |
                De (geslachts)naam waarvan de eventueel aanwezige voorvoegsels zijn afgesplitst. **Gebruik van de wildcard is toegestaan. Zie [feature-beschrijving](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.3.0/features/wildcard.feature)** **Zoeken met tekstvelden is [case-Insensitive](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.3.0/features/case_insensitive.feature).**
              type: string
              pattern: ^(\?+|\*)?[a-zA-Z0-9À-ÿ '\-\']{1,200}(\?+|\*)?$
              example: "Vries"
            geslachtsaanduiding:
              description: |
                Geeft aan dat de persoon een man of een vrouw is, of dat het geslacht (nog) onbekend is.
              type: string
              pattern: ^([Mm]|[Vv]|[Oo])$
              example: "V"
            voorvoegsel:
              description: |
                Deel van de geslachtsnaam dat vooraf gaat aan de rest van de geslachtsnaam. Het zoeken op het voorvoegsel is [case-Insensitive](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.3.0/features/case_insensitive.feature).**
              type: string
              pattern: ^[a-zA-Z0-9À-ÿ' '\-\']{1,10}$
              example: "de"
            voornamen:
              description: |
                De verzameling namen die, gescheiden door spaties, aan de geslachtsnaam voorafgaat. ** Bij deze query-parameter is het gebruik van een [wildcard](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.3.0/features/wildcard.feature) toegestaan in combinatie met minimaal 2 karakters.** **Zoeken met tekstvelden is [case-Insensitive](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.3.0/features/case_insensitive.feature).**
              type: string
              pattern: ^(\?+|\*)?[a-zA-Z0-9À-ÿ' '\-\']{1,200}(\?+|\*)?$
              example: "Dirk"
    ZoekMetGeslachtsnaamEnGemeenteVanInschrijving:
      required:
        - geslachtsnaam
        - gemeenteVanInschrijving
        - voornamen
      allOf:
        - $ref: '#/components/schemas/PersonenQuery'
        - type: object
          properties:
            inclusiefOverledenPersonen:
              $ref: '#/components/schemas/InclusiefOverledenPersonen'
            geslachtsaanduiding:
              description: |
                Geeft aan dat de persoon een man of een vrouw is, of dat het geslacht (nog) onbekend is.
              type: string
              pattern: ^([Mm]|[Vv]|[Oo])$
              example: "V"
            geslachtsnaam:
              description: |
                De (geslachts)naam waarvan de eventueel aanwezige voorvoegsels zijn afgesplitst. **Gebruik van de wildcard is toegestaan. Zie [feature-beschrijving](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.3.0/features/wildcard.feature)** **Zoeken met tekstvelden is [case-Insensitive](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.3.0/features/case_insensitive.feature).**
              type: string
              pattern: ^(\?+|\*)?[a-zA-Z0-9À-ÿ '\-\']{1,200}(\?+|\*)?$
              example: "Vries"
            voorvoegsel:
              description: |
                Deel van de geslachtsnaam dat vooraf gaat aan de rest van de geslachtsnaam. Het zoeken op het voorvoegsel is [case-Insensitive](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.3.0/features/case_insensitive.feature).**
              type: string
              pattern: ^[a-zA-Z0-9À-ÿ' '\-\']{1,10}$
              example: "de"
            voornamen:
              description: |
                De verzameling namen die, gescheiden door spaties, aan de geslachtsnaam voorafgaat. ** Bij deze query-parameter is het gebruik van een [wildcard](https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/v1.3.0/features/wildcard.feature) toegestaan in combinatie met minimaal 2 karakters.** **Zoeken met tekstvelden is [case-Insensitive](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v1.3.0/features/case_insensitive.feature).**
              type: string
              pattern: ^(\?+|\*)?[a-zA-Z0-9À-ÿ' '\-\']{1,200}(\?+|\*)?$
              example: "Dirk"
    ZoekMetPostcodeEnHuisnummer:
      required:
        - postcode
        - huisnummer
      allOf:
        - $ref: '#/components/schemas/PersonenQuery'
        - type: object
          properties:
            inclusiefOverledenPersonen:
              $ref: '#/components/schemas/InclusiefOverledenPersonen'
            huisletter:
              $ref: 'verblijfplaats.yaml#/components/schemas/Huisletter'
            huisnummer:
              $ref: 'verblijfplaats.yaml#/components/schemas/Huisnummer'
            huisnummertoevoeging:
              $ref: 'verblijfplaats.yaml#/components/schemas/Huisnummertoevoeging'
            postcode:
              $ref: 'verblijfplaats.yaml#/components/schemas/Postcode'
    ZoekMetStraatHuisnummerEnGemeenteVanInschrijving:
      required:
        - straat
        - huisnummer
        - gemeenteVanInschrijving
      allOf:
        - $ref: '#/components/schemas/PersonenQuery'
        - type: object
          properties:
            inclusiefOverledenPersonen:
              $ref: '#/components/schemas/InclusiefOverledenPersonen'
            huisletter:
              $ref: 'verblijfplaats.yaml#/components/schemas/Huisletter'
            huisnummer:
              $ref: 'verblijfplaats.yaml#/components/schemas/Huisnummer'
            huisnummertoevoeging:
              $ref: 'verblijfplaats.yaml#/components/schemas/Huisnummertoevoeging'
            straat:
              $ref: 'filter.yaml#/components/schemas/StraatFilter'
    ZoekMetNummeraanduidingIdentificatie:
      required:
        - nummeraanduidingIdentificatie
      allOf:
        - $ref: '#/components/schemas/PersonenQuery'
        - type: object
          properties:
            inclusiefOverledenPersonen:
              $ref: '#/components/schemas/InclusiefOverledenPersonen'
            nummeraanduidingIdentificatie:
              $ref: 'verblijfplaats.yaml#/components/schemas/NummeraanduidingIdentificatie'
    PersonenQueryResponse:
      type: object
      required:
        - type
      discriminator:
        propertyName: type
        mapping:
          ZoekMetGeslachtsnaamEnGeboortedatum: '#/components/schemas/ZoekMetGeslachtsnaamEnGeboortedatumResponse'
          ZoekMetGeslachtsnaamEnGemeenteVanInschrijving: '#/components/schemas/ZoekMetGeslachtsnaamEnGemeenteVanInschrijvingResponse'
          RaadpleegMetBurgerservicenummer: '#/components/schemas/RaadpleegMetBurgerservicenummerResponse'
          ZoekMetPostcodeEnHuisnummer: '#/components/schemas/ZoekMetPostcodeEnHuisnummerResponse'
          ZoekMetStraatHuisnummerEnGemeenteVanInschrijving: '#/components/schemas/ZoekMetStraatHuisnummerEnGemeenteVanInschrijvingResponse'
          ZoekMetNummeraanduidingIdentificatie: '#/components/schemas/ZoekMetNummeraanduidingIdentificatieResponse'
      properties:
        type:
          type: string
    RaadpleegMetBurgerservicenummerResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon.yaml#/components/schemas/AbstractPersoon'
    ZoekMetGeslachtsnaamEnGeboortedatumResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon.yaml#/components/schemas/AbstractPersoonBeperkt'
    ZoekMetGeslachtsnaamEnGemeenteVanInschrijvingResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon.yaml#/components/schemas/AbstractPersoonBeperkt'
    ZoekMetPostcodeEnHuisnummerResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon.yaml#/components/schemas/AbstractPersoonBeperkt'
    ZoekMetStraatHuisnummerEnGemeenteVanInschrijvingResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon.yaml#/components/schemas/AbstractPersoonBeperkt'
    ZoekMetNummeraanduidingIdentificatieResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              items:
                $ref: 'persoon.yaml#/components/schemas/AbstractPersoonBeperkt'
