openapi: 3.0.3
info:
  title: Zoek Personen endpoint definitie
  version: 2.0.0
  contact: {}
paths:
  /personen:
    post:
      operationId: Personen
      summary: Zoek personen
      description: |
        Zoek personen met één van de onderstaande verplichte combinaties van parameters en vul ze evt. aan met optionele parameters.

        1.  Raadpleeg met burgerservicenummer
        2.  Zoek met geslachtsnaam en geboortedatum
        3.  Zoek met geslachtsnaam, voornamen en gemeente van inschrijving
        4.  Zoek met postcode en huisnummer
        5.  Zoek met straat, huisnummer en gemeente van inschrijving
        6.  Zoek met nummeraanduiding identificatie
        7.  Zoek met adresseerbaarobject identificatie

        Default krijg je personen terug die nog in leven zijn, tenzij je de inclusiefoverledenpersonen=true opgeeft.
        
        Gebruik de fields parameter om alleen die gegevens op te vragen die je nodig hebt en waarvoor je geautoriseerd bent.
      requestBody:
        content:
          'application/json; charset=utf-8':
            schema:
              $ref: '#/components/schemas/PersonenQuery'
      responses:
        '200':
          description: |
                        Zoekactie geslaagd
          headers:
            warning:
              $ref: 'common.yaml#/components/headers/warning'
            X-Rate-Limit-Limit:
              $ref: 'common.yaml#/components/headers/X_Rate_Limit_Limit'
            X-Rate-Limit-Remaining:
              $ref: 'common.yaml#/components/headers/X_Rate_Limit_Remaining'
            X-Rate-Limit-Reset:
              $ref: 'common.yaml#/components/headers/X_Rate_Limit_Reset'
          content:
            'application/json; charset=utf-8':
              schema:
                $ref: '#/components/schemas/PersonenQueryResponse'
        '400':
          $ref: 'common.yaml#/components/responses/400'
        '401':
          $ref: 'common.yaml#/components/responses/401'
        '403':
          $ref: 'common.yaml#/components/responses/403'
        '406':
          $ref: 'common.yaml#/components/responses/406'
        '415':
          $ref: 'common.yaml#/components/responses/415'
        '429':
          $ref: 'common.yaml#/components/responses/429'
        '500':
          $ref: 'common.yaml#/components/responses/500'
        '503':
          $ref: 'common.yaml#/components/responses/503'
        'default':
          $ref: 'common.yaml#/components/responses/default'
      tags:
        - Personen
components:
  schemas:
    InclusiefOverledenPersonen:
      description: |
        Als je ook overleden personen in het antwoord wilt, geef dan de parameter inclusiefOverledenPersonen op met waarde True.
      type: boolean
      example: true
    PersonenQuery:
      type: object
      required:
        - type
        - fields
      discriminator:
        propertyName: type
        mapping:
          ZoekMetGeslachtsnaamEnGeboortedatum: '#/components/schemas/ZoekMetGeslachtsnaamEnGeboortedatum'
          ZoekMetNaamEnGemeenteVanInschrijving: '#/components/schemas/ZoekMetNaamEnGemeenteVanInschrijving'
          RaadpleegMetBurgerservicenummer: '#/components/schemas/RaadpleegMetBurgerservicenummer'
          ZoekMetPostcodeEnHuisnummer: '#/components/schemas/ZoekMetPostcodeEnHuisnummer'
          ZoekMetStraatHuisnummerEnGemeenteVanInschrijving: '#/components/schemas/ZoekMetStraatHuisnummerEnGemeenteVanInschrijving'
          ZoekMetNummeraanduidingIdentificatie: '#/components/schemas/ZoekMetNummeraanduidingIdentificatie'
          ZoekMetAdresseerbaarObjectIdentificatie: '#/components/schemas/ZoekMetAdresseerbaarObjectIdentificatie'
      properties:
        type:
          type: string
        fields:
          description: |
            Hiermee kun je de velden opgeven die je wenst te ontvangen.
            
            Velden die automatisch worden geleverd (inOnderzoek, geheimhoudingPersoonsgegevens, opschortingBijhouding, rni en verificatie) mag je niet opgeven in fields.
            Opgave van een pad dat verwijst naar een niet-bestaand veld of naar een automatisch geleverd veld leidt tot een 400 Bad Request.
            
            Meer details over hoe fields werkt lees je in het [feature overzicht](https://brp-api.github.io/Haal-Centraal-BRP-bevragen/v2/features-overzicht#filteren-van-de-velden-van-de-gevonden-personen).
            Stel je fields eenvoudig samen met de [fields tool](https://brp-api.github.io/Haal-Centraal-BRP-bevragen/v2/fields){:target="_blank" rel="noopener"}.
          type: array
          maxItems: 130
          minItems: 1
          items:
            $ref: 'filter.yaml#/components/schemas/Field'
        gemeenteVanInschrijving:
          $ref: 'persoon.yaml#/components/schemas/GemeenteVanInschrijving'
    RaadpleegMetBurgerservicenummer:
      required:
        - burgerservicenummer
      allOf:
        - $ref: '#/components/schemas/PersonenQuery'
        - type: object
          properties:
            burgerservicenummer:
              type: array
              items:
                $ref: 'persoon.yaml#/components/schemas/Burgerservicenummer'
              minItems: 1
              maxItems: 20
    ZoekMetGeslachtsnaamEnGeboortedatum:
      required:
        - geslachtsnaam
        - geboortedatum
      allOf:
        - $ref: '#/components/schemas/PersonenQuery'
        - type: object
          properties:
            inclusiefOverledenPersonen:
              $ref: '#/components/schemas/InclusiefOverledenPersonen'
            geboortedatum:
              description: |
                Je kunt alleen zoeken met een volledige geboortedatum.
              type: string
              format: date
              example: "1964-09-24"
            geslachtsnaam:
              $ref: 'filter.yaml#/components/schemas/GeslachtsnaamFilter'
            geslacht:
              $ref: 'filter.yaml#/components/schemas/GeslachtFilter'
            voorvoegsel:
              $ref: 'filter.yaml#/components/schemas/VoorvoegselFilter'
            voornamen:
              $ref: 'filter.yaml#/components/schemas/VoornamenOptioneelFilter'
    ZoekMetNaamEnGemeenteVanInschrijving:
      required:
        - geslachtsnaam
        - gemeenteVanInschrijving
        - voornamen
      allOf:
        - $ref: '#/components/schemas/PersonenQuery'
        - type: object
          properties:
            inclusiefOverledenPersonen:
              $ref: '#/components/schemas/InclusiefOverledenPersonen'
            geslacht:
              $ref: 'filter.yaml#/components/schemas/GeslachtFilter'
            geslachtsnaam:
              $ref: 'filter.yaml#/components/schemas/GeslachtsnaamFilter'
            voorvoegsel:
              $ref: 'filter.yaml#/components/schemas/VoorvoegselFilter'
            voornamen:
              $ref: 'filter.yaml#/components/schemas/VoornamenVerplichtFilter'
    ZoekMetPostcodeEnHuisnummer:
      required:
        - postcode
        - huisnummer
      allOf:
        - $ref: '#/components/schemas/PersonenQuery'
        - type: object
          properties:
            inclusiefOverledenPersonen:
              $ref: '#/components/schemas/InclusiefOverledenPersonen'
            huisletter:
              $ref: 'verblijfplaats.yaml#/components/schemas/Huisletter'
            huisnummer:
              $ref: 'verblijfplaats.yaml#/components/schemas/Huisnummer'
            huisnummertoevoeging:
              $ref: 'verblijfplaats.yaml#/components/schemas/Huisnummertoevoeging'
            postcode:
              $ref: 'verblijfplaats.yaml#/components/schemas/Postcode'
    ZoekMetStraatHuisnummerEnGemeenteVanInschrijving:
      required:
        - straat
        - huisnummer
        - gemeenteVanInschrijving
      allOf:
        - $ref: '#/components/schemas/PersonenQuery'
        - type: object
          properties:
            inclusiefOverledenPersonen:
              $ref: '#/components/schemas/InclusiefOverledenPersonen'
            huisletter:
              $ref: 'verblijfplaats.yaml#/components/schemas/Huisletter'
            huisnummer:
              $ref: 'verblijfplaats.yaml#/components/schemas/Huisnummer'
            huisnummertoevoeging:
              $ref: 'verblijfplaats.yaml#/components/schemas/Huisnummertoevoeging'
            straat:
              $ref: 'filter.yaml#/components/schemas/StraatFilter'
    ZoekMetNummeraanduidingIdentificatie:
      required:
        - nummeraanduidingIdentificatie
      allOf:
        - $ref: '#/components/schemas/PersonenQuery'
        - type: object
          properties:
            inclusiefOverledenPersonen:
              $ref: '#/components/schemas/InclusiefOverledenPersonen'
            nummeraanduidingIdentificatie:
              $ref: 'verblijfplaats.yaml#/components/schemas/NummeraanduidingIdentificatie'
    ZoekMetAdresseerbaarObjectIdentificatie:
      required:
        - adresseerbaarObjectIdentificatie
      allOf:
        - $ref: '#/components/schemas/PersonenQuery'
        - type: object
          properties:
            inclusiefOverledenPersonen:
              $ref: '#/components/schemas/InclusiefOverledenPersonen'
            adresseerbaarObjectIdentificatie:
              $ref: 'verblijfplaats.yaml#/components/schemas/AdresseerbaarObjectIdentificatie'
    PersonenQueryResponse:
      type: object
      required:
        - type
      discriminator:
        propertyName: type
        mapping:
          ZoekMetGeslachtsnaamEnGeboortedatum: '#/components/schemas/ZoekMetGeslachtsnaamEnGeboortedatumResponse'
          ZoekMetNaamEnGemeenteVanInschrijving: '#/components/schemas/ZoekMetNaamEnGemeenteVanInschrijvingResponse'
          RaadpleegMetBurgerservicenummer: '#/components/schemas/RaadpleegMetBurgerservicenummerResponse'
          ZoekMetPostcodeEnHuisnummer: '#/components/schemas/ZoekMetPostcodeEnHuisnummerResponse'
          ZoekMetStraatHuisnummerEnGemeenteVanInschrijving: '#/components/schemas/ZoekMetStraatHuisnummerEnGemeenteVanInschrijvingResponse'
          ZoekMetNummeraanduidingIdentificatie: '#/components/schemas/ZoekMetNummeraanduidingIdentificatieResponse'
          ZoekMetAdresseerbaarObjectIdentificatie: '#/components/schemas/ZoekMetAdresseerbaarObjectIdentificatieResponse'
      properties:
        type:
          type: string
    RaadpleegMetBurgerservicenummerResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              description: |
                * **geslacht** - wordt gevuld met waarden voor 'Geslacht' in 'tabelwaarden.csv'.
              items:
                $ref: 'persoon.yaml#/components/schemas/Persoon'
    ZoekMetGeslachtsnaamEnGeboortedatumResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              description: |
                * **geslacht** - wordt gevuld met waarden voor 'Geslacht' in 'tabelwaarden.csv'.
              items:
                $ref: 'persoon.yaml#/components/schemas/PersoonBeperkt'
    ZoekMetNaamEnGemeenteVanInschrijvingResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              description: |
                * **geslacht** - wordt gevuld met waarden voor 'Geslacht' in 'tabelwaarden.csv'.
              items:
                $ref: 'persoon.yaml#/components/schemas/PersoonBeperkt'
    ZoekMetPostcodeEnHuisnummerResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              description: |
                * **geslacht** - wordt gevuld met waarden voor 'Geslacht' in 'tabelwaarden.csv'.
              items:
                $ref: 'persoon.yaml#/components/schemas/PersoonBeperkt'
    ZoekMetStraatHuisnummerEnGemeenteVanInschrijvingResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              description: |
                * **geslacht** - wordt gevuld met waarden voor 'Geslacht' in 'tabelwaarden.csv'.
              items:
                $ref: 'persoon.yaml#/components/schemas/PersoonBeperkt'
    ZoekMetNummeraanduidingIdentificatieResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              description: |
                * **geslacht** - wordt gevuld met waarden voor 'Geslacht' in 'tabelwaarden.csv'.
              items:
                $ref: 'persoon.yaml#/components/schemas/PersoonBeperkt'
    ZoekMetAdresseerbaarObjectIdentificatieResponse:
      allOf:
        - $ref: '#/components/schemas/PersonenQueryResponse'
        - type: object
          properties:
            personen:
              type: array
              description: |
                * **geslacht** - wordt gevuld met waarden voor 'Geslacht' in 'tabelwaarden.csv'.
              items:
                $ref: 'gezag.yaml#/components/schemas/GezagPersoonBeperkt'
