# Generated by Django 2.0.8 on 2018-09-26 16:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import zds_schema.models
import zds_schema.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdellijkeTitelPredikaat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predikaat', models.CharField(max_length=2)),
                ('omschrijving', models.CharField(max_length=10)),
                ('soort', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Geboorte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('plaats', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='IngeschrevenNatuurlijkPersoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('burgerservicenummer', models.CharField(blank=True, help_text='Het burgerservicenummer, bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer.', max_length=9, null=True, validators=[zds_schema.validators.validate_non_negative_string])),
                ('a_nummer', models.BigIntegerField(null=True)),
                ('geslachtsaanduiding', models.CharField(blank=True, choices=[('Man', 'Man'), ('Vrouw', 'Vrouw'), ('Onbekend', 'Onbekend')], help_text='Een aanduiding die aangeeft of de persoon een man of een vrouw is, of dat het geslacht nog onbekend is.', max_length=1)),
                ('burgerlijke_staat', models.CharField(choices=[('ongehuwd en nooit gehuwd geweest', 'ongehuwd'), ('gehuwd', 'gehuwd'), ('gescheiden', 'gescheiden'), ('weduwe / weduwnaar', 'weduwe'), ('partnerschap', 'parnterschap'), ('partnerschap beeindigd', 'parnterschap beeindigd'), ('achtergebleven partner', 'achtergleven partner')], max_length=40)),
                ('indicatie_geheim', models.CharField(max_length=200)),
                ('gemeente_van_inschrijving', models.IntegerField(null=True)),
                ('datum_inschrijving_in_gemeente', models.DateField()),
                ('datum_begin_geldigheid_verblijfplaats', models.DateField()),
                ('datum_vestiging_in_nederland', models.DateField(null=True)),
                ('reden_opschorting_bijhouding', models.CharField(choices=[('overlijden', 'overlijden'), ('emigratie', 'emigratie'), ('Ministerieel besluit', 'ministrieel besluit'), ('PL aangelegd in de RNI', 'pl aangelegd in de rni'), ('fout', 'fout'), ('standaardwaarde indien onbekend', 'standaardwaarde indien onbekend')], max_length=40)),
                ('datum_opschorting_bijhouding', models.DateField()),
                ('signalering_nederlands_reisdocument', models.IntegerField(null=True)),
                ('geboorte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Geboorte')),
                ('kinderen', models.ManyToManyField(blank=True, related_name='ouders', to='datamodel.IngeschrevenNatuurlijkPersoon')),
            ],
            bases=(zds_schema.models.APIMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('code', models.CharField(help_text='De code, behorende bij de landnaam, zoals opgenomen in de Land/Gebied-tabel van de BRP.', max_length=4)),
                ('naam', models.CharField(help_text='De naam van het land, zoals opgenomen in de Land/Gebied-tabel van de BRP.', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Naam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornamen', models.CharField(blank=True, help_text='Voornamen bij de naam die de persoon wenst te voeren.', max_length=200)),
                ('geslachtsnaam', models.CharField(help_text='De stam van de geslachtsnaam.', max_length=200)),
                ('adellijke_titel_predikaat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamodel.AdellijkeTitelPredikaat')),
            ],
        ),
        migrations.CreateModel(
            name='Naamgebruik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aanduiding', models.CharField(choices=[('E', 'eigen'), ('P', 'Partner'), ('V', 'Partner, eigen'), ('N', 'Eigen, partner')], max_length=20)),
                ('aanschrijfwijze', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nationaliteit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aanduiding_bijzonder_nederlanderschap', models.CharField(choices=[('behandeld als Nederlander', 'behandeld als nederlander'), ('vastgesteld niet-Nederlander', 'vastgesteld niet nederlander')], max_length=40)),
                ('code', models.IntegerField()),
                ('officiele_omschrijving', models.CharField(max_length=42)),
                ('datum_einde_geldigheid', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Overlijden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('plaats', models.CharField(max_length=40)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Land')),
            ],
        ),
        migrations.CreateModel(
            name='Reisdocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.IngeschrevenNatuurlijkPersoon')),
            ],
        ),
        migrations.CreateModel(
            name='Verblijfsplaats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresherkomst', models.CharField(choices=[('Woonadres', 'woonadres'), ('Briefadres', 'briefadres')], max_length=20)),
                ('huisletter', models.CharField(blank=True, max_length=1)),
                ('identificatiecode_nummeraanduiding', models.CharField(blank=True, max_length=29)),
                ('huisnummer', models.IntegerField()),
                ('locatiebeschrijving', models.CharField(blank=True, help_text='Een geheel of gedeeltelijke omschrijving van de ligging van een object.', max_length=35)),
                ('woonplaatsnaam', models.CharField(max_length=80)),
                ('huisnummertoevoeging', models.CharField(blank=True, max_length=4)),
                ('naam_openbare_ruimte', models.CharField(max_length=80)),
                ('postcode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9]{1}[0-9]{3}[A-Z]{2}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Verblijfstitel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingangsdatum', models.DateField()),
                ('datum_einde', models.DateField()),
                ('numeriek', models.CharField(max_length=2)),
                ('omschrijving', models.CharField(max_length=80)),
                ('datum_aanvang_geldigheid', models.DateField()),
                ('datum_einde_geldigheid', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoorvoegselGeslachtsnaam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voorvoegselnummer', models.IntegerField()),
                ('voorvoegsel', models.CharField(max_length=10)),
                ('scheidingsteken', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='naam',
            name='voorvoegsel_geslachtsnaam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamodel.VoorvoegselGeslachtsnaam'),
        ),
        migrations.AddField(
            model_name='ingeschrevennatuurlijkpersoon',
            name='naam',
            field=models.ForeignKey(blank=True, help_text='Gegevens over de naam van de NATUURLIJK PERSOON', null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Naam'),
        ),
        migrations.AddField(
            model_name='ingeschrevennatuurlijkpersoon',
            name='naamgebruik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Naamgebruik'),
        ),
        migrations.AddField(
            model_name='ingeschrevennatuurlijkpersoon',
            name='nationaliteit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Nationaliteit'),
        ),
        migrations.AddField(
            model_name='ingeschrevennatuurlijkpersoon',
            name='overlijden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Overlijden'),
        ),
        migrations.AddField(
            model_name='ingeschrevennatuurlijkpersoon',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='_ingeschrevennatuurlijkpersoon_partners_+', to='datamodel.IngeschrevenNatuurlijkPersoon'),
        ),
        migrations.AddField(
            model_name='ingeschrevennatuurlijkpersoon',
            name='verblijfsplaats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Verblijfsplaats'),
        ),
        migrations.AddField(
            model_name='ingeschrevennatuurlijkpersoon',
            name='verblijfstitel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datamodel.Verblijfstitel'),
        ),
        migrations.AddField(
            model_name='geboorte',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Land'),
        ),
    ]
