# Generated by Django 2.0.8 on 2018-10-02 16:50

from django.db import migrations, models
import django.db.models.deletion
import zds_schema.validators


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingeschrevennatuurlijkpersoon',
            name='a_nummer',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingeschrevennatuurlijkpersoon',
            name='burgerservicenummer',
            field=models.CharField(blank=True, default='', help_text='Het burgerservicenummer, bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer.', max_length=9, validators=[zds_schema.validators.validate_non_negative_string]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingeschrevennatuurlijkpersoon',
            name='datum_vestiging_in_nederland',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingeschrevennatuurlijkpersoon',
            name='gemeente_van_inschrijving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingeschrevennatuurlijkpersoon',
            name='signalering_nederlands_reisdocument',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='naam',
            name='adellijke_titel_predikaat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamodel.AdellijkeTitelPredikaat'),
        ),
        migrations.AlterField(
            model_name='naam',
            name='voorvoegsel_geslachtsnaam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datamodel.VoorvoegselGeslachtsnaam'),
        ),
        migrations.AlterField(
            model_name='nationaliteit',
            name='datum_einde_geldigheid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verblijfstitel',
            name='datum_einde_geldigheid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
