contentType:
  name: Content-Type
  in: header
  required: false
  description: Media type van het request.
  schema:
    type: string
contentCrs:
  name: Content-Crs
  in: header
  required: false
  description: CRS van de meegegeven geometrie.
  schema:
    type: string
    enum:
      - 'epsg:4258'
      - 'epsg:28992'
    default: 'epsg:4258'
acceptCrs:
  name: Accept-Crs
  in: header
  required: false
  description: Gewenste CRS van de coördinaten in de response.
  schema:
    type: string
    enum:
      - 'epsg:4258'
      - 'epsg:28992'
    default: 'epsg:4258'
expand:
  in: query
  name: expand
  description: Hier kan aangegeven worden welke gerelateerde resources meegeladen moeten worden. Resources en velden van resources die gewenst zijn kunnen in de expand parameter kommagescheiden worden opgegeven. Specifieke velden van resource kunnen worden opgegeven door het opgeven van de resource-naam gevolgd door de veldnaam, met daartussen een punt. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/expand.feature).
  required: false
  schema:
    type: string
    example: kinderen,adressen.postcode,adressen.huisnummer
fields:
  in: query
  name: fields
  description: Geeft de mogelijkheid de inhoud van de body van het antwoord naar behoefte aan te passen. Bevat een door komma's gescheiden lijst van attribuutnamen. Links naar relaties kunnen ook worden gevraagd door deze op te nemen in fields. Wanneer de parameter fields niet is opgenomen, worden alle gedefinieerde attributen die een waarde hebben en alle (links naar) relaties teruggegeven. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/fields.feature)
  required: false
  schema:
    type: string
    example: id,onderwerp,aanvrager,wijzig_datum
